#!/usr/bin/env python
"""hover_nongit_integrity_check.py -- content-hash tracking for the
gitignored/generated files this role's own tooling depends on, closing the
gap named directly: the content-hash freshness sweep (seq 306) can diff any
file with git history, but a file EXCLUDED from git by design (a generated
credential-adjacent shim) has no history to diff at all, and its own
validation stood only on a one-time content check with nothing re-checking
it later.

SCOPE, DELIBERATELY NARROW: gitignored/generated files whose CONTENT is
code/logic this role has read or driven and whose correctness matters --
never a credential file itself (the token's VALUE is never read, hashed,
or recorded here; only code files that happen to embed a token's PATH, not
its value, are in scope), and never incidental data files (a meta.json
expiry record, a fires log) whose expected behaviour is to change.

TRACKED FILES, both directories this role's own tooling touches:
  H1's .mirror-askpass.py / .mirror-askpass.bat  (generated by his
    hover_backup_mirror.py's _write_shim(); driven and content-read during
    this session's tool_provenance_check.py validation, no git history --
    gitignored by his own .gitignore)
  hover2's own .mirror2-askpass-real.py / .mirror2-askpass-real.bat /
    .mirror2-askpass-empty.py / .mirror2-askpass-empty.bat  (generated by
    this directory's own hover2_log_mirror.py's _write_shim(); not yet
    created as of this tool's first run -- no push has happened -- tracked
    from ABSENT so their first appearance is itself a recorded event, not
    a silent baseline)

RECORD is a JSON object keyed by label, each holding {path, status,
sha256, recorded_ts}. status is one of PRESENT (sha256 populated) or
ABSENT (sha256 null) -- never conflated. --record overwrites the baseline
for every tracked file with its CURRENT real state; --check compares the
CURRENT real state against that baseline and reports one of four outcomes
per file, never folding any into a silent pass:
  UNCHANGED        present then, present now, same hash
  CHANGED          present then, present now, DIFFERENT hash -- the
                    exact case a git diff would show for a tracked file
  NEWLY-PRESENT     absent then, present now -- a file this role never
                    saw before has appeared; worth a look, not a defect
  MISSING           present then, absent now -- a generated file that
                    existed disappeared; also worth a look
  STILL-ABSENT      absent then, absent now -- expected for hover2's own
                    shims until the first mirror push

No file's TEXT content is ever printed by --check or --record beyond its
hash; a --show-content flag exists ONLY for the askpass .py/.bat pair,
which are code files this role has already read and reported in full
(they embed a file PATH, never a token value), never for anything with
'token' in its name -- refused structurally, not by convention.

Run:
  python hover_nongit_integrity_check.py --record
  python hover_nongit_integrity_check.py --check
  python hover_nongit_integrity_check.py --selftest
"""
import hashlib
import io
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
H1_DIR = r'C:\Users\marsh\.claude\projects\C--Users-marsh-Documents-SAIRN-hover\hover-audit-log'
BASELINE = os.path.join(HERE, 'nongit_integrity_baseline.json')

TRACKED = {
    'h1.mirror-askpass.py': os.path.join(H1_DIR, '.mirror-askpass.py'),
    'h1.mirror-askpass.bat': os.path.join(H1_DIR, '.mirror-askpass.bat'),
    'hover2.mirror2-askpass-real.py': os.path.join(HERE, '.mirror2-askpass-real.py'),
    'hover2.mirror2-askpass-real.bat': os.path.join(HERE, '.mirror2-askpass-real.bat'),
    'hover2.mirror2-askpass-empty.py': os.path.join(HERE, '.mirror2-askpass-empty.py'),
    'hover2.mirror2-askpass-empty.bat': os.path.join(HERE, '.mirror2-askpass-empty.bat'),
    # Added 2026-09-29 (seventh item, direct instruction). NOT ACTUALLY
    # GITIGNORE-EXEMPT THE WAY THE OTHER SIX ARE: `git ls-files` shows this
    # path IS tracked in H1's repo despite appearing in his .gitignore --
    # committed once (a --mirror snapshot's `git add -A`) before the
    # ignore rule was added, and .gitignore never retroactively untracks
    # an already-tracked path. So a git-diff-based sweep (seq 306's
    # method) COULD reach this file; it is tracked here anyway per direct
    # instruction, as an independent, non-git-diff-reliant second record
    # of the same content -- content is confirmed non-secret (token
    # EXPIRY DATE, remote URL, a push counter; never the token itself).
    'h1.mirror-config.json': os.path.join(H1_DIR, '.mirror-config.json'),
}

# never allow a file with this substring in its label or path into the
# registry, or into --show-content -- a structural refusal, not a
# reviewer's promise to remember
_FORBIDDEN = 'token'


def _refuse_if_forbidden(label, path):
    if _FORBIDDEN in label.lower() or _FORBIDDEN in os.path.basename(path).lower():
        raise ValueError('refusing to track %r (%s) -- credential-shaped '
                         'name, out of scope by structural rule, not '
                         'convention' % (label, path))


for _label, _path in TRACKED.items():
    _refuse_if_forbidden(_label, _path)


def file_state(path):
    """(status, sha256|None) for one real file on disk. Never raises on a
    missing file -- ABSENT is a real, first-class state."""
    if not os.path.isfile(path):
        return ('ABSENT', None)
    with io.open(path, 'rb') as f:
        return ('PRESENT', hashlib.sha256(f.read()).hexdigest())


def load_baseline(path=BASELINE):
    if not os.path.isfile(path):
        return {}
    with io.open(path, encoding='utf-8') as f:
        return json.load(f)


def save_baseline(data, path=BASELINE):
    with io.open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=1, sort_keys=True)
        f.write('\n')


def record(tracked=None, path=BASELINE, now=None):
    tracked = tracked if tracked is not None else TRACKED
    now = now or time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())
    out = {}
    for label, p in sorted(tracked.items()):
        status, sha = file_state(p)
        out[label] = {'path': p, 'status': status, 'sha256': sha,
                      'recorded_ts': now}
    save_baseline(out, path)
    return out


def compare(baseline, tracked=None):
    """{label: outcome} for the four-state contract. A label present in
    tracked but missing from baseline entirely is its own fifth state,
    UNRECORDED -- never silently treated as STILL-ABSENT, which would hide
    a tracked file nobody ever took a baseline of at all."""
    tracked = tracked if tracked is not None else TRACKED
    out = {}
    for label, p in sorted(tracked.items()):
        if label not in baseline:
            out[label] = 'UNRECORDED'
            continue
        then = baseline[label]
        now_status, now_sha = file_state(p)
        if then['status'] == 'ABSENT' and now_status == 'ABSENT':
            out[label] = 'STILL-ABSENT'
        elif then['status'] == 'ABSENT' and now_status == 'PRESENT':
            out[label] = 'NEWLY-PRESENT'
        elif then['status'] == 'PRESENT' and now_status == 'ABSENT':
            out[label] = 'MISSING'
        elif then['sha256'] == now_sha:
            out[label] = 'UNCHANGED'
        else:
            out[label] = 'CHANGED'
    return out


def cmd_check():
    baseline = load_baseline()
    results = compare(baseline)
    changed = [l for l, o in results.items() if o in ('CHANGED', 'MISSING')]
    interesting = [l for l, o in results.items()
                  if o in ('CHANGED', 'MISSING', 'NEWLY-PRESENT', 'UNRECORDED')]
    for label, outcome in sorted(results.items()):
        print('  %-35s %s' % (label, outcome))
    print()
    print('CHECKED/UNIVERSE: %d of %d tracked files have a real baseline '
          'and were compared' % (len(results) - sum(1 for o in results.values()
                                                     if o == 'UNRECORDED'),
                                 len(results)))
    if interesting:
        print('NEEDS ATTENTION: %s' % ', '.join(sorted(interesting)))
    return 1 if changed else 0


def cmd_record():
    out = record()
    for label, row in sorted(out.items()):
        print('  %-35s %-8s %s' % (label, row['status'],
                                   (row['sha256'] or '-')[:16]))
    print('baseline written: %s' % BASELINE)
    return 0


# -- selftest, tests-first per this role's own standard, with a known-bad
#    control per outcome class --------------------------------------------

def selftest():
    import tempfile
    bad = []
    total = [0]

    def ck(name, cond):
        total[0] += 1
        print(('  ok   ' if cond else '  FAIL ') + name)
        if not cond:
            bad.append(name)

    ck('the forbidden-name guard refuses a token-named label',
       _raises(ValueError, lambda: _refuse_if_forbidden('x.token.py', 'x')))
    ck('...and refuses a token-named path even with a clean label',
       _raises(ValueError, lambda: _refuse_if_forbidden('shim', 'a.token.py')))
    ck('...and a clean label+path passes through with no exception',
       _no_raise(lambda: _refuse_if_forbidden('shim.py', 'a.py')))

    tmp = tempfile.mkdtemp()
    a = os.path.join(tmp, 'a.py')
    b = os.path.join(tmp, 'b.py')  # never created -- the absent fixture
    io.open(a, 'w', encoding='utf-8').write('print(1)\n')
    t = {'A': a, 'B': b}

    base1 = record(t, path=os.path.join(tmp, 'base1.json'), now='T1')
    ck('record(): A is PRESENT with a real sha256',
       base1['A']['status'] == 'PRESENT' and len(base1['A']['sha256']) == 64)
    ck('record(): B (never created) is ABSENT with sha256=None',
       base1['B']['status'] == 'ABSENT' and base1['B']['sha256'] is None)

    r1 = compare(base1, t)
    ck('compare(): unmodified A reads UNCHANGED', r1['A'] == 'UNCHANGED')
    ck('compare(): still-missing B reads STILL-ABSENT', r1['B'] == 'STILL-ABSENT')

    io.open(a, 'w', encoding='utf-8').write('print(2)\n')  # real content change
    r2 = compare(base1, t)
    ck('compare(): a real content change on A reads CHANGED', r2['A'] == 'CHANGED')

    io.open(b, 'w', encoding='utf-8').write('print(3)\n')  # B appears
    r3 = compare(base1, t)
    ck('compare(): B appearing for the first time reads NEWLY-PRESENT, '
       'never silently folded into UNCHANGED', r3['B'] == 'NEWLY-PRESENT')

    os.remove(a)
    r4 = compare(base1, t)
    ck('compare(): A disappearing after being present reads MISSING',
       r4['A'] == 'MISSING')

    r5 = compare({}, t)
    ck('compare(): a label with NO baseline at all reads UNRECORDED, '
       'never STILL-ABSENT (that would hide a file nobody ever took a '
       'baseline of)', r5['A'] == 'UNRECORDED' and r5['B'] == 'UNRECORDED')

    # KNOWN-BAD CONTROL: a comparator that always says UNCHANGED must be
    # caught by a fixture where the real answer is CHANGED
    def broken_compare(baseline, tracked):
        return dict((l, 'UNCHANGED') for l in tracked)
    io.open(a, 'w', encoding='utf-8').write('print(1)\n')  # restore then diverge
    base2 = record(t, path=os.path.join(tmp, 'base2.json'), now='T2')
    io.open(a, 'w', encoding='utf-8').write('print(999)\n')
    real = compare(base2, t)
    fake = broken_compare(base2, t)
    ck('KNOWN-BAD CONTROL: a comparator that always reports UNCHANGED '
       'disagrees with the real CHANGED verdict on this fixture -- proving '
       'the real comparator is load-bearing, not a formality',
       real['A'] == 'CHANGED' and fake['A'] == 'UNCHANGED' and real != fake)

    ck('TRACKED registry itself passes the forbidden-name guard '
       '(no entry named or pathed with "token")',
       all('token' not in l.lower() and 'token' not in os.path.basename(p).lower()
           for l, p in TRACKED.items()))

    print('%d ok, %d failed' % (total[0] - len(bad), len(bad)))
    return 0 if not bad else 1


def _raises(exc, fn):
    try:
        fn()
        return False
    except exc:
        return True


def _no_raise(fn):
    try:
        fn()
        return True
    except Exception:
        return False


def main(argv):
    if '--selftest' in argv:
        return selftest()
    if '--record' in argv:
        return cmd_record()
    if '--check' in argv:
        return cmd_check()
    print(__doc__)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
