---- MODULE MCRoleGates ----
\* GENERATED by tools/role_gate_mc_config.py -- do not hand-edit.
\* Regenerate after any change to an app's role sets; --check reports drift.
\*
\* TLC cannot take a function literal in a .cfg, so the constants live here
\* as OPERATORS and the .cfg SUBSTITUTES them. RoleGates.tla is untouched by
\* the act of checking it.
\*
\* THE VALUES ARE REAL -- read by requiring each api/*-auth.js and taking the
\* set the code would use, exported or internal. Not retyped.
\*
\* THIS INSTANCE IS 10 OF 16 APPS, and the other six are a BOUND, not a pass:
\*     sairnbiz         no management
\*     sairncode        no management
\*     sairngrounds     no management
\*     sairnlaw         no management
\*     sairnscape       no management
\*     stonedesk        no management
\*
\* Those six have NO management concept -- four of them say so in as many
\* words, and add that inventing one "would be a new authorisation tier
\* introduced as a side effect of an unrelated change". Supplying one here
\* to widen the instance would either invent that tier or set Management =
\* Provisioning, which makes ProvisioningIsManagement true BY CONSTRUCTION
\* and buys a green that means nothing.
\*
\* Role names carrying a dot are renamed with underscores because a model
\* value must be an identifier. No semantic content:
\*     ceremonial.manage      -> ceremonial_manage
\*     chaplain.pastoral      -> chaplain_pastoral
\*     finance.write          -> finance_write
\*     history.write          -> history_write
\*     legal.review           -> legal_review
\*     member.admit           -> member_admit
\*     post.govern            -> post_govern
\*     post.govern.deputy     -> post_govern_deputy
\*     records.write          -> records_write
\*     services.refer         -> services_refer
EXTENDS RoleGates

\* Declared so TLC treats these as MODEL VALUES; the .cfg assigns each to itself.
CONSTANTS
    NoApp, activities, admin, assistant, billing, caregiver,
    ceremonial_manage, chaplain_pastoral, coordinator, crew, designer, director,
    dvm, e1, e2, estimator, finance_write, foreman,
    frontdesk, history_write, legal_review, manager, med_aide, member_admit,
    nursing, office, owner, pm, post_govern, post_govern_deputy,
    provider, records_write, sairnbuild, sairncare, sairndental, sairndesign,
    sairnfreedom, sairnlegacy, sairnmechanical, sairnroofing, sairnsenior, sairnvet,
    sales, scheduler, services_refer, staff, tech

MCApps == {sairnbuild, sairncare, sairndental, sairndesign, sairnfreedom, sairnlegacy, sairnmechanical, sairnroofing, sairnsenior, sairnvet}

MCRoles == {activities, admin, assistant, billing, caregiver, ceremonial_manage, chaplain_pastoral, coordinator, crew, designer, director, dvm, estimator, finance_write, foreman, frontdesk, history_write, legal_review, manager, med_aide, member_admit, nursing, office, owner, pm, post_govern, post_govern_deputy, provider, records_write, sales, scheduler, services_refer, staff, tech}

MCEmployees == {e1, e2}

MCProvisioning == [a \in MCApps |->
    CASE a = sairnbuild -> {owner}
      [] a = sairncare -> {owner}
      [] a = sairndental -> {owner}
      [] a = sairndesign -> {owner}
      [] a = sairnfreedom -> {post_govern, post_govern_deputy}
      [] a = sairnlegacy -> {owner}
      [] a = sairnmechanical -> {owner}
      [] a = sairnroofing -> {owner}
      [] a = sairnsenior -> {owner}
      [] a = sairnvet -> {owner}]

MCManagement == [a \in MCApps |->
    CASE a = sairnbuild -> {office, owner}
      [] a = sairncare -> {billing, owner}
      [] a = sairndental -> {owner}
      [] a = sairndesign -> {office, owner}
      [] a = sairnfreedom -> {post_govern, post_govern_deputy}
      [] a = sairnlegacy -> {director, owner}
      [] a = sairnmechanical -> {admin, owner}
      [] a = sairnroofing -> {admin, owner}
      [] a = sairnsenior -> {billing, owner}
      [] a = sairnvet -> {manager, owner}]

MCAuthenticated == [a \in MCApps |->
    CASE a = sairnbuild -> {office, owner, pm}
      [] a = sairncare -> {activities, billing, caregiver, med_aide, nursing, owner}
      [] a = sairndental -> {frontdesk, owner, provider}
      [] a = sairndesign -> {designer, office, owner}
      [] a = sairnfreedom -> {ceremonial_manage, chaplain_pastoral, finance_write, history_write, legal_review, member_admit, post_govern, post_govern_deputy, records_write, services_refer}
      [] a = sairnlegacy -> {director, owner, staff}
      [] a = sairnmechanical -> {admin, owner, sales, tech}
      [] a = sairnroofing -> {admin, crew, estimator, foreman, owner}
      [] a = sairnsenior -> {billing, caregiver, coordinator, owner, scheduler}
      [] a = sairnvet -> {assistant, dvm, frontdesk, manager, owner, tech}]

MCBroadRead == [a \in MCApps |->
    CASE a = sairnbuild -> {office, owner, pm}
      [] a = sairncare -> {activities, billing, caregiver, med_aide, nursing, owner}
      [] a = sairndental -> {frontdesk, owner, provider}
      [] a = sairndesign -> {designer, office, owner}
      [] a = sairnfreedom -> {ceremonial_manage, chaplain_pastoral, finance_write, history_write, legal_review, member_admit, post_govern, post_govern_deputy, records_write, services_refer}
      [] a = sairnlegacy -> {director, owner, staff}
      [] a = sairnmechanical -> {admin, owner, sales, tech}
      [] a = sairnroofing -> {admin, estimator, owner}
      [] a = sairnsenior -> {billing, caregiver, coordinator, owner, scheduler}
      [] a = sairnvet -> {assistant, dvm, frontdesk, manager, owner, tech}]

MCVocabulary == [a \in MCApps |->
    CASE a = sairnbuild -> {office, owner, pm}
      [] a = sairncare -> {activities, billing, caregiver, med_aide, nursing, owner}
      [] a = sairndental -> {frontdesk, owner, provider}
      [] a = sairndesign -> {designer, office, owner}
      [] a = sairnfreedom -> {ceremonial_manage, chaplain_pastoral, finance_write, history_write, legal_review, member_admit, post_govern, post_govern_deputy, records_write, services_refer}
      [] a = sairnlegacy -> {director, owner, staff}
      [] a = sairnmechanical -> {admin, owner, sales, tech}
      [] a = sairnroofing -> {admin, crew, estimator, foreman, owner}
      [] a = sairnsenior -> {billing, caregiver, coordinator, owner, scheduler}
      [] a = sairnvet -> {assistant, dvm, frontdesk, manager, owner, tech}]

MCStatedAuthenticated == {sairndental, sairnmechanical}

====
