---- MODULE MCRoleGates ----
\* GENERATED by tools/role_gate_mc_config.py -- do not hand-edit.
\*
\* TLC cannot take a function literal in a .cfg, so the constants become
\* OPERATORS here and the .cfg SUBSTITUTES them. RoleGates.tla is not touched
\* by the act of checking it. This is the wrapper the TLA+ Toolbox emits.
\*
\* FUNCTIONS ARE BUILT WITH CASE, NOT [k |-> v]. The latter is a RECORD in
\* TLA+ and its keys are strings, so applying it to a model value fails with
\* "attempted to apply record to a non-string value" -- which it did, here,
\* before this was corrected.
\*
\* THE VALUES ARE REAL: read by REQUIRING each api/*-auth.js and taking what it
\* exports, the same source tools/role_gate_invariants.js reads -- not retyped.
\* SIX of sixteen apps export a complete PROVISIONING/MANAGEMENT/vocabulary set.
\* THE OTHER TEN ARE ABSENT FROM THIS INSTANCE, which BOUNDS the run and is NOT
\* a pass for them -- the same distinction role_gate_invariants.js draws when it
\* reports 22 checks as not-checkable.
\*
\* Role names carrying a dot (post.govern, finance.write, ...) are renamed with
\* underscores because a TLA+ model value must be an identifier. No semantic
\* content: same sets, same members, same relations.
EXTENDS RoleGates

\* Declared so TLC treats these as MODEL VALUES; the .cfg assigns each to itself.
CONSTANTS
    NoApp, admin, assistant, billing, caregiver, ceremonial_manage,
    chaplain_pastoral, coordinator, crew, dvm, e1, e2,
    estimator, finance_write, foreman, frontdesk, history_write, legal_review,
    manager, member_admit, owner, post_govern, post_govern_deputy, provider,
    records_write, sairndental, sairnfreedom, sairnmechanical, sairnroofing, sairnsenior,
    sairnvet, sales, scheduler, services_refer, tech

MCApps == {sairndental, sairnmechanical, sairnroofing, sairnsenior, sairnfreedom, sairnvet}

MCRoles == {admin, assistant, billing, caregiver, ceremonial_manage, chaplain_pastoral, coordinator, crew, dvm, estimator, finance_write, foreman, frontdesk, history_write, legal_review, manager, member_admit, owner, post_govern, post_govern_deputy, provider, records_write, sales, scheduler, services_refer, tech}

MCEmployees == {e1, e2}

MCProvisioning == [a \in MCApps |->
    CASE a = sairndental -> {owner}
      [] a = sairnmechanical -> {owner}
      [] a = sairnroofing -> {owner}
      [] a = sairnsenior -> {owner}
      [] a = sairnfreedom -> {post_govern, post_govern_deputy}
      [] a = sairnvet -> {owner}]

MCManagement == [a \in MCApps |->
    CASE a = sairndental -> {owner}
      [] a = sairnmechanical -> {admin, owner}
      [] a = sairnroofing -> {admin, owner}
      [] a = sairnsenior -> {billing, owner}
      [] a = sairnfreedom -> {post_govern, post_govern_deputy}
      [] a = sairnvet -> {manager, owner}]

MCAuthenticated == [a \in MCApps |->
    CASE a = sairndental -> {frontdesk, owner, provider}
      [] a = sairnmechanical -> {admin, owner, sales, tech}
      [] a = sairnroofing -> {admin, crew, estimator, foreman, owner}
      [] a = sairnsenior -> {billing, caregiver, coordinator, owner, scheduler}
      [] a = sairnfreedom -> {ceremonial_manage, chaplain_pastoral, finance_write, history_write, legal_review, member_admit, post_govern, post_govern_deputy, records_write, services_refer}
      [] a = sairnvet -> {assistant, dvm, frontdesk, manager, owner, tech}]

MCBroadRead == [a \in MCApps |->
    CASE a = sairndental -> {frontdesk, owner, provider}
      [] a = sairnmechanical -> {admin, owner, sales, tech}
      [] a = sairnroofing -> {admin, estimator, owner}
      [] a = sairnsenior -> {billing, caregiver, coordinator, owner, scheduler}
      [] a = sairnfreedom -> {ceremonial_manage, chaplain_pastoral, finance_write, history_write, legal_review, member_admit, post_govern, post_govern_deputy, records_write, services_refer}
      [] a = sairnvet -> {assistant, dvm, frontdesk, manager, owner, tech}]

MCVocabulary == [a \in MCApps |->
    CASE a = sairndental -> {frontdesk, owner, provider}
      [] a = sairnmechanical -> {admin, owner, sales, tech}
      [] a = sairnroofing -> {admin, crew, estimator, foreman, owner}
      [] a = sairnsenior -> {billing, caregiver, coordinator, owner, scheduler}
      [] a = sairnfreedom -> {ceremonial_manage, chaplain_pastoral, finance_write, history_write, legal_review, member_admit, post_govern, post_govern_deputy, records_write, services_refer}
      [] a = sairnvet -> {assistant, dvm, frontdesk, manager, owner, tech}]

MCStatedAuthenticated == {sairndental, sairnmechanical}

====
