#!/usr/bin/env python
"""regenerate_repoint_list.py -- the MOVED-SINCE repoint list generator,
promoted from three rounds of inline one-off scripts to a real tool with
its own self-check (2026-09-30, queue-3 item 9).

THE INCIDENT THIS EXISTS TO PREVENT, NAMED PLAINLY: the FIRST repoint
list this role shipped (queue 1, generated by repointing to the anchor
occurrence nearest the OLD cited line) was independently re-derived on
15 sampled rows and came back 9 WRONG OF 15 -- a 60% error rate on a
list this role had already reported as a finished, routable deliverable.
The SECOND list (queue 2, content-first: exact derivation-line text
matched against HEAD, register row-name fallback) was independently
re-derived on a DIFFERENT 15-row sample by a genuinely different method
(difflib SequenceMatcher alignment, not the classifier's own anchor
logic) and came back 15/15 -- but "came back clean this once" is a
result, not a guarantee, and nothing forced that re-check to happen
before the list was reported as ready. This tool is the fix: the
generator no longer gets to report success without proving a sample of
its own output first.

METHOD: content-first exact match against HEAD (falls back to register
row-name match for rewritten register rows), IDENTICAL to what shipped
in queue 2/3 -- this file promotes that method, it does not replace it.

SELF-CHECK, feasible and built-in, not bolted on after: after generating
the full repoint list, draw a random sample (SAMPLE_N, default 15) of its
own output rows and INDEPENDENTLY re-derive each one by a second method
(difflib SequenceMatcher alignment between the derivation blob and HEAD --
genuinely different code path from the exact-line-match the generator
itself uses, so a bug shared by both methods is still possible but a bug
in only one is not silently blessed by re-running the same one). Any
disagreement between the generator's own answer and the independent
re-derivation REFUSES to emit the list at all -- exit 2, naming every
disagreeing row, rather than printing a list with a known-wrong row in it.
"""
import json
import os
import random
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import citation_class_check as cc  # noqa: E402

LOG = cc.LOG
SAMPLE_N = 15


ROW_NAME = re.compile(r'^\|\s*`([\w.]+)`\s*\|')


def _head_lines_cache(repo):
    cache = {}

    def head(path):
        if path not in cache:
            cache[path] = cc.head_lines(repo, path)
        return cache[path]
    return head


def generate(entries, repo=cc.REPO):
    """[(path, old_line, new_line, how, seqs)] -- the generator's own
    answer, exact-content-match first, register row-name fallback."""
    head = _head_lines_cache(repo)
    out = {}
    cchanged = []
    for e in entries:
        for path, ln, cls, sent, hb in cc.classify(e, repo=repo, detail=True):
            if cls != 'MOVED-SINCE':
                continue
            rec = (e.get('source_shas') or {}).get(path)
            dl = cc.blob_lines(repo, rec['sha'], path) if rec else None
            hl = head(path)
            new, how = None, None
            if dl and hl and ln <= len(dl):
                content = dl[ln - 1]
                if content.strip():
                    exact = [i for i, l in enumerate(hl, 1) if l == content]
                    if exact:
                        new = min(exact, key=lambda i: abs(i - ln))
                        how = 'content'
                if new is None:
                    # ROW-NAME FALLBACK: a register row REWRITTEN wholesale
                    # (the cell's own prose changed, not just the code it
                    # cites) has no verbatim line match at HEAD. Find the
                    # SAME resource's row by name instead -- only when it
                    # resolves to exactly one row, so an ambiguous or
                    # renamed/removed resource still falls through to
                    # CONTENT-CHANGED rather than guessing.
                    m = ROW_NAME.match(content)
                    if m:
                        matches = [i for i, l in enumerate(hl, 1)
                                  if ROW_NAME.match(l)
                                  and ROW_NAME.match(l).group(1) == m.group(1)]
                        if len(matches) == 1:
                            new, how = matches[0], 'row-name'
            if new is None:
                cchanged.append((e['seq'], path, ln))
                continue
            out.setdefault((path, ln), {'new': new, 'how': how,
                                        'seqs': set()})['seqs'].add(e['seq'])
    rows = [(p, l, v['new'], v['how'], sorted(v['seqs']))
            for (p, l), v in out.items()]
    return rows, cchanged


def _independent_rederive(path, old_line, repo=cc.REPO, entries_by_seq=None,
                          seq=None):
    """SequenceMatcher alignment -- genuinely different code path from
    generate()'s exact-match: maps old_line through a full-file diff
    alignment between the derivation blob and HEAD, the same method used
    to independently re-verify the queue-2 list (15/15)."""
    import difflib
    e = entries_by_seq[seq]
    rec = (e.get('source_shas') or {}).get(path)
    if not rec:
        return None
    dl = cc.blob_lines(repo, rec['sha'], path)
    hl = cc.head_lines(repo, path)
    if not dl or not hl or old_line > len(dl):
        return None
    sm = difflib.SequenceMatcher(None, dl, hl, autojunk=False)
    for tag, a1, a2, b1, b2 in sm.get_opcodes():
        if tag == 'equal' and a1 <= old_line - 1 < a2:
            return b1 + (old_line - 1 - a1) + 1
    return None


def self_check(rows, entries_by_seq, repo=cc.REPO, n=SAMPLE_N, rng=None):
    """Draw n rows, re-derive each by the independent method, and return
    (ok, disagreements). A row the independent method cannot resolve at
    all (None) is NOT counted as a disagreement -- it is a weaker method
    limitation, not evidence the generator was wrong; only a resolved,
    DIFFERING answer counts."""
    rng = rng or random
    pool = [r for r in rows if r[4]]
    sample = rng.sample(pool, min(n, len(pool)))
    disagreements = []
    for path, old_line, new_line, how, seqs in sample:
        alt = _independent_rederive(path, old_line, repo, entries_by_seq,
                                    seqs[0])
        if alt is not None and alt != new_line:
            disagreements.append((path, old_line, new_line, alt, seqs[0]))
    return (not disagreements), disagreements


def main(argv):
    log_path = LOG
    entries = [json.loads(l) for l in
               open(log_path, encoding='utf-8')] if os.path.isfile(
        log_path) else []
    if not entries:
        print('COULD NOT RUN: no log entries to generate from at %s'
              % log_path)
        return 2
    rows, cchanged = generate(entries)
    entries_by_seq = {e['seq']: e for e in entries}
    ok, dis = self_check(rows, entries_by_seq)
    if not ok:
        print('REFUSED: self-check found %d disagreement(s) between the '
              'generator and an independent re-derivation -- nothing '
              'emitted.' % len(dis))
        for path, old, gen, alt, seq in dis:
            print('  %s:%d -- generator says :%d, independent re-derive '
                  'says :%d (seq %d)' % (path, old, gen, alt, seq))
        return 2
    out_path = os.path.join(HERE, 'moved_since_repoint_list.txt')
    lines = ['%s:%d -> :%d (%s; seqs %s)'
             % (p, l, n, how, ','.join(map(str, s)))
             for p, l, n, how, s in sorted(rows)]
    lines.append('')
    lines.append('CONTENT-CHANGED (skipped): '
                 + ', '.join('seq %d %s:%d' % t for t in cchanged))
    open(out_path, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    print('SELF-CHECK PASSED (%d of %d sampled rows independently '
          'confirmed). Wrote %d repoints, %d content-changed, to %s'
          % (min(SAMPLE_N, len([r for r in rows if r[4]])),
             min(SAMPLE_N, len([r for r in rows if r[4]])),
             len(rows), len(cchanged), out_path))
    return 0


def _fixtures():
    ok, bad = [0], [0]

    def ck(name, cond):
        (ok if cond else bad)[0] += 1
        print('  %s %s' % ('ok  ' if cond else 'FAIL', name))

    import tempfile
    import shutil
    d = tempfile.mkdtemp(prefix='regen_repoint_fx_')
    try:
        def g(*a):
            subprocess.run(['git'] + list(a), cwd=d, capture_output=True,
                           check=True,
                           env=dict(os.environ, GIT_AUTHOR_NAME='fx',
                                    GIT_AUTHOR_EMAIL='f@x',
                                    GIT_COMMITTER_NAME='fx',
                                    GIT_COMMITTER_EMAIL='f@x'))
        g('init', '-q')
        v1 = ['# pad'] * 9 + ['def frobnicate():', '    return 1']
        open(os.path.join(d, 'app.py'), 'w').write('\n'.join(v1) + '\n')
        g('add', '-A'); g('commit', '-q', '-m', 'v1')
        sha1 = subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=d,
                              capture_output=True,
                              text=True).stdout.strip()
        open(os.path.join(d, 'app.py'), 'w').write(
            '\n'.join(['# new'] * 5 + v1) + '\n')
        g('add', '-A'); g('commit', '-q', '-m', 'v2 shifts by 5')

        entry = {'seq': 1, 'summary': '`frobnicate` sits at app.py:10 today.',
                 'source_shas': {'app.py': {'sha': sha1}}}
        rows, cchanged = generate([entry], repo=d)
        ck('generator correctly repoints the moved def to its real HEAD '
           'line', any(p == 'app.py' and old == 10 and new == 15
                       for p, old, new, how, seqs in rows))

        entries_by_seq = {1: entry}
        ok_check, dis = self_check(rows, entries_by_seq, repo=d, n=1)
        ck('self-check AGREES on a genuinely correct row -- no false '
           'refusal', ok_check and not dis)

        # ── ROW-NAME FALLBACK (weekly-cleanup item 2): a register row
        # REWRITTEN wholesale (the cell's own prose changed, not just the
        # code it cites) has no verbatim line match at HEAD -- fall back
        # to matching the register row by its OWN name.
        os.makedirs(os.path.join(d, 'docs'))
        reg_old = ['# pad'] * 8 + [
            '| Resource | Evidence |', '|---|---|',
            '| `sf_bottle_fills` | old wording here |']
        open(os.path.join(d, 'docs', 'REG.md'), 'w').write(
            '\n'.join(reg_old) + '\n')
        g('add', '-A'); g('commit', '-q', '-m', 'reg v1')
        reg_sha = subprocess.run(
            ['git', 'rev-parse', 'HEAD:docs/REG.md'], cwd=d,
            capture_output=True, text=True).stdout.strip()
        reg_new = ['# pad'] * 8 + [
            '| Resource | Evidence |', '|---|---|',
            '| `unrelated_row` | padding |'] + ['# pad'] * 20 + [
            '| `sf_bottle_fills` | REWRITTEN wording, different '
            'text entirely |']
        open(os.path.join(d, 'docs', 'REG.md'), 'w').write(
            '\n'.join(reg_new) + '\n')
        g('add', '-A'); g('commit', '-q', '-m', 'reg rewritten')
        reg_entry = {'seq': 2,
                    'summary': 'docs/REG.md:11 sf_bottle_fills evidence.',
                    'source_shas': {'docs/REG.md': {'sha': reg_sha}}}
        reg_rows, reg_cchanged = generate([reg_entry], repo=d)
        ck('ROW-NAME FALLBACK: a rewritten register row with no verbatim '
           'HEAD match still repoints, via its own row name, not '
           'CONTENT-CHANGED',
           any(p == 'docs/REG.md' and old == 11 and new == 32
               for p, old, new, how, seqs in reg_rows)
           and not any(s == 2 for s, p, l in reg_cchanged))
        ck('ROW-NAME FALLBACK: the repointed row is tagged row-name, not '
           'content, so a reader can tell the two methods apart',
           any(p == 'docs/REG.md' and how == 'row-name'
               for p, old, new, how, seqs in reg_rows))

        # sabotage: force the generator's own answer to be wrong and
        # confirm self-check catches it (the mutation-test discipline
        # this role holds every OTHER checker to, applied to this one)
        import types
        real_generate = generate

        def poisoned(entries, repo=cc.REPO):
            rows, cchanged = real_generate(entries, repo=repo)
            return [(p, old, new + 1000, how, seqs)
                    for p, old, new, how, seqs in rows], cchanged
        rows_bad, _ = poisoned([entry], repo=d)
        ok_bad, dis_bad = self_check(rows_bad, entries_by_seq, repo=d, n=1)
        ck('SABOTAGE: a deliberately wrong generator answer is caught by '
           'the self-check and refuses (proves the check has teeth)',
           not ok_bad and dis_bad)
    finally:
        shutil.rmtree(d, ignore_errors=True)
    print('%d ok, %d failed' % (ok[0], bad[0]))
    return bad[0] == 0


if __name__ == '__main__':
    if '--selftest' in sys.argv[1:]:
        sys.exit(0 if _fixtures() else 1)
    sys.exit(main(sys.argv[1:]))
