#!/usr/bin/env python
"""audit_checkpoint_status.py -- drive the daily audit checkpoint and WRITE DOWN
what it said, somewhere a person reads.

    CRON_SECRET=... python tools/audit_checkpoint_status.py
    CRON_SECRET=... python tools/audit_checkpoint_status.py --verify   # full

── WHY A TOOL AND NOT JUST A LOG LINE ──────────────────────────────────────
`api/audit-checkpoint.js` logs its verdict, and Vercel keeps that log. But
nothing reads it, and a detector nobody reads is not a detector -- item 39 found
exactly that shape one layer down, a correctly-counted warning sent to a
`console.warn` nobody in a clinic would ever open.

Michael's decision, 2026-09-14: **until item 54's heartbeat monitor exists,
checkpoint failures go to the status doc that is already checked before every
dispatch -- a NAMED STOPGAP, not a permanent answer.** Once 54 lands it becomes
the real reader and this tool becomes the thing 54 calls.

── WHICH STATUS DOC, AND WHY NOT THE OBVIOUS ONE ───────────────────────────
`CLAUDE.md` names `docs/SAIRN-OPEN-WORK-INDEX.md` as the dispatch-time document:
it is what a free session filters to pick work, and the claim tooling's own
record already calls a stale row in it "the input the claim tool reads".

This tool does NOT write into that file. `docs/SAIRN-PROCESS-RULES.md` section
2.1 forbids editing one of its rows by splitting on `|`, and a 400-row table
rewritten by a cron-adjacent script is precisely how that rule got written. So:
the verdict goes in its own machine-owned file, `docs/AUDIT-CHECKPOINT-STATUS.md`,
and the index carries ONE hand-written row pointing at it. A pointer is weaker
than a notice printed at dispatch, and that weakness is the reason this is
labelled a stopgap rather than the answer.

── THE ONE RULE THAT MATTERS HERE ──────────────────────────────────────────
**A STATUS DOC THAT CANNOT BE UPDATED MUST NOT KEEP SAYING OK.** If the endpoint
is unreachable, the secret is absent, or the answer is unparseable, this writes a
COULD NOT TELL status and exits 2. Leaving yesterday's clean verdict in place
would be a document asserting a check that never ran -- the failure every
convention in docs/2026-09-13-cross-domain-disciplines.md defends against, and
the one this file would be most embarrassing to commit.

Exit 0 verified clean, 1 a verification FAILED, 2 could not run.
"""
import io
import json
import os
import sys
import time

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, 'tools'))

EXIT_CLEAN, EXIT_FINDING, EXIT_COULD_NOT_RUN = 0, 1, 2
DOC = os.path.join(REPO, 'docs', 'AUDIT-CHECKPOINT-STATUS.md')
DEFAULT_URL = 'https://sairn.vercel.app/api/audit-checkpoint'


def write_status(state, lines, payload=None):
    """Rewrite the status doc WHOLE. Never a line edit -- the file is generated."""
    stamp = time.strftime('%Y-%m-%d %H:%M:%SZ', time.gmtime())
    out = [
        '# Audit checkpoint status',
        '',
        '**GENERATED by `tools/audit_checkpoint_status.py`. Do not hand-edit.**',
        'Rewritten whole on every run; a hand-edit is lost and, worse, would make',
        'this file assert a check that did not happen.',
        '',
        '| | |',
        '|---|---|',
        '| **State** | **%s** |' % state,
        '| Last run | %s |' % stamp,
        '| Endpoint | `%s` |' % os.environ.get('SAIRN_CHECKPOINT_URL', DEFAULT_URL),
        '',
    ] + lines + [
        '',
        '---',
        '',
        '**COULD NOT TELL is a third state and is never folded into OK.** If this',
        'file says COULD NOT TELL, no verification happened -- that is not a clean',
        'run, and the previous clean verdict was deliberately overwritten rather',
        'than left standing.',
        '',
        '**What this can and cannot detect** is in',
        '`sql/audit_checkpoint_schema.sql` and `api/audit-checkpoint.js`. In short:',
        'it catches a row INSERTED into a window that has already closed. It does',
        'not catch an insertion into the current day, and it does not bind anyone',
        'with direct database access, who can rewrite rows and recompute every',
        'checkpoint over them.',
        '',
        '**This is a NAMED STOPGAP reader** (Michael, 2026-09-14). Item 54\'s',
        'liveness monitor is the real one; until it exists, this file is the place',
        'a failure is written down instead of a log line nobody opens.',
    ]
    if payload is not None:
        out += ['', '<details><summary>Raw response</summary>', '',
                '```json', json.dumps(payload, indent=2)[:8000], '```', '',
                '</details>']
    io.open(DOC, 'w', encoding='utf-8', newline='').write('\n'.join(out) + '\n')


def main(argv):
    action = 'verify' if '--verify' in argv else 'checkpoint'
    url = os.environ.get('SAIRN_CHECKPOINT_URL', DEFAULT_URL)
    secret = os.environ.get('CRON_SECRET')
    if not secret:
        write_status('COULD NOT TELL', [
            '**CRON_SECRET is not set in this environment, so the endpoint was not',
            'called and nothing was verified.**',
            '',
            'This is not a finding about the audit logs. It is this tool being unable',
            'to ask. Set CRON_SECRET and run it again.',
        ])
        print('COULD NOT RUN: CRON_SECRET is not set. %s says so rather than '
              'keeping a stale OK.' % os.path.relpath(DOC, REPO))
        return EXIT_COULD_NOT_RUN

    try:
        from sairn_http import fetch_json
    except Exception as e:
        write_status('COULD NOT TELL', [
            '**`tools/sairn_http.py` could not be imported (%s), so the endpoint'
            % type(e).__name__,
            'was not called.** Bare `curl` is deliberately not used as a fallback --',
            'see the push protocol: a 403 from an edge challenge reads as a clean',
            '200 to a naive client, which is how a check reports success it never had.',
        ])
        print('COULD NOT RUN: sairn_http unavailable -- %s' % e)
        return EXIT_COULD_NOT_RUN

    try:
        # ── fetch_json RETURNS Response(status, body), NOT THE BODY ─────────
        # SECOND INSTANCE of the defect found in tools/cron_liveness_check.py
        # on 2026-09-17, and it failed the same way: `payload` was the
        # namedtuple, so `isinstance(payload, dict)` below was ALWAYS false and
        # this tool could only ever write COULD NOT TELL.
        #
        # THE MODULE'S OWN GUARD WAS SHORT-CIRCUITED BY THE BUG. The next line
        # reads `if not isinstance(payload, dict) or 'ok' not in payload:` --
        # and `'ok' not in payload` on a Response raises the TypeError that
        # exists precisely to catch this. It never ran: `not isinstance(...)`
        # was True first, and `or` stops there. The defence was present,
        # correct, and unreachable because of the thing it was defending
        # against.
        resp = fetch_json(url, method='POST', payload={'action': action},
                          headers={'Authorization': 'Bearer ' + secret})
    except Exception as e:
        write_status('COULD NOT TELL', [
            '**The endpoint could not be reached or did not answer usefully.**',
            '',
            '    %s: %s' % (type(e).__name__, str(e)[:400]),
            '',
            'Nothing was verified. A 403 is UNREACHED, not verified-good.',
        ])
        print('COULD NOT RUN: %s: %s' % (type(e).__name__, e))
        return EXIT_COULD_NOT_RUN

    # THE HTTP STATUS IS READ RATHER THAN ASSUMED. fetch_json does NOT raise on
    # an HTTP error -- it returns the parsed error body with its code -- so a
    # 401 from a stale secret would otherwise be parsed as an answer.
    status, payload = resp.status, resp.body
    if status != 200:
        write_status('COULD NOT TELL', [
            '**The endpoint rejected or could not serve this request: HTTP %s.**'
            % status,
            '',
            '`401` means the secret this tool sent does not match the one the',
            'deployment holds -- SET and WRONG, which is indistinguishable from',
            'healthy from the outside. Nothing was verified.',
        ], payload if isinstance(payload, (dict, list)) else None)
        print('COULD NOT RUN: HTTP %s from the endpoint' % status)
        return EXIT_COULD_NOT_RUN
    if not isinstance(payload, dict) or 'ok' not in payload:
        write_status('COULD NOT TELL', [
            '**The endpoint answered something this tool cannot read.** Treated as',
            'could-not-tell rather than guessed at.',
        ], payload if isinstance(payload, (dict, list)) else None)
        print('COULD NOT RUN: unreadable answer')
        return EXIT_COULD_NOT_RUN

    if payload.get('error'):
        write_status('COULD NOT TELL', [
            '**The endpoint refused: `%s`**' % payload['error'].get('code', 'error'),
            '',
            '> %s' % payload['error'].get('message', ''),
            '',
            'A refusal is not a clean verification. NOT_PROVISIONED in particular',
            'means `sql/audit_checkpoint_schema.sql` has never been run.',
        ], payload)
        print('COULD NOT RUN: endpoint refused')
        return EXIT_COULD_NOT_RUN

    results = payload.get('results') or []
    recent = payload.get('recent_verify') or []
    bad = [r for r in list(results) + list(recent) if r.get('ok') is False]
    lines = ['| Table | Checkpoints | Verified this run | Verdict |', '|---|---|---|---|']
    for r in (recent or results):
        lines.append('| `%s` | %s | %s%s | %s |' % (
            r.get('table'), r.get('checkpoints', '-'), r.get('verified', '-'),
            '' if r.get('full', True) else ' (PARTIAL)',
            'FAILED: ' + str(r.get('kind')) if r.get('ok') is False else 'ok'))
    if payload.get('recent_verify_windows'):
        lines += ['', '**The daily run verifies the most recent %d windows, not the '
                  'whole history** -- the bound is stated because a bounded check that '
                  'reads as a full one is the defect this platform keeps finding. Run '
                  'with `--verify` for the full walk.'
                  % payload['recent_verify_windows']]
    if bad:
        lines += ['', '## A verification FAILED', '']
        for b in bad:
            lines.append('- `%s` window ending **%s** -- **%s**'
                         % (b.get('table'), b.get('window_end'), b.get('kind')))
            if b.get('kind') == 'WINDOW_CHANGED':
                lines.append('  - rows at checkpoint **%s**, rows now **%s** -- a count '
                             'that GREW is an INSERTION, the mode the grants leave open; '
                             'an unchanged count means a row\'s CONTENT moved, which the '
                             'grants make impossible through the API and therefore points '
                             'at direct database access.'
                             % (b.get('rows_at_checkpoint'), b.get('rows_now')))
            if b.get('kind') == 'CHAIN_BROKEN':
                lines.append('  - the CHECKPOINT TABLE itself was altered, which is a '
                             'different finding from the audit rows moving.')
        write_status('FAILED', lines, payload)
        print('FINDING: %d verification failure(s). See %s'
              % (len(bad), os.path.relpath(DOC, REPO)))
        return EXIT_FINDING

    write_status('OK', lines, payload)
    print('OK: %s updated.' % os.path.relpath(DOC, REPO))
    return EXIT_CLEAN


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
