#!/usr/bin/env python
"""cron_liveness_check.py -- ask the watchdog, OUT OF BAND, and write it down.

    CRON_SECRET=... python tools/cron_liveness_check.py

── WHY THIS EXISTS SEPARATELY FROM api/cron-watchdog.js ────────────────────
The watchdog runs on the SAME Vercel cron scheduler as the jobs it watches. If
that scheduler stops, the watchdog stops with it and reports nothing -- two
units sharing a failure mode, which is convention 7's exact lesson: a second
copy is not a second opinion.

THIS RUNS OUTSIDE VERCEL. It is the only thing in the repo that survives a total
scheduler outage, because a person or a session invokes it. That is a weaker
guarantee than a hosted uptime check and it is stated as one: a third-party
monitor pinging the endpoint on its own schedule is what would close the
remaining gap, and that is a decision about spend and vendors rather than
something to invent quietly in a file.

── THE RULE THAT MATTERS ───────────────────────────────────────────────────
**A STATUS DOC THAT CANNOT BE UPDATED MUST NOT KEEP SAYING OK.** Unreachable
endpoint, absent secret, unparseable answer, a 503 because the migration has not
been run -- every one of them overwrites the previous verdict with COULD NOT
TELL and exits 2. Leaving yesterday's clean answer in place would be a document
asserting a check that never happened, which is the failure every convention in
docs/2026-09-13-cross-domain-disciplines.md defends against and the single worst
thing a liveness check could do.

Exit 0 every job ok, 1 at least one job is not, 2 could not run.
"""
import io
import json
import os
import sys
import time

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, 'tools'))

EXIT_CLEAN, EXIT_FINDING, EXIT_COULD_NOT_RUN = 0, 1, 2
DOC = os.path.join(REPO, 'docs', 'CRON-LIVENESS-STATUS.md')
DEFAULT_URL = 'https://sairn.vercel.app/api/cron-watchdog'

# What each non-ok status MEANS and what it points at. Written here rather than
# in the endpoint because this is the document a human reads, and a status code
# with no sentence beside it makes the reader go and find the source.
MEANING = {
    'DEAD': 'has missed three or more intervals. The job is not running -- check '
            'the deploy and the vercel.json cron entry before anything else.',
    'LATE': 'has missed two intervals. One slow run does not explain this; two '
            'in a row usually means the last deploy or an upstream timeout.',
    'NEVER_BEAT': 'has NO heartbeat row at all. It has never completed a run -- '
                  'this is usually a job that was scheduled but never deployed, '
                  'or one that predates sql/cron_heartbeat_schema.sql.',
    'FAILING': 'ran on time and reported FAILED. The scheduler is fine; the job '
               'is not. Its own log line carries the reason.',
    'PARTIAL': 'ran on time and did only part of its work. On the alert sweeps '
               'this is the shape that matters most: alive, on schedule, and '
               'notifying nobody.',
    'UNDECLARED': 'is beating but is not in the watchdog EXPECTED_JOBS list -- '
                  'either it was removed from vercel.json and still runs, or its '
                  'name does not match the one being watched.',
}


def write_status(state, lines, payload=None):
    stamp = time.strftime('%Y-%m-%d %H:%M:%SZ', time.gmtime())
    out = [
        '# Cron liveness status',
        '',
        '**GENERATED by `tools/cron_liveness_check.py`. Do not hand-edit.**',
        'Rewritten whole on every run; a hand-edit is lost and, worse, would make',
        'this file assert a check that did not happen.',
        '',
        '| | |',
        '|---|---|',
        '| **State** | **%s** |' % state,
        '| Last run | %s |' % stamp,
        '| Endpoint | `%s` |' % os.environ.get('SAIRN_WATCHDOG_URL', DEFAULT_URL),
        '',
    ] + lines + [
        '',
        '---',
        '',
        '**COULD NOT TELL is a third state and is never folded into OK.** If this',
        'file says COULD NOT TELL, nothing was checked -- that is not a clean run,',
        'and the previous clean verdict was deliberately overwritten rather than',
        'left standing.',
        '',
        '**WHAT THIS CANNOT SEE.** `api/cron-watchdog.js` runs on the same Vercel',
        'cron scheduler as the jobs it watches, so a total scheduler outage',
        'silences both. THIS tool runs outside Vercel and is what survives that --',
        'but only when somebody runs it. A third-party uptime check pinging the',
        'endpoint on its own schedule is what would close the gap, and that is a',
        'spend-and-vendor decision rather than a code change.',
    ]
    if payload is not None:
        out += ['', '<details><summary>Raw response</summary>', '',
                '```json', json.dumps(payload, indent=2)[:8000], '```', '',
                '</details>']
    io.open(DOC, 'w', encoding='utf-8', newline='').write('\n'.join(out) + '\n')


def cannot_tell(lines, payload=None, msg=''):
    write_status('COULD NOT TELL', lines, payload)
    print('COULD NOT RUN: %s %s says so rather than keeping a stale OK.'
          % (msg, os.path.relpath(DOC, REPO)))
    return EXIT_COULD_NOT_RUN


def main(argv):
    url = os.environ.get('SAIRN_WATCHDOG_URL', DEFAULT_URL)
    secret = os.environ.get('CRON_SECRET')
    if not secret:
        return cannot_tell([
            '**CRON_SECRET is not set in this environment, so the watchdog was not',
            'called and no job was checked.**',
            '',
            'This is not a finding about the jobs. It is this tool being unable to ask.',
        ], msg='CRON_SECRET is not set.')

    try:
        from sairn_http import fetch_json
    except Exception as e:
        return cannot_tell([
            '**`tools/sairn_http.py` could not be imported (%s).**' % type(e).__name__,
            '',
            'Bare `curl` is deliberately not used as a fallback: an edge challenge',
            'returns a 403 that a naive client reads as a page, which is how a check',
            'reports a success it never had.',
        ], msg=str(e))

    try:
        payload = fetch_json(url, method='POST', payload={},
                             headers={'Authorization': 'Bearer ' + secret})
    except Exception as e:
        return cannot_tell([
            '**The watchdog could not be reached or did not answer usefully.**',
            '',
            '    %s: %s' % (type(e).__name__, str(e)[:400]),
            '',
            'No job was checked. A 403 is UNREACHED, not verified-good -- and an',
            'unreachable watchdog is itself consistent with the outage it exists to',
            'report, so this is the one COULD NOT TELL worth acting on immediately.',
        ], msg='%s: %s' % (type(e).__name__, e))

    if not isinstance(payload, dict):
        return cannot_tell(['**The watchdog answered something this tool cannot read.**'],
                           msg='unreadable answer.')
    if payload.get('error'):
        code = payload['error'].get('code', 'error')
        return cannot_tell([
            '**The watchdog refused: `%s`**' % code,
            '',
            '> %s' % payload['error'].get('message', ''),
            '',
            '`NOT_PROVISIONED` means `sql/cron_heartbeat_schema.sql` has never been',
            'run, so there are no heartbeats to check and nothing is being watched.',
        ], payload, msg='the watchdog refused.')

    jobs = payload.get('jobs')
    if not isinstance(jobs, list):
        return cannot_tell(['**The watchdog answered without a job list.**'], payload,
                           msg='no job list.')

    lines = ['| Job | Status | Last run | Age (s) | Headroom (s) |', '|---|---|---|---|---|']
    for j in sorted(jobs, key=lambda x: str(x.get('job'))):
        lines.append('| `%s` | **%s** | %s | %s | %s |' % (
            j.get('job'), j.get('status'), j.get('last_run_at', '—'),
            j.get('age_seconds', '—'), j.get('seconds_until_late', '—')))
    # ── WHAT WAS DONE ABOUT IT (item 55) ───────────────────────────────────
    # Reported separately from what was FOUND, because a reader who cannot tell
    # them apart cannot tell a suppressed alert from an alert that was never
    # planned -- and UNDELIVERED is the state that matters most here: detection
    # worked and nobody was told, which is the shape a watchdog is supposed to
    # make impossible rather than produce.
    actions = payload.get('actions') or []
    undelivered = [a for a in actions if a.get('delivered') is False]
    if actions:
        lines += ['', '## Response', '',
                  '| Job | Status | Action | Delivered | Why |', '|---|---|---|---|---|']
        for a in actions:
            d = a.get('delivered')
            lines.append('| `%s` | %s | **%s** | %s | %s |' % (
                a.get('job'), a.get('status'), a.get('action'),
                '—' if d is None else ('yes' if d else '**NO**'),
                str(a.get('reason', ''))[:160]))
    if undelivered:
        lines += ['', '### A response could NOT be delivered', '',
                  '**Detection worked and nobody was told.** This is worse than a',
                  'missing watchdog, because the existence of one is an assurance',
                  'somebody is relying on.', '']
        for a in undelivered:
            lines.append('- `%s` %s **%s** — %s' % (
                a.get('job'), a.get('status'), a.get('action'),
                (a.get('detail') or {}).get('error', 'no reason given')))

    bad = [j for j in jobs if j.get('status') != 'ok'] + undelivered
    if bad:
        lines += ['', '## Not ok', '']
        for j in bad:
            lines.append('- **`%s` — %s**: %s' % (
                j.get('job'), j.get('status'),
                MEANING.get(j.get('status'), j.get('why', 'no explanation available'))))
        write_status('NOT OK', lines, payload)
        print('FINDING: %d job(s) not ok. See %s' % (len(bad), os.path.relpath(DOC, REPO)))
        return EXIT_FINDING

    if not jobs:
        # A CLEAN SWEEP OVER AN EMPTY LIST IS NOT A CLEAN SWEEP. It is what a
        # watchdog watching nothing looks like, and it is identical in shape to
        # every job being healthy.
        return cannot_tell([
            '**The watchdog checked ZERO jobs.** That is not "everything is fine" --',
            'it is what a watchdog watching nothing looks like, and the two are',
            'indistinguishable from the outside.',
        ], payload, msg='zero jobs checked.')

    write_status('OK', lines, payload)
    print('OK: %d job(s) healthy. %s updated.' % (len(jobs), os.path.relpath(DOC, REPO)))
    return EXIT_CLEAN


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
