#!/usr/bin/env python
"""new_checker.py -- scaffold a checker that CANNOT report clean until it works.

    python tools/new_checker.py <name> "<one line: what it catches>"
    python tools/new_checker.py <name> "..." --dry-run     # print, write nothing

Writes two files and nothing else:

    tools/<name>_check.py             the checker, built THROUGH checker_kit
    tests/run_<name>_probe.py         its control pair, both directions

── ITEM 28's FOLD-IN: A GENERATOR, NOT ANOTHER LIBRARY ─────────────────────
`tools/checker_kit.py` already holds the three things every checker here has had
to get right -- the three-state exit contract, comment-stripped parsing, and the
control-pair declaration. What it cannot do is make anyone USE them. A library
is available; a scaffold is what arrives already wired.

Every defect checker_kit's header lists was a checker that skipped one of the
three: `literal_drift_check.py` promoted with `verdict: by_exit` and no
`sys.exit` anywhere in it, so it could never report a finding through the
registry that ran it. `checkblocks.py` always exited 0 and nothing noticed. Nine
of ten checks in one push gate disabled behind a single `if os.path.isfile(...)`
and reporting a pass they never performed. None of those authors lacked the
library. They lacked a starting point that already had the wiring in it.

── THE ONE PROPERTY THAT MATTERS: A FRESH CHECKER REFUSES ──────────────────
The generated checker exits **2 -- COULD NOT RUN** until its author replaces the
`rule()` body. It does NOT exit 0.

That is the whole point of generating it rather than copying one. A scaffold
that starts out reporting CLEAN manufactures, on demand, the exact defect this
platform keeps finding: a check that reads as coverage and has never been able
to fire. This one starts out saying "no rule is implemented, so nothing was
judged" -- which is true, is the third state, and is impossible to mistake for a
passing run.

── AND THE FIXTURES COME FIRST ─────────────────────────────────────────────
The generated file carries a FIXTURES block and refuses to judge a real file
until every fixture classifies correctly -- convention 1 of
`docs/2026-09-13-cross-domain-disciplines.md`, wired rather than remembered. Two
fixtures are pre-written and DELIBERATELY FAIL against the unimplemented rule,
so the author's first run shows them failing and the refusal working, instead of
a green screen that proves nothing.

── WHAT IT DOES NOT DO, SAID PLAINLY ───────────────────────────────────────
It does not register the checker in `report_only_checks.REGISTRY`, add a
PURPOSES entry to `tooling_inventory.py`, or wire a push-gate check. Those are
decisions with owners and evidence behind them -- promotion is earned on a track
record, not granted by a scaffold -- and a generator that quietly wired a new
checker into a gate would be doing the one thing this repo is most careful
about. It PRINTS the next steps instead.
"""
import io
import os
import re
import sys

# AT THE TOP, BEFORE ANYTHING PRINTS. The templates below carry box-drawing
# characters, and printing them on a Windows console defaulting to cp1252 raises
# UnicodeEncodeError -- which is how `--dry-run` exited 1 on its first run while
# the real generation worked fine. Wrapping here rather than later matters:
# replacing sys.stdout mid-run abandons the old stream's buffer and silently
# discards everything printed before it, which cost three of four sections in
# tests/run_reachability_r5_probe.py earlier today.
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXIT_CLEAN, EXIT_FINDING, EXIT_COULD_NOT_RUN = 0, 1, 2

CHECKER_TEMPLATE = '''#!/usr/bin/env python
"""{name}_check.py -- {what}

    python tools/{name}_check.py                 # sweep
    python tools/{name}_check.py --fixtures      # the blind lock alone
    python tools/{name}_check.py <file>...       # scope to a file list

GENERATED by tools/new_checker.py. The wiring below is the platform's, and it is
already correct; what is missing is the RULE, and until it is written this
checker REFUSES rather than reporting clean.

── BEFORE YOU CHANGE ANYTHING, WRITE THE FIXTURES ──────────────────────────
Convention 1 of docs/2026-09-13-cross-domain-disciplines.md: a check's pass/fail
criteria are decided against synthetic fixtures BEFORE the check is run against
real data, and the tool refuses to judge anything real until those fixtures
classify correctly. A criterion chosen by looking at what produced a number is
not a check -- it is a description of the data wearing a check's clothes.

Add fixtures for the shapes you intend to catch AND for the shapes you must NOT
catch. A fixture set made only of defects locks in a checker that flags correct
files, which is how a checker gets switched off before it is ever promoted.

── THEN WRITE rule() ───────────────────────────────────────────────────────
It takes a path and the file's text and returns a list of finding strings. It
gets COMMENT-STRIPPED source by default, because grep cannot tell code from text
that describes code -- this repo's most repeated defect. Ask for the raw text
explicitly if your subject IS the comments.

── AND KEEP THE THIRD STATE ────────────────────────────────────────────────
A file you could not read is not a file with no findings. Append to
`could_not_run`, never to `findings`, and never swallow it.

Exit 0 clean, 1 finding, 2 could not run.
"""
import io
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, 'tools'))
from checker_kit import EXIT_CLEAN, EXIT_FINDING, EXIT_COULD_NOT_RUN  # noqa: E402
from checker_kit import tracked, strip_comments, finish                # noqa: E402

# ── THE BLIND LOCK ──────────────────────────────────────────────────────────
# (label, filename, source, must_flag). Judged in ISOLATION, before any real
# file is opened -- a lock that rides beside live data can be satisfied by the
# data.
#
# THE TWO BELOW ARE DELIBERATELY UNSATISFIED by the unimplemented rule, so your
# first run shows the refusal working rather than a green screen that proves
# nothing. Replace them; do not delete them.
FIXTURES = [
    ('REPLACE ME: a file that MUST be flagged', 'f.js',
     'the shape this checker exists to catch', True),
    ('REPLACE ME: a file that must NOT be flagged', 'f.js',
     'an ordinary line with nothing wrong with it', False),
]


def rule(path, src):
    """Return a list of finding strings for one file. `src` is comment-stripped.

    NOT IMPLEMENTED. Returning [] here would make this checker report CLEAN over
    the whole tree, which is why it raises instead -- see NotImplementedRule in
    main(). Delete the raise when you write the rule.
    """
    raise NotImplementedError('rule() has not been written yet')


def run_fixtures(verbose=True):
    wrong = []
    for label, name, src, must_flag in FIXTURES:
        try:
            got = bool(rule(name, src))
        except NotImplementedError:
            wrong.append('%s -- rule() is not implemented, so NOTHING was judged'
                         % label)
            continue
        if got != must_flag:
            wrong.append('%s -- expected %s, got %s'
                         % (label, 'FLAG' if must_flag else 'SILENT',
                            'FLAG' if got else 'SILENT'))
        elif verbose:
            print('  ok   %s' % label)
    return wrong


def main(argv):
    only_fixtures = '--fixtures' in argv
    args = [a for a in argv if not a.startswith('--')]

    print('BLIND LOCK -- %d fixture(s), judged before any real file is opened'
          % len(FIXTURES))
    wrong = run_fixtures(verbose=only_fixtures)
    if wrong:
        print('')
        print('REFUSING: the criteria do not classify their own fixtures.')
        for w in wrong:
            print('  x %s' % w)
        print('')
        print('NOTHING REAL WAS JUDGED. Fix the criteria, or fix a fixture whose')
        print('expected verdict was itself wrong -- and say in this file which')
        print('one you did. A fixture changed to match the tool output is how a')
        print('lock stops locking.')
        return EXIT_COULD_NOT_RUN
    print('  %d/%d fixtures correct.' % (len(FIXTURES), len(FIXTURES)))
    if only_fixtures:
        return EXIT_CLEAN

    if args:
        files, notes = [os.path.relpath(a, REPO).replace(chr(92), '/') for a in args], []
    else:
        files, notes = tracked('*.js', '*.html')

    findings, could_not_run, scanned = [], [], 0
    for f in files:
        p = os.path.join(REPO, f)
        try:
            src = io.open(p, encoding='utf-8').read()
        except Exception as e:
            # A FILE YOU COULD NOT READ IS NOT A FILE WITH NO FINDINGS.
            could_not_run.append('%s -- unreadable (%s), so it was NOT scanned'
                                 % (f, type(e).__name__))
            continue
        scanned += 1
        try:
            findings.extend(rule(f, strip_comments(src)))
        except NotImplementedError:
            could_not_run.append('%s -- rule() is not implemented' % f)

    print('')
    print('  files scanned : %d' % scanned)
    for n in notes:
        print('  not scanned   : %s' % n)
    return finish(findings, could_not_run,
                  clean_line='CLEAN -- {what}')


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
'''

PROBE_TEMPLATE = '''"""tests/run_{name}_probe.py

Run:  python tests/run_{name}_probe.py

The control pair for tools/{name}_check.py.

GENERATED by tools/new_checker.py.

A CONTROL IS ONLY A CONTROL WHEN IT ASSERTS BOTH DIRECTIONS:

    plant the defect -> the checker must REPORT it   (non-zero exit)
    plant clean code -> the checker must STAY SILENT (zero exit)

A check that always reports passes the first alone. A check that never reports
passes the second alone. Only the pair says anything -- and `checkblocks.py`
always exited 0 for months precisely because nobody had written the first half.

EVERY PLANT ASSERTS IT LANDED. When an anchor rots, str.replace silently does
nothing, the checker runs against an UNCHANGED file, and "it exited 0" is then
reported as the clean arm passing. tools/sabotage_control_check.py exists
because 21 of 37 controls on this platform had drifted into exactly that state.

NOTHING IS MUTATED IN THIS CLONE -- every plant is written to a temporary file.
"""
import io
import os
import subprocess
import sys
import tempfile

CONTROLS_FOR = ['{name}_check.py']

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOOL = os.path.join(REPO, 'tools', '{name}_check.py')
FAIL = []


def ok(name, cond, detail=''):
    print('  %s %s%s' % ('PASS ' if cond else 'FAIL ', name,
                         '' if cond else chr(10) + '        ' + str(detail)[:600]))
    if not cond:
        FAIL.append(name)


def run(*args):
    r = subprocess.run([sys.executable, TOOL] + list(args),
                       capture_output=True, text=True, cwd=REPO)
    return r.returncode, (r.stdout or '') + (r.stderr or '')


def write(tmp, name, body):
    """Write a fixture file and PROVE it landed."""
    p = os.path.join(tmp, name)
    io.open(p, 'w', encoding='utf-8', newline='').write(body)
    back = io.open(p, encoding='utf-8').read()
    if back != body:
        raise AssertionError('the fixture did not land: ' + name)
    return p


print('{name}_check -- the control pair')

# ── A. the blind lock stands on its own ────────────────────────────────────
print('')
print('--- A. the fixtures, in isolation ---')
rc, out = run('--fixtures')
ok('A1 the lock runs before any real file is opened',
   'before any real file' in out, out)
# TWO LEGITIMATE STATES AND NOTHING ELSE, which is why this arm names both.
# Before rule() is written the lock must REFUSE (2) -- a scaffold that started
# out reporting CLEAN would manufacture the exact defect this platform keeps
# finding. After it is written the lock must PASS (0) with its fixtures stated.
# Exit 1 is neither: it would mean the lock itself found a finding, which is not
# a thing --fixtures can do.
ok('A2 the lock is either REFUSING (no rule yet) or PASSING (rule written) -- never anything else',
   rc == 2 or (rc == 0 and 'fixtures correct' in out),
   'rc=%d' % rc + chr(10) + out)

# ── B. the two directions. WRITE THESE. ────────────────────────────────────
# Replace the bodies below with the real defect shape and a real clean file.
# Both arms are expected to FAIL until rule() exists, which is the point: the
# failing arm is the thing that tells you the checker is not finished.
print('')
print('--- B. plant the defect / plant clean code ---')
tmp = tempfile.mkdtemp(prefix='{name}-probe-')
bad = write(tmp, 'bad.js', 'REPLACE ME: the shape this checker exists to catch' + chr(10))
good = write(tmp, 'good.js', 'REPLACE ME: an ordinary file with nothing wrong' + chr(10))

rc_bad, out_bad = run(bad)
ok('B1 the planted defect is REPORTED', rc_bad == 1, 'rc=%d' % rc_bad + chr(10) + out_bad)
rc_good, out_good = run(good)
ok('B2 THE PAIR: clean code is left alone', rc_good == 0, 'rc=%d' % rc_good + chr(10) + out_good)

print('')
if FAIL:
    print('{name}: %d ARM(S) FAILED -- %s' % (len(FAIL), ', '.join(FAIL)))
    sys.exit(1)
print('{name}: all arms pass')
'''

NEXT_STEPS = """
WRITTEN:
  tools/{name}_check.py
  tests/run_{name}_probe.py

IT REFUSES RIGHT NOW, ON PURPOSE. Run it:

    python tools/{name}_check.py

and it exits 2 saying nothing was judged. That is the correct state for a
checker with no rule in it, and it is why this was generated rather than copied
from something that already worked.

NEXT, IN THIS ORDER -- the order is the discipline:
  1. Replace FIXTURES with the shapes you MUST catch and the shapes you must
     NOT. Include a real-world benign occurrence; a fixture set made only of
     defects locks in a checker that flags correct files.
  2. Write rule(). Delete the `raise NotImplementedError`.
  3. Fill in both arms of tests/run_{name}_probe.py and run it. An arm that
     fails is the checker telling you it is not finished.

NOT DONE BY THIS GENERATOR, and deliberately:
  * No entry in report_only_checks.REGISTRY. Promotion is earned on a track
    record, not granted by a scaffold.
  * No PURPOSES entry in tooling_inventory.py -- but note that tool REFUSES to
    generate while a tools/ file has no entry, so add one before you commit.
  * No push-gate wiring. A generator that quietly put a new checker in front of
    every push would be doing the one thing this repo is most careful about.
"""


def main(argv):
    args = [a for a in argv if not a.startswith('--')]
    dry = '--dry-run' in argv
    if len(args) < 2:
        print(__doc__.strip().split('\n\n')[0])
        print('\nusage: python tools/new_checker.py <name> "<what it catches>" [--dry-run]')
        return EXIT_COULD_NOT_RUN
    name, what = args[0], args[1]
    if not re.match(r'^[a-z][a-z0-9_]*$', name):
        print('COULD NOT RUN: <name> must be lower_snake_case -- got %r. The file '
              'names and the CONTROLS_FOR declaration are both derived from it, '
              'and a name that needs quoting breaks the second one silently.' % name)
        return EXIT_COULD_NOT_RUN

    checker = os.path.join(REPO, 'tools', '%s_check.py' % name)
    probe = os.path.join(REPO, 'tests', 'run_%s_probe.py' % name)
    # NEVER OVERWRITE. A generator that clobbers a checker somebody has already
    # written the rule into is a worse failure than one that refuses.
    existing = [p for p in (checker, probe) if os.path.exists(p)]
    if existing and not dry:
        print('REFUSING: these already exist and would be overwritten:')
        for p in existing:
            print('  %s' % os.path.relpath(p, REPO))
        print('Pick another name, or delete them deliberately first.')
        return EXIT_COULD_NOT_RUN

    body = CHECKER_TEMPLATE.format(name=name, what=what)
    probe_body = PROBE_TEMPLATE.format(name=name)
    if dry:
        print('--- tools/%s_check.py ---' % name)
        print(body)
        print('--- tests/run_%s_probe.py ---' % name)
        print(probe_body)
        return EXIT_CLEAN

    io.open(checker, 'w', encoding='utf-8', newline='').write(body)
    io.open(probe, 'w', encoding='utf-8', newline='').write(probe_body)
    print(NEXT_STEPS.format(name=name).strip())
    return EXIT_CLEAN


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
