"""nhi_register.py -- every NON-HUMAN IDENTITY, its OWNER and its SCOPE.

    python tools/nhi_register.py            # write docs/NHI-REGISTER.md
    python tools/nhi_register.py --check    # is the document still true?
    python tools/nhi_register.py --selftest

── WHY THIS IS NOT docs/SECRETS-INVENTORY.md ────────────────────────────────
That document is generated by `tools/secrets_inventory.py`, which finds
credentials by scanning code for `process.env.X` reads. It is the right tool for
what it does and this file does not replace it -- it CITES it.

**AN ENV-VAR SCAN CANNOT ANSWER "WHO OWNS EVERY LIVE CREDENTIAL", AND THE REASON
IS STRUCTURAL RATHER THAN A GAP IN ITS COVERAGE.** Three of the four identity
classes on this platform are not environment variables at all:

  * the **GitHub PAT** -- held by a human and by CI, never read from
    `process.env` anywhere in this repo;
  * **`sairn_backup_reader`** -- a Postgres LOGIN role created by
    `sql/backup_reader_role.sql`. The role is the identity; the password is a
    property of it;
  * **each clone's push access** -- four working copies with write rights to
    `origin/main`, credentialed by the Windows credential manager.

So the register is keyed on IDENTITY, not on variable name, and an env-var
credential appears here as *a credential belonging to an identity* rather than
as a row of its own.

── WHAT MAKES IT A CHECK RATHER THAN A LIST ─────────────────────────────────
A written list of owners goes stale the first time somebody adds a credential,
and nothing announces the day it stopped being complete. Two things are therefore
DERIVED from the repo on every run and diffed against the hand-written half:

  1. every `CREDENTIAL` in `secrets_inventory.SECRETS` must be attributed to an
     identity here. A new secret classified as a credential and not attributed
     makes this tool REFUSE, the same way a new tool with no `PURPOSES` entry
     makes `tooling_inventory.py` refuse;
  2. every Postgres role this repo CREATES (`create role <name>` in `sql/`) must
     appear here. Minting a login role is exactly the act most likely to happen
     without anybody recording who owns it.

`--check` answers whether the published document still matches. The hand-written
half is OWNER and SCOPE, because neither is derivable -- ownership is a decision.

── THE HONEST LIMITS, STATED HERE RATHER THAN DISCOVERED ────────────────────
  * **It cannot see an identity that exists only in a console.** A Vercel token,
    a Supabase personal access token, or a GitHub Action's OIDC identity minted
    in a web UI leaves no trace in this repo. Those are recorded here by HAND on
    somebody's word, and rows sourced that way are marked `attested`.
  * **It does not verify a credential is still live**, has been rotated, or has
    the scope claimed for it. No clone holds any of them. `last_rotated` is
    attested, never measured, and a blank means NOBODY KNOWS rather than never.
  * **It does not check least privilege.** `tools/role_gate_invariants.js` and
    the grant-sweep work own that question.
"""
import io
import json
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, 'tools'))
DOC = os.path.join('docs', 'NHI-REGISTER.md')

# ── THE HAND-WRITTEN HALF: OWNER and SCOPE. Neither is derivable. ────────────
# `credentials` lists the env-var names from secrets_inventory.SECRETS that this
# identity authenticates with, so the cross-reference in check_attribution() has
# something to match. `source`: 'repo' when the identity is visible in tracked
# files, 'attested' when it exists only because somebody says so.
IDENTITIES = [
    {
        'id': 'supabase-service-role',
        'kind': 'database role',
        'owner': 'Michael',
        'scope': 'FULL read/write on every table in the ONE Supabase project, '
                 'bypassing RLS by design. Every app server-side path acts as '
                 'this identity. 495 grant statements across sql/ name it',
        'credentials': ['SUPABASE_SERVICE_ROLE_KEY'],
        'source': 'repo',
        'rotation': 'coordinated -- every app stops working at once',
        'last_rotated': '',
        'compromise': (
            'REVOKE: Supabase dashboard, Project Settings -> API -> roll the '
            'service_role key. Then set SUPABASE_SERVICE_ROLE_KEY in Vercel '
            '(Production AND Preview) and REDEPLOY -- the running functions '
            'hold the old value until they do. BLAST WHILE COMPROMISED: read '
            'and write on every table in the one project, RLS bypassed, so '
            'every tenant of every app at once. WHAT BREAKS DURING: every '
            'server-side path on the platform, until the redeploy completes. '
            'ROTATION DOES NOT UNDO A READ -- anything already exfiltrated '
            'stays exfiltrated, and docs/2026-09-14-nightly-backup-design.md '
            'records the project on the FREE TIER with one-day log retention, '
            'so there may be no way to establish what was touched. THE HUMAN '
            'DECISION, not drafted here: whether to roll immediately and take '
            'every app down, or stage the redeploy first. DRAFTED 2026-09-15 '
            'from this register and the repo; the console steps are NOT '
            'verified because no clone has that access.'
        ),
    },
    {
        'id': 'sairn_backup_reader',
        'kind': 'database role (LOGIN)',
        'owner': 'Michael',
        'scope': 'SELECT on every table in public, plus BYPASSRLS so a dump is '
                 'complete rather than silently partial. NOLOGIN is deliberately '
                 'NOT set, because the backup job has to connect',
        'credentials': [],
        'source': 'repo',
        'rotation': 'alter role ... password. No automation',
        'last_rotated': '',
        'compromise': (
            'REVOKE: `alter role sairn_backup_reader with password ...` in '
            'the Supabase SQL editor, or `drop role` outright. '
            'sql/backup_reader_role.sql rotates unconditionally, so '
            're-running the corrected file IS the rotation. BLAST WHILE '
            'COMPROMISED: SELECT on every table in public plus BYPASSRLS -- a '
            'complete read of the platform, and no write. WHAT BREAKS DURING: '
            'the backup job only. NO APPLICATION PATH USES THIS ROLE, which '
            'makes it the one credential here that can be revoked first and '
            'reasoned about afterwards. STILL OPEN AND NOT ANSWERABLE FROM A '
            'CLONE: whether the LIVE role currently holds the placeholder or '
            'a rotated password. DRAFTED 2026-09-15.'
        ),
        # ── CORRECTED 2026-09-15, AND THE STALE VERSION WAS MINE ─────────────
        # This row shipped saying the script-level finding was UNFIXED. It is
        # not, and I verified the correction rather than accepting it: Fourth's
        # `e40e146b` added a guard that RAISES while the literal placeholder is
        # present (sql/backup_reader_role.sql:97) and an UNCONDITIONAL
        # `alter role ... with password` (:117), so a re-run of the corrected
        # file ROTATES rather than no-opping on an existing role. Independently
        # re-verified twice by the auditor (entries 58 and 108).
        #
        # Carrying "UNFIXED" forward into the document that is now meant to be
        # the reliable source is exactly the staleness this register exists to
        # remove, and it was the THIRD time that claim resurfaced.
        'warning': 'THE SCRIPT IS FIXED -- Fourth\'s e40e146b raises while the '
                   'placeholder password is present and rotates unconditionally '
                   'on an existing role, so the file can no longer mint or '
                   'preserve a published credential. WHAT IS STILL OPEN IS '
                   'NARROWER AND IS NOT RESOLVABLE FROM SOURCE: the role is '
                   'confirmed to EXIST in the live project, and whether it '
                   'currently holds the placeholder or the rotated password is '
                   'UNKNOWN. No clone has database access, so no check here can '
                   'answer it -- it needs one query by somebody who can connect. '
                   'Register entry 101. LIVE-PASSWORD-STATE UNKNOWN, not '
                   'script-unfixed',
    },
    {
        'id': 'postgres',
        'kind': 'database role',
        'owner': 'Michael',
        'scope': 'the identity every migration runs as, through the Supabase SQL '
                 'editor. Owns all 380-odd objects in public -- which is the '
                 'evidence the supabase_admin default ACL has never fired',
        'credentials': [],
        'source': 'repo',
        'rotation': 'managed by Supabase',
        'last_rotated': '',
    },
    {
        'id': 'supabase_admin',
        'kind': 'database role (platform-managed)',
        'owner': 'Supabase',
        'scope': 'NOT ours and not controllable from here. Recorded because its '
                 'DEFAULT ACL grants anon and authenticated full CRUD on tables '
                 'it creates -- a standing accepted risk with a named trigger',
        'credentials': [],
        'source': 'repo',
        'rotation': 'not ours',
        'last_rotated': '',
    },
    {
        'id': 'anon',
        'kind': 'database role (public)',
        'owner': 'Michael',
        'scope': 'the role the shipped publishable key maps to. Probed live '
                 '2026-09-05 across nine tables: every one 42501 permission '
                 'denied, confirmed independently from inside as postgres. It '
                 'holds no SELECT anywhere it matters',
        'credentials': [],
        'source': 'repo',
        'rotation': 'rotating the publishable key is customer-visible',
        'last_rotated': '',
    },
    {
        'id': 'anthropic-api',
        'kind': 'third-party API identity',
        'owner': 'Michael',
        'scope': 'billed model access for every app that calls Claude, through '
                 'api/claude.js and the three endpoints that import '
                 'callAnthropic',
        'credentials': ['ANTHROPIC_API_KEY'],
        'source': 'repo',
        'rotation': 'Anthropic console. Breaks every AI feature until redeployed',
        'last_rotated': '',
        'compromise': (
            'REVOKE: Anthropic console -> API keys -> revoke, then issue a '
            'replacement, set ANTHROPIC_API_KEY in Vercel and REDEPLOY. BLAST '
            'WHILE COMPROMISED: METERED SPEND on this account, which is a '
            'financial exposure rather than a data one -- and the model calls '
            'carry whatever the apps send, so treat prompt content as exposed '
            'too. WHAT BREAKS DURING: every AI feature in every app, until '
            'the redeploy. CHECK AFTERWARDS: console usage for the window, '
            'which is the one place on this platform where a compromise '
            'leaves an independent, billable trace. DRAFTED 2026-09-15; the '
            'console steps are NOT verified from here.'
        ),
    },
    {
        'id': 'stripe-account',
        'kind': 'third-party API identity',
        'owner': 'Michael',
        'scope': 'live charge and refund authority on the SAIRNcash Stripe '
                 'account, plus webhook-signature verification',
        'credentials': ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET'],
        'source': 'repo',
        'rotation': 'Stripe dashboard',
        'last_rotated': '',
    },
    {
        'id': 'resend',
        'kind': 'third-party API identity',
        'owner': 'Michael',
        'scope': 'outbound transactional email -- reminders and the cron '
                 'watchdog alert, which is one of only two mechanisms on this '
                 'platform that reaches a human',
        'credentials': ['RESEND_API_KEY'],
        'source': 'repo',
        'rotation': 'Resend dashboard',
        'last_rotated': '',
    },
    {
        # ADDED 2026-09-23. It was unattributed and the register REFUSED TO RUN
        # over it, which is the refusal working: this is not a spare copy of
        # the signing secret, it is a SEPARATE identity that was split out of
        # SD_AUTH_SECRET on 2026-09-17 precisely so the two stop sharing fate.
        # api/_lib/auth.js says why in its own words: a leak of the combined
        # secret "did not only forge sessions, it decrypted every secret at
        # rest".
        'id': 'secrets-at-rest',
        'kind': 'encryption key',
        'owner': 'Michael',
        'scope': 'AES-256-GCM key for secrets AT REST -- attorney MFA/TOTP '
                 'secrets (api/law-auth.js) and a stored Stedi API key '
                 '(api/sc-credentials.js, api/sc-eligibility.js). Read in one '
                 'module, api/_lib/auth.js',
        'credentials': ['SD_ENCRYPTION_KEY'],
        'source': 'repo',
        'rotation': 'ROTATABLE ONLY SINCE THE v2 FORMAT, and it is worth '
                    'stating what it was before: changing the key made every '
                    'stored ciphertext undecryptable, NOTHING ERRORED AT '
                    'DEPLOY TIME, and MFA began failing per-attorney as each '
                    'one next signed in. "Rotate the shared secret" read as '
                    'routine hygiene and was a data-loss event with a delayed '
                    'fuse. The ciphertext now carries the key it used '
                    '(legacy -> sha256(SD_AUTH_SECRET), v2 -> '
                    'sha256(SD_ENCRYPTION_KEY)), so both decrypt during a '
                    'backfill. A rotation still needs a re-encrypt pass, and '
                    'no schedule exists',
        'last_rotated': '',
        'compromise': (
            'REVOKE: there is no revoke. A leaked encryption key decrypts '
            'every ciphertext already written with it, and those ciphertexts '
            'are in Supabase whether the key changes or not. CONTAINMENT IS '
            'RE-ENCRYPTION PLUS INVALIDATION OF WHAT WAS PROTECTED, not a '
            'key change: every attorney MFA/TOTP secret must be re-enrolled '
            'and the Stedi API key rotated at Stedi. BLAST WHILE COMPROMISED: '
            'the holder can compute any attorney TOTP code, which defeats the '
            'second factor on a system holding client trust money, and can '
            'use the Stedi key for real-time payer eligibility queries. '
            'WHAT BREAKS DURING: nothing at deploy time, and that is the '
            'hazard rather than the comfort -- the v2 format means a new key '
            'is accepted silently while old values keep decrypting, so a '
            'half-finished migration looks identical to a finished one from '
            'the outside. WHAT IS NOT ESTABLISHED HERE: whether '
            'SD_ENCRYPTION_KEY is actually SET in Vercel. api/_lib/auth.js '
            'says "UNTIL SD_ENCRYPTION_KEY IS SET THIS DEPLOY CHANGES '
            'NOTHING" -- new writes stay legacy and the duty stays with '
            'SD_AUTH_SECRET. If it is unset, this identity does not yet exist '
            'in production and the SPLIT HAS NOT HAPPENED; that is a one '
            'command check (vercel env ls production) and it is NOT asserted '
            'either way from here. DRAFTED 2026-09-23. '
            'AND THE DEADLOCK THE PROCEDURE EXISTS FOR, because it is not '
            'visible from this entry: rotating the key leaves every MFA user '
            'unable to verify (500 MFA_UNAVAILABLE), unable to re-enrol '
            '(409 MFA_ALREADY_ENABLED while mfa_enabled is true), and unable '
            'to be reset (mfa_reset needs an OWNER session, and the Owner is '
            'locked out too). Every route out runs through a session the state '
            'prevents, so the SQL file is the only door -- not a shortcut '
            'around the procedure. STEP 1 IS ROTATING AT STEDI, not touching '
            'this key: that is the credential an attacker can use remotely and '
            'immediately.'
        ),
    },
    {
        'id': 'session-signing',
        'kind': 'signing key',
        'owner': 'Michael',
        'scope': 'signs and verifies EVERY app employee session token. One '
                 'secret and no per-app key, so one leak forges sessions '
                 'everywhere at once. CORRECTED 2026-09-23: it said "and no '
                 'overlap window, so a rotation logs everyone out of everything '
                 'at once" -- SD_AUTH_SECRET_PREVIOUS has been accepted on '
                 'verify since 2026-09-17, so that has not been true for six days',
        'credentials': ['SD_AUTH_SECRET', 'SD_AUTH_SECRET_PREVIOUS'],
        'source': 'repo',
        'rotation': 'overlap window, since 2026-09-17: set '
                    'SD_AUTH_SECRET_PREVIOUS to the current secret, change '
                    'SD_AUTH_SECRET, wait one SESSION_TTL_MS (12h) for every '
                    'old token to expire, then clear PREVIOUS. NO universal '
                    'logout. THE ENTRY BELOW STILL SAYS THERE IS ONE -- see '
                    'the CORRECTED paragraph in compromise',
        'last_rotated': '',
        'compromise': (
            'REVOKE: set a new SD_AUTH_SECRET in Vercel and redeploy. THE '
            'CONTAINMENT IS THE DISRUPTION, and that is why this needs '
            'deciding in advance rather than during: one secret signs EVERY '
            'app employee session and there is no overlap window, so rotating '
            'LOGS EVERYONE OUT OF EVERYTHING AT ONCE, mid-shift, including '
            'whoever is handling the incident. BLAST WHILE COMPROMISED: forge '
            'a session token for any employee of any app, including an admin '
            '-- so the exposure is IMPERSONATION, and every audit row written '
            'during the window names whoever the forger chose. WHAT BREAKS '
            'DURING: nothing stays broken; everyone signs in again. THE HUMAN '
            'DECISION, not drafted here: whether a suspected compromise is '
            'enough to rotate, given that the cost is certain and the '
            'compromise is not. AN OVERLAP WINDOW -- accept two secrets '
            'during a changeover -- would remove that dilemma and is a build, '
            'not a procedure. DRAFTED 2026-09-15. '
            '**CORRECTED 2026-09-23: THAT BUILD HAS LANDED AND THIS '
            'PARAGRAPH WAS STILL SAYING IT HAD NOT.** api/_lib/auth.js:365 '
            'accepts SD_AUTH_SECRET_PREVIOUS on verify and never signs with '
            'it, so a rotation no longer logs anyone out: set PREVIOUS to the '
            'current secret, change SD_AUTH_SECRET, wait one SESSION_TTL_MS '
            '(12h), clear PREVIOUS. The dilemma above -- certain cost against '
            'an uncertain compromise -- is GONE, and with it the reason to '
            'hesitate. Found because the register REFUSED TO RUN over '
            'SD_AUTH_SECRET_PREVIOUS being unattributed; the refusal is what '
            'surfaced a stale procedure, which is the whole argument for '
            'failing closed on a blank owner.'
        ),
    },
    {
        'id': 'cron-caller',
        'kind': 'shared-secret identity',
        'owner': 'Michael',
        'scope': 'proves a request to a scheduled endpoint came from Vercel Cron '
                 'rather than from anybody who found the URL',
        'credentials': ['CRON_SECRET'],
        'source': 'repo',
        'rotation': 'Vercel env, both Production and Preview',
        'last_rotated': '',
    },
    # ── THE ELEVEN THE CHECK FOUND ON ITS FIRST RUN ─────────────────────────
    # Every one of these was already classified CREDENTIAL by secrets_inventory
    # and belonged to NO identity here, which is precisely the gap this register
    # exists to close -- eleven live credentials with no recorded owner, found
    # mechanically rather than by remembering. Each scope below is taken from
    # secrets_inventory's own description of what the variable unlocks; the OWNER
    # is the decision and it is Michael in every case, because there is one
    # person.
    {
        'id': 'oidc-client',
        'kind': 'third-party API identity',
        'owner': 'Michael',
        'scope': 'the platform\'s OIDC client. The only one of the four OIDC '
                 'values whose exposure is a security event rather than a '
                 'misconfiguration',
        'credentials': ['OIDC_CLIENT_SECRET'],
        'source': 'repo',
        'rotation': 'the OIDC provider\'s console',
        'last_rotated': '',
    },
    {
        'id': 'quickbooks-oauth',
        'kind': 'third-party API identity',
        'owner': 'Michael',
        'scope': 'QuickBooks OAuth client. NOTE that StoneDesk GAP 6 records '
                 'QuickBooks integration as deliberately HELD OPEN, so this '
                 'credential may be provisioned for work nobody is doing',
        'credentials': ['QB_CLIENT_SECRET'],
        'source': 'repo',
        'rotation': 'Intuit developer console',
        'last_rotated': '',
    },
    {
        'id': 'courtlistener',
        'kind': 'third-party API identity',
        'owner': 'Michael',
        'scope': 'CourtListener API access for the SAIRNlaw citator',
        'credentials': ['COURTLISTENER_API_TOKEN'],
        'source': 'repo',
        'rotation': 'CourtListener account',
        'last_rotated': '',
    },
    {
        'id': 'stability-ai',
        'kind': 'third-party API identity',
        'owner': 'Michael',
        'scope': 'billed image generation for StoneDesk rendering. A second '
                 'metered AI vendor beyond Anthropic, and the only one',
        'credentials': ['STABILITY_API_KEY'],
        'source': 'repo',
        'rotation': 'Stability account',
        'last_rotated': '',
    },
    {
        'id': 'sairncash-firebase-admin',
        'kind': 'third-party service account',
        'owner': 'Michael',
        'scope': 'FULL Firebase admin authority for SAIRNcash. The most '
                 'consequential credential on the consumer side, and distinct '
                 'from the Firebase WEB values, which are public by design',
        'credentials': ['SAIRNCASH_FIREBASE_SERVICE_ACCOUNT'],
        'source': 'repo',
        'rotation': 'Google Cloud IAM -- a JSON key, not a string',
        'last_rotated': '',
        'compromise': (
            'REVOKE: Google Cloud IAM -> the service account -> delete the '
            'KEY (not the account), mint a replacement, set '
            'SAIRNCASH_FIREBASE_SERVICE_ACCOUNT in Vercel and REDEPLOY. It is '
            'a JSON blob, not a string, so a partial paste fails closed '
            'rather than half-working. BLAST WHILE COMPROMISED: full Firebase '
            'admin on SAIRNcash -- consumer accounts and their data, read and '
            'write, and the ability to mint credentials. This is the consumer '
            'side, so the affected parties are members of the public rather '
            'than a business customer. WHAT BREAKS DURING: SAIRNcash '
            'server-side paths, until the redeploy. NOTE it is DISTINCT from '
            'the Firebase WEB values, which are public by design -- leaking '
            'those is not this event. DRAFTED 2026-09-15; the IAM steps are '
            'NOT verified from here.'
        ),
    },
    {
        'id': 'sairncash-stripe-webhook',
        'kind': 'shared-secret identity',
        'owner': 'Michael',
        'scope': 'verifies SAIRNcash webhook signatures. RECORDED SEPARATELY '
                 'FROM stripe-account ON PURPOSE: secrets_inventory already '
                 'flags the near-collision with STRIPE_WEBHOOK_SECRET, two '
                 'variables one word apart, and folding them into one identity '
                 'here would re-create exactly that confusion',
        'credentials': ['SAIRNCASH_STRIPE_WEBHOOK_SECRET'],
        'source': 'repo',
        'rotation': 'Stripe dashboard, the SAIRNcash endpoint',
        'last_rotated': '',
    },
    {
        'id': 'sairncash-admin',
        'kind': 'shared-secret identity',
        'owner': 'Michael',
        'scope': 'lets a caller RENEW A SAIRNCASH TRIAL WITHOUT PAYING. A '
                 'bypass of the paywall, held as a bearer string',
        'credentials': ['SAIRNCASH_ADMIN_SECRET'],
        'source': 'repo',
        'rotation': 'Vercel env, both Production and Preview',
        'last_rotated': '',
    },
    {
        'id': 'alf-pharmacy',
        'kind': 'third-party integration identity',
        'owner': 'Michael',
        'scope': 'authenticates the pharmacy integration into the SAIRNcare '
                 'eMAR -- a medication-administration record, so a PHI-adjacent '
                 'path',
        'credentials': ['ALF_PHARMACY_SECRET'],
        'source': 'repo',
        'rotation': 'with the pharmacy vendor',
        'last_rotated': '',
    },
    {
        'id': 'dental-bi-export',
        'kind': 'shared-secret identity',
        'owner': 'Michael',
        'scope': 'the SAIRNdental BI export key -- authorises a bulk data pull '
                 'out of a PHI-bearing app',
        'credentials': ['DENTAL_BI_KEY'],
        'source': 'repo',
        'rotation': 'Vercel env',
        'last_rotated': '',
    },
    {
        'id': 'rate-limit-salts',
        'kind': 'hashing salt (two variables, one purpose)',
        'owner': 'Michael',
        'scope': 'salts the hashed identifiers the dental and StoneDesk PUBLIC '
                 'rate limiters key on. Leaking one makes the stored hashes '
                 'reversible, so these protect the anonymity of the identifiers '
                 'rather than access to anything. Two variables under one '
                 'identity because they are the same decision twice',
        'credentials': ['DENTAL_RATE_LIMIT_SALT', 'STONEDESK_RATE_LIMIT_SALT'],
        'source': 'repo',
        'rotation': 'rotating INVALIDATES every stored hash and resets the '
                    'limiter\'s memory -- a behaviour change, not just a swap',
        'last_rotated': '',
    },
    {
        'id': 'github-pat',
        'kind': 'VCS token',
        'owner': 'Michael',
        'scope': 'push to SAIRN1/SAIRN, and read of a PUBLIC repository. ATTESTED '
                 'ONLY -- it appears nowhere in tracked files by design, so this '
                 'row cannot be derived and cannot be verified from here',
        'credentials': [],
        'source': 'attested',
        'rotation': 'GitHub settings. No automation, no expiry recorded here',
        'last_rotated': '',
    },
    {
        'id': 'clone-push-access',
        'kind': 'VCS credential (per working copy)',
        'owner': 'Michael',
        # DERIVED at render time by clone_scope(). The literal below is never
        # published -- it is here so the key exists and so a reader who greps
        # for the row finds the reason rather than a blank.
        'scope_derived': 'clones',
        'scope': '(derived from disk -- see clone_scope())',
        'credentials': [],
        'source': 'attested',
        'rotation': 'per-clone, in the credential manager. A Windows credential-'
                    'manager collision between two GitHub accounts has already '
                    'caused a push to report success while landing nothing',
        'last_rotated': '',
    },
]


class CouldNotTell(Exception):
    pass


# ── THE CLONE ROW IS DERIVED NOW, AND THE REASON IS THAT IT WAS WRONG ──────
# (2026-09-17.) `clone-push-access` said "FOUR working copies -- SAIRN-hank,
# SAIRN-cc, SAIRN-cody, SAIRN-fourth". There are FIVE. `Documents\SAIRN-hover`
# is a clone of the same remote with the same push credential, and it was
# missing from the identity that exists to say who can push.
#
# THAT IS THE SECOND TIME THIS EXACT UNDERCOUNT HAS HAPPENED HERE. CLAUDE.md
# records the first: the clone registry said "Four clones" and named four for
# WEEKS after a fifth existed and was pushing commits, corrected 2026-09-16 when
# a tool discovered five. A hand-written list claiming to match a population
# nothing compares it to is the defect shape this whole register was built
# against -- and it was sitting inside the register.
#
# So the population is READ FROM DISK rather than typed. Sibling directories of
# this repo named SAIRN-*, kept when they are git clones of the SAME origin.
#
# IT FAILS CLOSED. If the enumeration cannot run -- no readable parent, no git,
# no origin on this repo -- it raises rather than falling back to a list, because
# a register that quietly reverts to the hardcoded four would report exactly the
# defect it was changed to fix, and nothing downstream could tell.
#
# READ-ONLY, AND THE BOUNDARY IS DELIBERATE. One of the five is the hover
# auditor's clone, which a build agent must not reach into. This reads ONE
# value, `remote.origin.url`, and writes nothing anywhere; NOT counting that
# clone is the defect, so leaving it out is not the safe option.
def sibling_clones():
    import subprocess
    # ── encoding= IS PINNED, AND I INTRODUCED THIS DEFECT MYSELF (2026-09-17)
    # `text=True` decodes with the LOCALE DEFAULT, which is cp1252 on this
    # platform. cc recorded the same one-line fail-open in tier_a_review_gate.py
    # on 2026-09-15 -- its reader thread raised UnicodeDecodeError on this repo's
    # box-drawing characters and the call returned TRUNCATED stdout rather than
    # failing, so a diff-reading gate silently got a short diff and under-
    # detected. I wrote these two calls the day AFTER that was recorded, and
    # found them while reviewing the record that asks whether any other tool has
    # the same shape. tools/subprocess_decode_check.py is the sweep.
    #
    # A remote URL is ASCII in practice, so this one would not have bitten --
    # which is exactly why it is worth pinning rather than reasoning about: the
    # defect is invisible until the bytes happen to be non-ASCII.
    try:
        mine = subprocess.run(
            ['git', '-C', REPO, 'config', '--get', 'remote.origin.url'],
            capture_output=True, text=True, encoding='utf-8', errors='replace',
            timeout=20).stdout.strip()
    except Exception as e:
        raise CouldNotTell('could not read this clone\'s own origin (%s), so '
                           'no sibling can be compared to it' % e)
    if not mine:
        raise CouldNotTell('this working copy has no remote.origin.url, so '
                           '"a clone of the same remote" has nothing to mean')
    parent = os.path.dirname(REPO)
    try:
        entries = sorted(os.listdir(parent))
    except OSError as e:
        raise CouldNotTell('could not list %s (%s)' % (parent, e))
    found = []
    for name in entries:
        if not name.startswith('SAIRN-'):
            continue
        path = os.path.join(parent, name)
        if not os.path.isdir(os.path.join(path, '.git')):
            continue
        try:
            url = subprocess.run(
                ['git', '-C', path, 'config', '--get', 'remote.origin.url'],
                capture_output=True, text=True, encoding='utf-8',
                errors='replace', timeout=20).stdout.strip()
        except Exception:
            continue
        if url == mine:
            found.append(name)
    if not found:
        raise CouldNotTell(
            'no sibling clone of %s was found beside %s -- this clone should '
            'have found ITSELF at minimum, so the enumeration is broken rather '
            'than the answer being zero' % (mine, parent))
    return found


def clone_scope():
    names = sibling_clones()
    return ('%d working copies -- %s -- each a clone of the same remote and '
            'each able to push to origin/main, credentialed by the Windows '
            'credential manager rather than by anything in this repo. An agent '
            'session acts as this identity whenever it pushes, so every commit '
            'on main was made by it. **COUNTED FROM DISK, not listed here** -- '
            'this row said FOUR and named four while a fifth was pushing, which '
            'is the second time that undercount has happened on this platform. '
            'Note that the clones are NOT interchangeable: one of them is the '
            'hover auditor, which does not build'
            % (len(names), ', '.join(names)))


def declared_credentials():
    out = {}
    for ident in IDENTITIES:
        for c in ident.get('credentials') or []:
            out.setdefault(c, []).append(ident['id'])
    return out


def env_credentials():
    """Every CREDENTIAL-kind variable secrets_inventory already classifies."""
    try:
        import secrets_inventory
    except Exception as e:                                   # noqa: BLE001
        raise CouldNotTell('could not import secrets_inventory: %r' % e)
    secrets = getattr(secrets_inventory, 'SECRETS', None)
    if not isinstance(secrets, dict) or not secrets:
        raise CouldNotTell('secrets_inventory.SECRETS is missing or empty')
    return sorted(k for k, v in secrets.items()
                  if isinstance(v, (list, tuple)) and v and v[0] == 'CREDENTIAL')


def created_roles():
    """Every Postgres role this repo CREATES. Minting a login role is the act
    most likely to happen with nobody recording who owns it."""
    ls = subprocess.run(['git', '-C', REPO, 'ls-files', 'sql/*.sql'],
                        capture_output=True, encoding='utf-8', errors='replace')
    if ls.returncode != 0:
        raise CouldNotTell('git ls-files failed, so no SQL file was read')
    found = set()
    pat = re.compile(r'create\s+role\s+([A-Za-z_][\w]*)', re.I)
    for rel in [f for f in ls.stdout.split('\n') if f]:
        try:
            txt = io.open(os.path.join(REPO, rel), encoding='utf-8',
                          errors='replace').read()
        except OSError:
            continue
        for m in pat.finditer(txt):
            found.add(m.group(1).lower())
    return sorted(found)


def gaps():
    """(unattributed_credentials, unregistered_roles). Either one refuses."""
    declared = declared_credentials()
    unattributed = [c for c in env_credentials() if c not in declared]
    ids = set(i['id'].lower() for i in IDENTITIES)
    unregistered = [r for r in created_roles() if r not in ids]
    return unattributed, unregistered


def render():
    unattributed, unregistered = gaps()
    if unattributed or unregistered:
        raise CouldNotTell(
            'the hand-written half does not cover the repo:\n'
            + ''.join('  UNATTRIBUTED CREDENTIAL  %s -- classified CREDENTIAL by '
                      'secrets_inventory and belonging to no identity here\n' % c
                      for c in unattributed)
            + ''.join('  UNREGISTERED ROLE        %s -- `create role` in sql/ and '
                      'no entry here\n' % r for r in unregistered))
    L = []
    L.append('# Non-human identity register -- owner and scope, per identity')
    L.append('')
    L.append('**GENERATED by `python tools/nhi_register.py`. Do not hand-edit.** '
             'OWNER and SCOPE live in `IDENTITIES` inside that tool, which '
             '**REFUSES to run** when a credential `secrets_inventory` calls a '
             'CREDENTIAL belongs to no identity here, or when `sql/` creates a '
             'role this file does not know. Run `--check` to find out whether '
             'this page still matches the repo.')
    L.append('')
    L.append('## Why an identity register and not a list of secrets')
    L.append('')
    L.append('`docs/SECRETS-INVENTORY.md` answers *what does this variable '
             'unlock*. It cannot answer *who owns every live credential*, '
             'because it finds credentials by scanning for `process.env.X` and '
             'three of the four identity classes here are not environment '
             'variables at all -- a VCS token, a Postgres LOGIN role, and the '
             'working copies credentialed by the Windows credential manager. '
             'This register is keyed on the IDENTITY; an env var appears as a '
             'credential *belonging to* one.')
    L.append('')
    L.append('**The `clone-push-access` row is COUNTED FROM DISK, not typed.** '
             'It read *"FOUR working copies"* and named four until 2026-09-17, '
             'while a fifth clone of the same remote held the same push '
             'credential -- the second time that undercount has happened here. '
             'The enumeration FAILS CLOSED: if it cannot run, this document '
             'refuses to generate rather than reverting to a list.')
    L.append('')
    L.append('**A blank `last rotated` means NOBODY KNOWS, not never.** No clone '
             'holds any of these, so rotation dates are attested and none has '
             'been attested yet.')
    L.append('')
    L.append('| identity | kind | owner | scope | credentials | source |')
    L.append('|---|---|---|---|---|---|')
    for i in IDENTITIES:
        creds = ', '.join('`%s`' % c for c in (i.get('credentials') or [])) or '&mdash;'
        scope = clone_scope() if i.get('scope_derived') == 'clones' else i['scope']
        L.append('| **%s** | %s | **%s** | %s | %s | %s |'
                 % (i['id'], i['kind'], i['owner'], scope, creds, i['source']))
    L.append('')
    warned = [i for i in IDENTITIES if i.get('warning')]
    if warned:
        L.append('## Open warnings carried on an identity')
        L.append('')
        for i in warned:
            L.append('- **%s** -- %s' % (i['id'], i['warning']))
        L.append('')
    # ── COMPROMISE PROCEDURES (2026-09-15) ──────────────────────────────────
    # tools/rotation_blast_radius.py measured 0 of 22 identities recording what
    # to do if that credential leaks. Every one had a ROTATION procedure -- how
    # to change it -- and not one said what to do when it is known to be in
    # somebody else's hands, which is a different question asked under time
    # pressure.
    #
    # DRAFTED, NOT VERIFIED, and the distinction is on every one of them: the
    # blast radius and what-breaks halves are derived from this register and the
    # repo; the console steps are not verified, because no clone holds any of
    # these credentials or that console access.
    procs = [i for i in IDENTITIES if (i.get('compromise') or '').strip()]
    if procs:
        L.append('## If one of these is compromised')
        L.append('')
        L.append('**%d of %d identities carry a drafted procedure.** Written '
                 '2026-09-15 for the identities holding BROAD standing access '
                 'with no attested rotation and no schedule -- the set where '
                 'neither of the other two controls is doing anything.'
                 % (len(procs), len(IDENTITIES)))
        L.append('')
        L.append('**A procedure is a THIRD control and does not fix either of '
                 'the first two.** It tells you what to do AFTER. It does not '
                 'shorten the window a leaked credential works, and it does not '
                 'narrow what that credential reaches.')
        L.append('')
        L.append('**DRAFTED, NOT REHEARSED, AND NOT VERIFIED.** The blast-radius '
                 'and what-breaks halves are derived from this register and the '
                 'repo. **The console steps are not verified** -- no clone holds '
                 'these credentials or that access, so nobody here has done any '
                 'of this. A runbook nobody has walked through is a draft, and '
                 'calling it anything else is the claim-versus-reality failure '
                 'this platform keeps recording.')
        L.append('')
        for i in procs:
            L.append('### %s' % i['id'])
            L.append('')
            L.append(i['compromise'])
            L.append('')
    L.append('## What this register cannot tell you')
    L.append('')
    L.append('- **Whether a credential is still live, or has ever been '
             'rotated.** No clone holds one. Every rotation column is attested, '
             'never measured.')
    L.append('- **Identities that exist only in a console.** A Vercel token or a '
             'Supabase personal access token minted in a web UI leaves no trace '
             'in this repo. Rows marked `attested` are here on somebody\'s word '
             'and cannot be derived.')
    L.append('- **Whether any of this is least privilege.** That is the '
             'grant-sweep and role-gate work, not this document.')
    L.append('')
    L.append('## Derived counts')
    L.append('')
    L.append('```')
    L.append('  identities registered        %3d' % len(IDENTITIES))
    L.append('  attributed CREDENTIAL vars   %3d   secrets_inventory.SECRETS'
             % len(env_credentials()))
    L.append('  postgres roles created here  %3d   `create role` in sql/'
             % len(created_roles()))
    L.append('  attested, not derivable      %3d'
             % len([i for i in IDENTITIES if i['source'] == 'attested']))
    L.append('```')
    L.append('')
    return '\n'.join(L)


def _selftest():
    ok = True

    def check(name, cond, detail=''):
        nonlocal ok
        print(('  ok   ' if cond else '  FAIL ') + name + ('' if cond else '  ' + str(detail)))
        if not cond:
            ok = False

    print('1. the refusal fires in both directions')
    saved = list(IDENTITIES)
    try:
        # Drop the identity owning ANTHROPIC_API_KEY and the register must refuse.
        IDENTITIES[:] = [i for i in saved if i['id'] != 'anthropic-api']
        try:
            render()
            check('an unattributed CREDENTIAL refuses', False, 'it rendered')
        except CouldNotTell as e:
            check('an unattributed CREDENTIAL refuses', 'ANTHROPIC_API_KEY' in str(e))
        # Drop the backup reader and the created-role check must refuse.
        IDENTITIES[:] = [i for i in saved if i['id'] != 'sairn_backup_reader']
        try:
            render()
            check('a `create role` with no entry refuses', False, 'it rendered')
        except CouldNotTell as e:
            check('a `create role` with no entry refuses',
                  'sairn_backup_reader' in str(e))
    finally:
        IDENTITIES[:] = saved

    print('\n2. CONTROL: the real register renders')
    try:
        body = render()
        check('it renders with the real IDENTITIES', 'identity | kind | owner' in body)
        check('...and every identity appears',
              all(i['id'] in body for i in IDENTITIES))
    except CouldNotTell as e:
        check('it renders with the real IDENTITIES', False, e)

    print('\n3. the derived halves really read the repo')
    try:
        check('secrets_inventory yields CREDENTIALs', len(env_credentials()) >= 10,
              len(env_credentials()))
        check('sql/ yields at least the backup reader',
              'sairn_backup_reader' in created_roles(), created_roles())
    except CouldNotTell as e:
        check('the derived halves read', False, e)

    # ── 3b. THE CLONE COUNT IS MEASURED, AND THE MEASUREMENT IS DRIVEN ──────
    # Added 2026-09-17 with the derivation itself. An arm that only asserted
    # "clone_scope() returns a string" would pass on a function that had
    # silently reverted to a hardcoded list, which is the exact failure this
    # replaced -- so the arms below check that it FINDS THIS CLONE, that it
    # finds MORE THAN THE FOUR the old row named, and that it REFUSES rather
    # than guessing when it cannot read.
    print('\n3b. the clone population is counted from disk and fails closed')
    try:
        names = sibling_clones()
        me = os.path.basename(REPO)
        check('the enumeration finds THIS clone -- if it cannot find the one it '
              'is running in, nothing it says about the others is worth reading',
              me in names, (me, names))
        check('it finds the FIFTH clone the typed list was missing',
              len(names) >= 5, names)
        body_scope = clone_scope()
        check('...and the published scope names the count it actually measured',
              str(len(names)) + ' working copies' in body_scope, body_scope[:80])
        check('the old hardcoded four is not in the output',
              'FOUR working copies' not in body_scope)
    except CouldNotTell as e:
        check('the clone enumeration ran', False, e)

    # THE FAIL-CLOSED HALF, DRIVEN. A check that depends on another tool must
    # fail CLOSED when that tool is absent (PR 1.11), and the only way to know
    # this one does is to take the tool away.
    try:
        real = globals()['REPO']
        globals()['REPO'] = os.path.join(real, '__no_such_clone__')
        raised = False
        try:
            sibling_clones()
        except CouldNotTell:
            raised = True
        except Exception:
            raised = False
        check('with an unreadable repo root it RAISES rather than returning a '
              'list -- a quiet revert to the typed four is the defect itself',
              raised)
    finally:
        globals()['REPO'] = real

    print('\n4. a blank rotation date is NOT rendered as "never"')
    try:
        body = render()
        check('no row claims a rotation nobody attested',
              'never rotated' not in body.lower())
        check('...and the document says a blank means NOBODY KNOWS',
              'NOBODY KNOWS, not never' in body)
    except CouldNotTell as e:
        # Guarded, because the first version called render() bare here and the
        # selftest CRASHED instead of reporting when the real register was
        # incomplete -- a selftest that dies on a real finding is a selftest
        # nobody can use to fix the finding.
        check('no row claims a rotation nobody attested', False, e)

    print('')
    print('  all arms pass' if ok else '  ARMS FAILED')
    return 0 if ok else 2


def main(argv):
    if '--selftest' in argv:
        return _selftest()
    try:
        body = render()
    except CouldNotTell as e:
        print('REFUSING: %s' % e)
        print('A blank owner is exactly how the last inventory went stale, so '
              'this is an error rather than an empty cell.')
        return 2
    path = os.path.join(REPO, DOC)
    if '--check' in argv:
        try:
            cur = io.open(path, encoding='utf-8', newline='').read()
        except OSError:
            print('FAIL: %s does not exist. Run the generator.' % DOC)
            return 1
        if cur.replace('\r\n', '\n') == body.replace('\r\n', '\n'):
            print('OK: %s matches the repo.' % DOC)
            return 0
        print('FAIL: %s no longer matches -- an identity, a credential or a '
              'created role has changed. Regenerate:' % DOC)
        print('    python tools/nhi_register.py')
        return 1
    if '--json' in argv:
        print(json.dumps(IDENTITIES, indent=1))
        return 0
    io.open(path, 'w', encoding='utf-8', newline='\n').write(body)
    print('wrote %s (%d identities)' % (DOC, len(IDENTITIES)))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
