#!/usr/bin/env python
"""Generate the SAIRNlaw load-state gate from the seed files.

WHAT THIS SOLVES
----------------
A rule is corrected in a seed, the commit lands, and a live licence keeps
serving the old value indefinitely. That happened: LAW-PINNACLE-2026 computed
federal answer deadlines three days late for a day after the fix was pushed,
and it was found by accident during an unrelated audit.

Nothing could detect it. Every rule carries a `version` field and all 270
SAIRNlaw seed rules are `version: 1` -- including the two the fix changed. A
stale live row and a corrected seed row are byte-distinguishable but not
version-distinguishable.

WHAT THIS GENERATES
-------------------
A read-only SQL gate that compares every live rule against the seed it should
have come from, and names every row that disagrees. It is generated FROM the
seeds so it cannot drift from them: re-run this script after any seed change and
the gate updates itself.

TWO DESIGN DECISIONS WORTH KNOWING
----------------------------------
1. SUBTRACTIVE, NOT ADDITIVE field selection. The gate compares
   `rule minus {metadata keys}` rather than `rule restricted to {compute keys}`.
   A hand-picked compute list is a list that goes stale silently -- a new
   date-affecting field would simply not be compared, and the gate would report
   clean while missing it. Subtracting known-inert keys means anything new is
   included by default. This is the same reasoning that made the platform
   provenance audit discover its tables instead of listing them.

   It also means the gate is deliberately NOISIER than the hand-picked version:
   it will flag a `designated_period` or `cap` difference that the earlier
   ad-hoc query ignored entirely. That is the point.

2. jsonb-to-jsonb comparison, not hashes. Computing a matching md5 across
   Python and Postgres means agreeing on key order and whitespace, and a
   mismatch there produces a false alarm that looks exactly like a real one.
   Postgres compares jsonb canonically, so the gate hands it two jsonb values
   and lets it decide.

WHAT IT STILL CANNOT DO
-----------------------
Tell you a reload RAN. It reports what a licence holds versus what the seeds
say. That is the question that matters, but it is not the same question.
"""
import glob
import io
import json
import os
import sys

# Keys that describe or cite a rule but cannot change a computed date.
# Everything NOT listed here is treated as compute-relevant and compared.
# `verified_by` is included defensively: it does not appear in any seed file but
# was reported as a source of noise in live rows, so it is presumably stamped at
# load time.
INERT_KEYS = {
    'rule_id', 'label', 'authority', 'computation',
    'version', 'supersedes', 'verified_by', 'verified_on', 'source_url',
}

SEED_GLOB = 'sql/sairnlaw_deadline_seed_*.json'


def compute_subset(rule):
    """The part of a rule that can move a date. Subtractive by design."""
    return {k: v for k, v in rule.items() if k not in INERT_KEYS}


def collect(seed_glob=SEED_GLOB):
    rules, dupes = {}, []
    for path in sorted(glob.glob(seed_glob)):
        with io.open(path, encoding='utf-8') as fh:
            doc = json.load(fh)
        for rule in doc.get('rules', []):
            rid = rule.get('rule_id')
            if not rid:
                raise SystemExit('rule with no rule_id in %s' % path)
            if rid in rules:
                dupes.append((rid, rules[rid]['file'], os.path.basename(path)))
                continue
            rules[rid] = {
                'file': os.path.basename(path),
                'jurisdiction': rule.get('jurisdiction'),
                'version': rule.get('version'),
                'compute': compute_subset(rule),
            }
    return rules, dupes


def sql_literal(text):
    return "'" + text.replace("'", "''") + "'"


def build_sql(rules, dupes):
    out = []
    w = out.append
    w('-- sql/sairnlaw_load_gate_generated.sql')
    w('-- GENERATED by tools/sairnlaw_build_load_gate.py -- DO NOT HAND-EDIT.')
    w('-- Re-run that script after any seed change; this file is derived, not authored.')
    w('-- READ-ONLY: no insert, update, delete, grant, revoke, alter, drop, truncate.')
    w('--')
    w('-- Compares every live law_deadline_rules row against the seed it should have')
    w('-- come from. A row appearing in the output is a licence serving something the')
    w('-- seeds do not say -- which is the defect that computed federal deadlines three')
    w('-- days late on LAW-PINNACLE-2026 and was found only by accident.')
    w('--')
    w('-- The comparison is SUBTRACTIVE: rule minus known-inert keys (%s).'
      % ', '.join(sorted(INERT_KEYS)))
    w('-- Anything else is compared, so a date-affecting field added later is covered')
    w('-- by default instead of being silently skipped by a stale hand-picked list.')
    w('--')
    w('-- ⚠ `version` IS REPORTED BUT CANNOT BE TRUSTED AS A SIGNAL TODAY: all %d seed'
      % len(rules))
    w('--   rules are version 1, including the two that a correction changed. It is')
    w('--   shown so the day someone starts bumping it, the drift becomes visible here')
    w('--   without editing this file. Until then the jsonb comparison is the real test.')
    w('')
    w('with expected(rule_id, jurisdiction, seed_file, seed_version, compute) as (values')
    rows = []
    for rid in sorted(rules):
        r = rules[rid]
        rows.append('  (%s, %s, %s, %s, %s::jsonb)' % (
            sql_literal(rid),
            sql_literal(r['jurisdiction'] or ''),
            sql_literal(r['file']),
            'null' if r['version'] is None else str(int(r['version'])),
            sql_literal(json.dumps(r['compute'], sort_keys=True, ensure_ascii=False)),
        ))
    w(',\n'.join(rows))
    w('),')
    w('licences as (')
    w("  select k.key, k.app_id, encode(digest(k.key,'sha256'),'hex') as h")
    w("  from public.license_keys k where k.app_id = 'sairnlaw'")
    w('),')
    w('live as (')
    w('  select l.key as licence, r.entry_id, r.data,')
    w('         (r.data - %s) as compute' % ' - '.join(sql_literal(k) for k in sorted(INERT_KEYS)))
    w('  from licences l')
    w('  join public.law_deadline_rules r on r.license_hash = l.h')
    w('),')
    w('-- EVERY (licence, seed rule) PAIR, not every seed rule. Joining expected')
    w('-- straight to live on rule_id alone cannot see "missing from licence A while')
    w('-- present on licence B" -- the expected row finds B, matches, and A\'s absence')
    w('-- never appears. Enumerating the pairs first is what makes MISSING detectable')
    w('-- per licence, which is the whole point of a load-state gate.')
    w('wanted as (')
    w('  select l.key as licence, x.rule_id, x.jurisdiction, x.seed_file,')
    w('         x.seed_version, x.compute')
    w('  from licences l cross join expected x')
    w(')')
    w('select')
    w('  coalesce(w.licence, v.licence)               as licence,')
    w('  coalesce(w.rule_id, v.entry_id)              as rule_id,')
    w('  w.seed_file,')
    w('  case')
    w("    when v.entry_id is null then 'MISSING -- seed rule never loaded onto this licence'")
    w("    when w.rule_id  is null then 'ORPHAN -- live row with no seed; content of unknown origin'")
    w("    else 'STALE -- live content differs from the seed'")
    w('  end                                          as verdict,')
    w('  w.seed_version,')
    w("  v.data ->> 'version'                         as live_version,")
    w('  jsonb_pretty(w.compute)                      as seed_compute,')
    w('  jsonb_pretty(v.compute)                      as live_compute')
    w('from wanted w')
    w('full outer join live v')
    w('  on v.licence = w.licence and v.entry_id = w.rule_id')
    w('where v.entry_id is null')
    w('   or w.rule_id  is null')
    w('   or v.compute is distinct from w.compute')
    w('order by 4, 1, 2;')
    if dupes:
        w('')
        w('-- ⚠ DUPLICATE rule_ids across seed files, first occurrence kept:')
        for rid, first, second in dupes:
            w('--   %s: %s and %s' % (rid, first, second))
    return '\n'.join(out) + '\n'


def main():
    rules, dupes = collect()
    if not rules:
        raise SystemExit('no seed rules found -- run from the repo root')
    sql = build_sql(rules, dupes)
    dest = 'sql/sairnlaw_load_gate_generated.sql'
    with io.open(dest, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(sql)
    with_ext = sum(1 for r in rules.values() if 'service_extension' in r['compute'])
    versions = sorted({r['version'] for r in rules.values()})
    print('rules            : %d' % len(rules))
    print('jurisdictions    : %d' % len({r['jurisdiction'] for r in rules.values()}))
    print('with extension   : %d' % with_ext)
    print('distinct versions: %s%s' % (
        versions, '   <-- uninformative while this is a single value' if len(versions) == 1 else ''))
    print('duplicate ids    : %d' % len(dupes))
    print('written          : %s (%d bytes)' % (dest, os.path.getsize(dest)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
