"""Resolve a rebase conflict by FILE CLASS, and refuse on the class it must not touch.

    python tools/sairn_rebase_resolve.py          # classify and resolve what is safe
    python tools/sairn_rebase_resolve.py --dry    # say what it would do, change nothing

Exit 0  every conflicted file was a GENERATED document and is resolved and staged
       (or there was nothing conflicted)
Exit 1  at least one conflicted file is SOURCE -- a human has to read it
Exit 2  COULD NOT TELL -- never folded into either of the other two

── WHY THIS EXISTS, AND IT IS A REAL INCIDENT AND NOT A HYPOTHETICAL ──────────
On 2026-09-15 I pushed `api/_lib/dnt-rollup.js` to origin/main containing literal
`<<<<<<< HEAD` markers. The module did not parse, so every suite loading
api/sd-data.js through it went red on main -- including tests/sairncode_gates.js,
the suite guarding seven Tier A medical-billing records.

The cause was a push loop that resolved every conflict the same way:

    git checkout --theirs $U && regenerate && git add $U && rebase --continue

THAT IS CORRECT FOR A GENERATED DOCUMENT. `docs/MASTER-PLAN.md` conflicts
constantly because four clones regenerate it, and the resolution genuinely is
"take either side, then regenerate from the repo, which is the authority
anyway". It ran six times and was right six times.

IT IS CATASTROPHIC ON A SOURCE FILE. `--theirs` during a rebase does not mean
what it reads like, the file came back with markers intact, and `git add` staged
them because nothing looked. The rule that was broken is already written down --
"before deleting or overwriting, look at the target" -- and it was automated
past precisely because the loop had worked.

A RESOLUTION STRATEGY THAT IS RIGHT FOR ONE FILE CLASS AND WRONG FOR ANOTHER
MUST NOT BE APPLIED BY A LOOP THAT CANNOT TELL THEM APART. So this tool tells
them apart, and refuses rather than guessing.

── HOW THE CLASS IS DECIDED: THE FILE DECLARES ITSELF ─────────────────────────
A file is GENERATED when it SAYS SO, in its own first lines, and NAMES the
generator that produced it:

    **GENERATED by `python tools/master_plan.py`. Do not hand-edit ...**

Three documents carry that today. The list is NOT hardcoded here, and that is
deliberate: a hand-kept list of generated files is the pinned-list-drift defect
this platform has now been bitten by three times. The declaration is read from
the file, the named generator is checked to EXIST, and a file that declares a
generator this repo does not have is COULD NOT TELL -- never "source", because
guessing in that direction re-creates the incident, and never "generated",
because running a script named in a conflicted file is worse.

── AND THE BACKSTOP, WHICH IS THE PART THAT ACTUALLY SAVES YOU ────────────────
Classification can be wrong. So NOTHING is staged before every file about to be
staged is scanned for conflict markers, and a marker anywhere refuses the whole
run. That check does not depend on the classification being right, which is the
only reason it is worth having: the incident would have been caught by it even
with the class decided wrongly.
"""
import io
import os
import re
import subprocess
import sys

REPO = subprocess.run(['git', 'rev-parse', '--show-toplevel'],
                      capture_output=True, text=True).stdout.strip()

# The self-declaration. Read from the file, never from a list kept here.
DECLARES = re.compile(
    r'\*\*GENERATED by\s+`python\s+(tools/[A-Za-z0-9_./-]+\.py)`', re.I)

# A conflict marker, anchored at the start of a line so prose ABOUT markers --
# this file's own docstring, for instance -- is not mistaken for one.
MARKER = re.compile(r'^(?:<{7}|={7}|>{7})(?:\s|$)', re.M)

# How far into a file the declaration must appear. A generated document says so
# at the top; a mention halfway down is somebody discussing generation.
DECLARE_WINDOW = 4000


def fail(msg):
    print('COULD NOT TELL: ' + msg)
    print('Nothing was staged. This is exit 2, and it is not a pass.')
    sys.exit(2)


def conflicted():
    r = subprocess.run(['git', '-C', REPO, 'diff', '--name-only',
                        '--diff-filter=U'], capture_output=True, text=True)
    if r.returncode != 0:
        fail('git diff --diff-filter=U failed: ' + (r.stderr or '')[:200])
    return [p for p in r.stdout.split('\n') if p.strip()]


def read(rel):
    try:
        return io.open(os.path.join(REPO, rel), encoding='utf-8',
                       errors='replace').read()
    except OSError as e:                                        # noqa: BLE001
        fail('could not read %s: %s' % (rel, e))


def classify(rel):
    """('generated', generator) | ('source', why) | raises via fail()."""
    body = read(rel)
    m = DECLARES.search(body[:DECLARE_WINDOW])
    if not m:
        return ('source', 'no GENERATED-by declaration in its first %d bytes'
                % DECLARE_WINDOW)
    gen = m.group(1)
    if not os.path.isfile(os.path.join(REPO, gen)):
        fail('%s declares it is generated by %s, and that file does not exist '
             'in this repo. Refusing: treating it as source would re-create the '
             'incident, and running a generator named inside a CONFLICTED file '
             'is worse.' % (rel, gen))
    return ('generated', gen)


def main(argv):
    dry = '--dry' in argv
    files = conflicted()
    if not files:
        print('No conflicted files. Nothing to do.')
        return 0

    print('CONFLICTED FILES: %d\n' % len(files))
    gen_files, src_files = [], []
    for rel in files:
        kind, why = classify(rel)
        if kind == 'generated':
            gen_files.append((rel, why))
            print('  GENERATED  %-44s by %s' % (rel, why))
        else:
            src_files.append((rel, why))
            print('  SOURCE     %-44s %s' % (rel, why))
    print('')

    # ── THE REFUSAL COMES BEFORE ANY WORK ──────────────────────────────────
    # Not after the generated half is staged: a partial resolution is a state
    # somebody finishes by hand under time pressure, which is the same failure
    # wearing a different hat.
    if src_files:
        print('REFUSED: %d conflicted SOURCE file(s). A human has to read these.'
              % len(src_files))
        for rel, _why in src_files:
            print('    ' + rel)
        print('')
        print('This is the file class that put conflict markers on origin/main')
        print('on 2026-09-15. `--theirs` does not mean what it reads like during')
        print('a rebase, and `git add` will stage markers without complaining.')
        print('Resolve them by reading both sides, then re-run this.')
        return 1

    if dry:
        print('--dry: would regenerate and stage %d document(s). Nothing changed.'
              % len(gen_files))
        return 0

    # ── REGENERATE FROM THE REPO, WHICH IS THE AUTHORITY ───────────────────
    # `--theirs` is not used even here. The point of a generated document is
    # that neither side of the conflict is the source of truth; the repo is.
    for rel, gen in gen_files:
        r = subprocess.run([sys.executable, os.path.join(REPO, gen)],
                           cwd=REPO, capture_output=True, text=True,
                           encoding='utf-8', errors='replace')
        if r.returncode != 0:
            print('%s exited %d -- refusing to stage %s'
                  % (gen, r.returncode, rel))
            print(((r.stdout or '') + (r.stderr or ''))[-600:])
            return 2
        print('  regenerated %s  (%s)' % (rel, gen))

    # ── THE BACKSTOP, AND IT DOES NOT TRUST THE CLASSIFICATION ─────────────
    left = []
    for rel, _gen in gen_files:
        if MARKER.search(read(rel)):
            left.append(rel)
    if left:
        print('')
        print('REFUSED: conflict markers are STILL PRESENT after regeneration:')
        for rel in left:
            print('    ' + rel)
        print('Nothing was staged. A generator that leaves markers behind did')
        print('not regenerate the file, whatever its exit code said.')
        return 2

    add = subprocess.run(['git', '-C', REPO, 'add'] + [r for r, _g in gen_files],
                         capture_output=True, text=True)
    if add.returncode != 0:
        fail('git add failed: ' + (add.stderr or '')[:200])
    print('\nStaged %d regenerated document(s). Run `git rebase --continue`.'
          % len(gen_files))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
