#!/usr/bin/env python
"""shape_antipattern_check.py -- primitive obsession, boolean blindness and optional-property proliferation -- the three shapes behind the Number('') bug, the truthy-coercion sum and the UTC calendar-date bugs

    python tools/shape_antipattern_check.py                 # sweep
    python tools/shape_antipattern_check.py --fixtures      # the blind lock alone
    python tools/shape_antipattern_check.py <file>...       # scope to a file list

GENERATED by tools/new_checker.py. The wiring below is the platform's, and it is
already correct; what is missing is the RULE, and until it is written this
checker REFUSES rather than reporting clean.

── BEFORE YOU CHANGE ANYTHING, WRITE THE FIXTURES ──────────────────────────
Convention 1 of docs/2026-09-13-cross-domain-disciplines.md: a check's pass/fail
criteria are decided against synthetic fixtures BEFORE the check is run against
real data, and the tool refuses to judge anything real until those fixtures
classify correctly. A criterion chosen by looking at what produced a number is
not a check -- it is a description of the data wearing a check's clothes.

Add fixtures for the shapes you intend to catch AND for the shapes you must NOT
catch. A fixture set made only of defects locks in a checker that flags correct
files, which is how a checker gets switched off before it is ever promoted.

── THEN WRITE rule() ───────────────────────────────────────────────────────
It takes a path and the file's text and returns a list of finding strings. It
gets COMMENT-STRIPPED source by default, because grep cannot tell code from text
that describes code -- this repo's most repeated defect. Ask for the raw text
explicitly if your subject IS the comments.

── AND KEEP THE THIRD STATE ────────────────────────────────────────────────
A file you could not read is not a file with no findings. Append to
`could_not_run`, never to `findings`, and never swallow it.

Exit 0 clean, 1 finding, 2 could not run.
"""
import io
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, 'tools'))
from checker_kit import EXIT_CLEAN, EXIT_FINDING, EXIT_COULD_NOT_RUN  # noqa: E402
from checker_kit import tracked, strip_comments, finish                # noqa: E402

# ── THE BLIND LOCK ──────────────────────────────────────────────────────────
# (label, filename, source, must_flag). Judged in ISOLATION, before any real
# file is opened -- a lock that rides beside live data can be satisfied by the
# data.
#
# THE TWO BELOW ARE DELIBERATELY UNSATISFIED by the unimplemented rule, so your
# first run shows the refusal working rather than a green screen that proves
# nothing. Replace them; do not delete them.
# -- THE THREE SHAPES, EACH NARROWED TO A DECIDABLE SIGNATURE ----------------
# "Primitive obsession" and "boolean blindness" are design judgements, not
# greps. A checker that tried to detect the CONCEPTS would report a design
# opinion on most of the platform and be switched off inside a day -- this
# repo's own recorded fate for a first draft that over-reports.
#
# So each shape is narrowed to THE SIGNATURE THE REAL BUG ACTUALLY HAD, and the
# fixtures are built from those bugs rather than from the textbook:
#
#   S1 PRIMITIVE OBSESSION -> Number(x) on a value that came from outside, with
#      no range or finiteness check near it. api/greeting.js shipped
#      Number(client_hour); a query string sends '' and Number('') is 0, so an
#      ABSENT hour silently became MIDNIGHT. The fix was parseInt PLUS a range
#      check -- and the fix is the signature.
#
#   S2 BOOLEAN BLINDNESS -> a guard named is/has/can/should that returns a BARE
#      true/false literal. The platform's own worked counter-example is
#      api/sv-witness.js's requireWitness(), which returns a REFUSAL OBJECT or
#      null and says in its header why: a boolean invites `if (!ok) { log(); }`,
#      and this has to be the thing that stops the write rather than a fact
#      about it.
#      NOT the `(x || 0)` fold: tools/truthy_sum_check.py owns that one, and a
#      second detector for it would be the duplication the Guardian skill says
#      to resolve on discovery. That bug CALIBRATES this shape; it is not
#      re-detected here.
#
#   S3 OPTIONAL-PROPERTY PROLIFERATION -> three or more properties assigned null
#      in the same branch. That is one either/or state spelled as N nullable
#      fields, and every consumer then has to re-derive which state it is in.
#      api/_lib/wip-accounting.js's summariseDraw() nulls retainage_pct,
#      retainage_held and net_requested together -- three fields carrying one
#      fact: no retainage percentage was recorded.
#
# EVERY SHAPE CARRIES A BENIGN FIXTURE. A set made only of defects locks in a
# checker that flags correct files, which is how one gets switched off before it
# is ever promoted.
FIXTURES = [
    ('S1: Number() on an outside value with no range check', 'f.js',
     'const hour = Number(req.query.client_hour);\nreturn hour;', True),
    ('S1: parseInt WITH a range check is the FIX, not a finding', 'f.js',
     'const hour = parseInt(req.query.client_hour, 10);\n'
     'if (!isFinite(hour) || hour < 0 || hour > 23) return null;', False),
    ('S1: Number() on a literal is nobody bug', 'f.js',
     'const n = Number(3);', False),
    ('S1: Number() guarded by isFinite on the next line is fine', 'f.js',
     'const n = Number(body.qty);\nif (!isFinite(n)) return null;', False),
    # ── A FIXTURE CORRECTED, AND WHICH KIND IS SAID OUT LOUD ────────────────
    # Convention 1 allows a fixture whose EXPECTED VERDICT was simply wrong to
    # change, and forbids changing one to match what the tool output. THIS IS
    # THE FIRST KIND. It originally read `if (!u) return false; return true;`
    # and expected FLAG -- but measuring the real tree established that a guard
    # with ONE failure reason is a pure predicate and must NOT be flagged, and
    # that fixture was byte-identical in shape to the benign one two lines down.
    # It was asserting two opposite verdicts for the same shape. Rewritten to a
    # guard with TWO DISTINCT REASONS, which is the shape the criterion is
    # actually about; the expected verdict did not move.
    ('S2: a guard collapsing TWO distinct failure reasons into one bit', 'f.js',
     'function isAllowed(u, role) {\n'
     '  if (!u) return false;\n'
     '  if (!role) return false;\n'
     '  return true;\n}', True),
    ('S2: the same guard returning a refusal object is the fix', 'f.js',
     'function isAllowed(u) {\n  if (!u) return { code: "NO_USER" };\n  return null;\n}', False),
    ('S2: a non-guard name returning a boolean is not this shape', 'f.js',
     'function compare(a, b) {\n  return true;\n}', False),
    # ADDED AFTER THE FIRST REAL MEASUREMENT flagged isWeekend() and
    # isMinorPatient(). A pure predicate is one question and one bit, which is
    # what a boolean is FOR. The fixture is kept so the narrowing cannot be
    # undone by accident.
    ('S2: A PURE PREDICATE IS NOT THIS SHAPE -- one reason, one bit', 'f.js',
     'function isWeekend(d) {\n  if (!d) return false;\n  return true;\n}', False),
    ('S3: three nulls in one branch', 'f.js',
     'if (pct === null) {\n  out.a = null;\n  out.b = null;\n  out.c = null;\n}', True),
    ('S3: two is not a proliferation', 'f.js',
     'if (pct === null) {\n  out.a = null;\n  out.b = null;\n}', False),
]

NUM_CALL = re.compile(r"\bNumber\(\s*([A-Za-z_$][\w$.\[\]'\"]*)\s*\)")
GUARD_FN = re.compile(r'function\s+(is|has|can|should)([A-Z]\w*)\s*\([^)]*\)\s*\{')
NULL_ASSIGN = re.compile(r'^\s*[\w$.\[\]]+\s*=\s*null\s*;', re.M)
OUTSIDE = re.compile(r'\b(req|body|query|params|payload|localStorage|row|input)\b'
                     r'|\.value\b|getItem')
# `|| 0` AND `?? 0` ARE REAL GUARDS HERE AND WERE MISSING FROM THE FIRST DRAFT.
# Measured, not reasoned about: `Number('') || 0` is 0 and `Number('abc') || 0`
# is 0, because NaN is falsy -- so the fold that breaks truthy_sum_check's case
# is the thing that RESCUES this one. api/_lib/ai-rate-limit.js's
# `Number(body.prior_count) || 0` was reported and is correct code.
#
# Worth keeping straight, because the two look identical and are opposites:
# `x || 0` on a RAW STRING is the truthy-coercion bug (a non-empty string is
# truthy, so "500" survives and concatenates). `Number(x) || 0` has already
# coerced, so the guard sees a number or NaN and does exactly what it looks
# like. Same three characters, different position, different verdict.
GUARD_NEAR = re.compile(r'isFinite|isNaN|parseInt|[<>]=?\s*\d'
                        r'|\?\?|\|\|\s*[\d\-]|==\s*null|!=\s*null'
                        # AN EMPTINESS CHECK IS A GUARD, and this was the second
                        # correction the real tree forced. sairnlaw.html rejects
                        # the field two lines above with
                        # `!String(dd.value).trim()` before calling Number() --
                        # which closes the empty-string-becomes-zero path
                        # completely, just not with a numeric test. The bug this
                        # shape is about is Number('') === 0; anything that
                        # proves the value is non-empty has already stopped it.
                        r'|\.trim\(\)|\.length|!==?\s*[\'"]{2}')


def _guarded(src, at, before=80, after=160):
    return bool(GUARD_NEAR.search(src[max(0, at - before):at + after]))


def rule(path, src):
    out = []
    nl = chr(10)

    for m in NUM_CALL.finditer(src):
        arg = m.group(1)
        # A LITERAL OR A LOCAL ARITHMETIC VALUE IS NOT THE BUG. The shape is a
        # value that crossed a boundary AS TEXT -- a request, a stored string, a
        # parsed payload, a DOM field.
        if not OUTSIDE.search(arg):
            continue
        if _guarded(src, m.start()):
            continue
        out.append('%s:%d S1 PRIMITIVE OBSESSION -- Number(%s) on a value from '
                   'outside with no range or finiteness check near it. '
                   "Number('') is 0, so an ABSENT field becomes a real number "
                   'and every downstream check passes on it.'
                   % (path, src.count(nl, 0, m.start()) + 1, arg))

    for m in GUARD_FN.finditer(src):
        name = m.group(1) + m.group(2)
        body = src[m.end():m.end() + 600]
        cut = re.search(r'\n(?:function|const|var|let|module\.exports)\b', body)
        if cut:
            body = body[:cut.start()]
        # NARROWED AFTER MEASURING IT, and the first draft was wrong in the loud
        # direction: it flagged isWeekend() and isMinorPatient(). Those are PURE
        # PREDICATES -- one question, one bit -- which is exactly what a boolean
        # is for and the opposite of a finding. The shape only bites when
        # SEVERAL DISTINCT REASONS are collapsed into one bit, because then the
        # caller cannot act on which, and that is precisely why
        # api/sv-witness.js's requireWitness() returns a refusal object instead.
        # Two or more separate `return false` paths; one is a predicate.
        if (len(re.findall(r'\breturn\s+false\s*;', body)) >= 2
                and re.search(r'\breturn\s+true\s*;', body)):
            out.append('%s:%d S2 BOOLEAN BLINDNESS -- %s() collapses several '
                       'distinct failure reasons into one bit. The answer '
                       'carries no evidence of WHAT was '
                       'checked, so a caller can only write `if (!ok) { log(); }`. '
                       'api/sv-witness.js returns a refusal object or null for '
                       'exactly this reason.'
                       % (path, src.count(nl, 0, m.start()) + 1, name))

    for bm in re.finditer(r'\{([^{}]*)\}', src):
        n = len(NULL_ASSIGN.findall(bm.group(1)))
        if n >= 3:
            out.append('%s:%d S3 OPTIONAL-PROPERTY PROLIFERATION -- %d '
                       'properties set to null in one branch. That is ONE '
                       'either/or state spelled as %d nullable fields, and every '
                       'consumer has to re-derive which state it is in.'
                       % (path, src.count(nl, 0, bm.start()) + 1, n, n))
    return out


def run_fixtures(verbose=True):
    wrong = []
    for label, name, src, must_flag in FIXTURES:
        try:
            got = bool(rule(name, src))
        except NotImplementedError:
            wrong.append('%s -- rule() is not implemented, so NOTHING was judged'
                         % label)
            continue
        if got != must_flag:
            wrong.append('%s -- expected %s, got %s'
                         % (label, 'FLAG' if must_flag else 'SILENT',
                            'FLAG' if got else 'SILENT'))
        elif verbose:
            print('  ok   %s' % label)
    return wrong


def main(argv):
    only_fixtures = '--fixtures' in argv
    args = [a for a in argv if not a.startswith('--')]

    print('BLIND LOCK -- %d fixture(s), judged before any real file is opened'
          % len(FIXTURES))
    wrong = run_fixtures(verbose=only_fixtures)
    if wrong:
        print('')
        print('REFUSING: the criteria do not classify their own fixtures.')
        for w in wrong:
            print('  x %s' % w)
        print('')
        print('NOTHING REAL WAS JUDGED. Fix the criteria, or fix a fixture whose')
        print('expected verdict was itself wrong -- and say in this file which')
        print('one you did. A fixture changed to match the tool output is how a')
        print('lock stops locking.')
        return EXIT_COULD_NOT_RUN
    print('  %d/%d fixtures correct.' % (len(FIXTURES), len(FIXTURES)))
    if only_fixtures:
        return EXIT_CLEAN

    if args:
        files, notes = [os.path.relpath(a, REPO).replace(chr(92), '/') for a in args], []
    else:
        files, notes = tracked('*.js', '*.html')

    findings, could_not_run, scanned = [], [], 0
    for f in files:
        p = os.path.join(REPO, f)
        try:
            src = io.open(p, encoding='utf-8').read()
        except Exception as e:
            # A FILE YOU COULD NOT READ IS NOT A FILE WITH NO FINDINGS.
            could_not_run.append('%s -- unreadable (%s), so it was NOT scanned'
                                 % (f, type(e).__name__))
            continue
        scanned += 1
        try:
            findings.extend(rule(f, strip_comments(src)))
        except NotImplementedError:
            could_not_run.append('%s -- rule() is not implemented' % f)

    print('')
    print('  files scanned : %d' % scanned)
    for n in notes:
        print('  not scanned   : %s' % n)
    return finish(findings, could_not_run,
                  clean_line='CLEAN -- primitive obsession, boolean blindness and optional-property proliferation -- the three shapes behind the Number('') bug, the truthy-coercion sum and the UTC calendar-date bugs')


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
