-- sql/dnt_cred_rules_load_gate_generated.sql
-- GENERATED by tools/sairn_build_load_gates.py -- DO NOT HAND-EDIT.
-- Re-run that script after any seed change; this file is derived, not authored.
-- READ-ONLY: no insert, update, delete, grant, revoke, alter, drop, truncate.
--
-- Compares every live dnt_cred_rules row against the seed it should have come
-- from. A row in the output is a licence serving something the seeds do not say.
--
-- BOTH SIDES ARE SUBTRACTIVE. This table keeps compute content in PROMOTED
-- COLUMNS, not only in `data`, so comparing the blob alone would miss a wrong
-- value in one of them. to_jsonb(row) names no columns, so a column added
-- later is compared by default instead of being skipped by a stale list.
-- Bookkeeping columns subtracted: id, license_hash, app_id, created_at, updated_at, verified_by, rule_id.
--
-- The expected side mirrors the server's write-path normalisation, read from
-- api/sd-data.js rather than assumed: `state` uppercased, `status` defaulted to
-- 'active'. Without that the gate reports false STALE on every row whose seed
-- omits status, and a gate that cries wolf on its first run gets switched off.

with expected(rule_id, seed_file, compute) as (values
  ('OH-BLS-HYGIENIST', 'sairndental_credentials_seed_ohio.json', '{"data": {"accepted_issuers": ["American Red Cross", "American Heart Association", "American Safety and Health Institute (if determined equivalent by the board)"], "authority": {"citation": "ORC 4715.251", "quote": "shall ... be currently certified to perform basic life-support procedures by having successfully completed a basic life-support training course certified by the American red cross, the American heart association, or, if determined equivalent by the board, the American safety and health institute", "read_on": "2026-08-24", "url": "https://codes.ohio.gov/ohio-revised-code/section-4715.251"}, "credential": "Basic Life Support (BLS/CPR)", "label": "Ohio — dental hygienists must hold current basic life-support certification at each renewal", "notes": ["Scoped to HYGIENISTS as the statute reads. Whether Ohio imposes the same standing requirement on dentists was NOT confirmed in this pass -- see unverified_notes. Do not extend this rule to dentists by inference.", "The certification itself carries its own expiry from its issuer; that date is entered per provider as a ''certification'' record."]}, "effective_from": "1995-01-01", "effective_to": null, "requirement_type": "certification", "role": "hygienist", "state": "OH", "status": "active"}'::jsonb),
  ('OH-CE-DENTIST-BIENNIAL', 'sairndental_credentials_seed_ohio.json', '{"data": {"authority": {"citation": "ORC 4715.141(A)", "quote": "Each licensed dentist shall complete biennially not less than thirty hours of continuing dental education", "read_on": "2026-08-24", "url": "https://codes.ohio.gov/ohio-revised-code/section-4715.141"}, "cycle_months": 24, "hours_required": 30, "label": "Ohio — dentists: 30 hours of continuing dental education, biennially", "notes": ["The statute states the hours and the biennial period. It does NOT fix a calendar date for the cycle; the cycle is tied to the licensee''s own registration period (see ORC 4715.24(A)), which is why each provider''s cycle_start/cycle_end is entered per provider rather than computed here.", "Record retention: OAC 4715-8-04 requires an applicant to keep documentation of CE taken for at least four years after the activity. This app stores the hours; it is not a substitute for keeping the certificates."]}, "effective_from": "1995-01-01", "effective_to": null, "requirement_type": "continuing_education", "role": "dentist", "state": "OH", "status": "active"}'::jsonb),
  ('OH-CE-HYGIENIST-BIENNIAL', 'sairndental_credentials_seed_ohio.json', '{"data": {"authority": {"citation": "ORC 4715.25(A)", "quote": "in the two-year period preceding the registration period for which renewal is sought the registrant completed a minimum of twenty hours of continuing dental hygiene education", "read_on": "2026-08-24", "url": "https://codes.ohio.gov/ohio-revised-code/section-4715.25"}, "cycle_months": 24, "hours_required": 20, "label": "Ohio — dental hygienists: 20 hours of continuing dental hygiene education per two-year period", "notes": ["Twenty, not thirty. The dentist figure and the hygienist figure are different statutes and different numbers; the engine refuses to substitute one for the other (NO_RULE_FOR_ROLE) rather than defaulting.", "The statute measures the hours over ''the two-year period preceding the registration period for which renewal is sought'' -- i.e. the hours are earned BEFORE the period being renewed into."]}, "effective_from": "1995-01-01", "effective_to": null, "requirement_type": "continuing_education", "role": "hygienist", "state": "OH", "status": "active"}'::jsonb),
  ('OH-LICENSE-TERM-ANNIVERSARY', 'sairndental_credentials_seed_ohio.json', '{"data": {"authority": {"citation": "ORC 4715.24(A)", "quote": "A license expires on the date that is two years from the date of issuance and may be registered for additional two-year periods", "read_on": "2026-08-24", "url": "https://codes.ohio.gov/ohio-revised-code/section-4715.24"}, "expiry_basis": "per_licensee_anniversary", "label": "Ohio — a licence runs two years from ITS OWN issuance date, not a statewide calendar date", "notes": ["This rule exists to record that expiry is NOT derivable from the state. It carries no date to compute from, deliberately.", "Two widely-published secondary claims (''December 31 of odd-numbered years'' and ''of even-numbered years'') contradict each other and the statute. Neither is encoded."], "term_months": 24}, "effective_from": "1995-01-01", "effective_to": null, "requirement_type": "license_term", "role": null, "state": "OH", "status": "active"}'::jsonb),
  ('US-DEA-MATE-8-HOUR', 'sairndental_credentials_seed_ohio.json', '{"data": {"authority": {"citation": "Consolidated Appropriations Act 2023 §1263(a) (MATE Act), per DEA Diversion Control MATE Act FAQ", "quote": "at least 8 hours of training … a one-time attestation … All DEA-registered practitioners, with the exception of practitioners that are solely veterinarians", "read_on": "2026-08-24", "url": "https://www.deadiversion.usdoj.gov/faq/MATE_Act_faq.html"}, "hours_required": 8, "label": "MATE Act — 8 hours of training on opioid/substance use disorder, one-time attestation", "notes": ["A ONE-TIME attestation, not a recurring or expiring requirement. It is tracked as a boolean plus the date attested, alongside the DEA registration, and never as an expiry row -- showing it as ''expiring'' would be wrong.", "Applies to all DEA-registered practitioners except those who are solely veterinarians, which includes every DEA-registered dentist.", "Attestation is made by checking a box on the online DEA registration form at the next submission, initial or renewal. This app records that it was done; it does not make the attestation."], "one_time": true}, "effective_from": "2023-06-27", "effective_to": null, "requirement_type": "dea_training", "role": null, "state": "US", "status": "active"}'::jsonb),
  ('US-DEA-TERM-36-MONTHS', 'sairndental_credentials_seed_ohio.json', '{"data": {"authority": {"citation": "21 CFR 1301.13", "quote": "the registration shall expire 36 months from the initial expiration date … Any person who is registered may apply to be reregistered not more than 60 days before the expiration date of his/her registration", "read_on": "2026-08-24", "url": "https://www.law.cornell.edu/cfr/text/21/1301.13"}, "label": "DEA practitioner registration runs 36 months; renewal may be filed no earlier than 60 days before expiry", "notes": ["The 60-day figure is the source of this feature''s DEA-specific alert threshold. It is the first day a renewal can actually be FILED, so warning earlier would prompt an action the government will not yet accept.", "Federal, so it applies regardless of which state the practice is licensed in -- this is the one rule here that is not Ohio-specific."], "renewal_window_days": 60, "term_months": 36}, "effective_from": "2006-12-01", "effective_to": null, "requirement_type": "dea_term", "role": null, "state": "US", "status": "active"}'::jsonb)
),
licences as (
  select k.key, encode(digest(k.key,'sha256'),'hex') as h
  from public.license_keys k where k.app_id = 'sairndental'
),
live as (
  select l.key as licence, r.rule_id as rule_id,
         (to_jsonb(r) - 'id' - 'license_hash' - 'app_id' - 'created_at' - 'updated_at' - 'verified_by' - 'rule_id') as compute
  from licences l
  join public.dnt_cred_rules r on r.license_hash = l.h
),
-- every (licence, seed rule) PAIR. Joining expected straight to live on
-- rule_id alone cannot see "missing from licence A while present on licence B".
wanted as (
  select l.key as licence, x.rule_id, x.seed_file, x.compute
  from licences l cross join expected x
)
select
  coalesce(w.licence, v.licence)   as licence,
  coalesce(w.rule_id, v.rule_id)   as rule_id,
  w.seed_file,
  case
    when v.rule_id is null then 'MISSING -- seed rule never loaded onto this licence'
    when w.rule_id is null then 'ORPHAN -- live row with no seed; origin unknown'
    else 'STALE -- live content differs from the seed'
  end                              as verdict,
  jsonb_pretty(w.compute)          as seed_compute,
  jsonb_pretty(v.compute)          as live_compute
from wanted w
full outer join live v on v.licence = w.licence and v.rule_id = w.rule_id
where v.rule_id is null or w.rule_id is null
   or v.compute is distinct from w.compute
order by 4, 1, 2;
