-- sql/full_crud_truncate_sweep_2026-08-24.sql
-- DIAGNOSTIC + DRAFT FIX ONLY. Nothing in this file has been run.
--
-- ── FULL EXPORT RECEIVED, 227 TABLES -- FINDINGS BEFORE SECTION 2 RUNS ────
-- Michael's SQL client had a row limit; the first export (100 rows) was
-- confirmed truncated by cross-checking against tables already known to
-- exist (SAIRNlegacy alone continues well past where that export stopped).
-- The real export surfaced two separate classes of finding, checked
-- against the actual codebase rather than assumed:
--
-- (1) ~20 tables show ZERO select/insert/update/delete for service_role
-- (only TRUNCATE/REFERENCES/TRIGGER/MAINTAIN) -- Section 2's keep_privs
-- would be NULL for every one, stripping them to zero grants entirely.
-- Checked each against every real dispatch mechanism in api/sd-data.js
-- (literal table-name calls, the generic resource===tablename pattern
-- SD_LINEAGE uses, and the full RESOURCES/action registry) -- CONFIRMED
-- unreferenced by any live SAIRN code path: conversations, customers
-- (bare -- the real 'customers' RESOURCE maps to scp_customers, a
-- different physical table, already covered), demo_calls, gl_entries,
-- intake_submissions, invoices (bare -- real resource maps to
-- scp_invoices), jobs (bare -- real resource maps to grd_jobs), licenses
-- (distinct from license_keys, see below), messages, parts, payments,
-- profiles, projects, shop_users, shops, slabs (bare -- real resource
-- maps to sd_slabs), subscriptions, usage_logs, user_storage.
-- Two of these were ALREADY flagged once before, not newly found here:
-- sql/network_schema.sql's own header records that webhook_events and
-- demo_calls surfaced via PostgREST's "perhaps you meant" hint while
-- probing for an unrelated table, explicitly states neither was assumed
-- to be SAIRN's, and recommended "a human check in the Supabase
-- dashboard" that was never followed up. That caution stands: unused by
-- this codebase is not the same as safe to touch with certainty, since a
-- table on the same Supabase project outside this repo's visibility
-- can't be ruled out. In practice the risk is low regardless -- Section 2
-- never touches SELECT/INSERT/UPDATE/DELETE, and these already have none
-- for service_role, so nothing with real read/write access today loses
-- any -- but the dashboard check is still the honest way to close this,
-- not a formality.
--
-- (2) network_insights is a DIFFERENT, more urgent case, wrongly grouped
-- with the above at first glance: it IS real and IS used
-- (api/network.js), confirmed by its own real schema file
-- (sql/network_schema.sql) -- but that file has NO grant statement of any
-- kind. service_role has held only the TRUNCATE/REFERENCES/TRIGGER/
-- MAINTAIN default baseline since the table was created, meaning
-- api/network.js has never been able to actually select or insert on it.
-- This is a live, currently-broken, previously-unnoticed bug -- the same
-- class as the StoneDesk fe730e2 incident -- not something Section 2
-- should touch. Section 2 would leave it at zero access, unchanged,
-- because it has nothing to preserve; the real fix is a normal
-- `grant select, insert on network_insights to service_role`, tracked
-- separately, not folded into this sweep.
--
-- (3) license_keys deserves its own caution, not blanket trust: it has NO
-- tracked CREATE TABLE anywhere in this repo. api/_lib/license.js's own
-- header already documents this -- the real table is "owned by a
-- separate, not-yet-built generation system" -- and
-- sql/demo_license_keys_seed.sql works around it with WHERE NOT EXISTS
-- specifically because no committed schema means no constraint to check.
-- It is almost certainly fine (every license check on the platform
-- depends on it working today), but with no file to cross-reference its
-- expected grants against, Section 2's correctness here can't be verified
-- the way it can for tables with a real schema file. Recommend excluding
-- it from an initial run and confirming it by hand afterward, given how
-- much depends on it.
--
-- (4) ai_memories, bridge_data, sairn_agents, sairn_agent_commands also
-- have NO tracked CREATE TABLE anywhere in this repo, but ARE real and
-- used (api/sd-data.js, api/_lib/sd-store.js, api/bridge.js respectively)
-- and are NOT in the zero-CRUD list, meaning service_role already has
-- real access to them today -- most likely created via Supabase's Table
-- Editor UI, which (per .claude/skills/sairn-infra-debugger/SKILL.md)
-- auto-grants correctly unlike raw SQL migrations. Section 2 is safe for
-- these the same way it is for every table with a real schema file: it
-- reads and re-asserts whatever they already have, so having no file to
-- check against doesn't create the same risk (1) and (3) do, since their
-- CURRENT grants (not an absent expectation) are what gets preserved.
-- Still worth a follow-up to write real schema files for all four so a
-- future session isn't left guessing again.
--
-- The broader sweep deliberately deferred while closing the append-only
-- gap tonight (sql/append_only_grant_audit.sql), logged as a named
-- follow-up in docs/SAIRN-OPEN-WORK-INDEX.md. Same root cause, confirmed
-- there and not re-litigated here: Postgres's default ACL for schema
-- public grants service_role TRUNCATE/REFERENCES/TRIGGER/MAINTAIN on
-- every table `postgres` creates, and a plain GRANT can only add
-- privileges, never strip that baseline. The source-level fix (ALTER
-- DEFAULT PRIVILEGES ... REVOKE ...) already applied tonight means every
-- table created FROM NOW ON is clean -- this file is only about the
-- ~150 tables that already existed before that fix ran.
--
-- ── SCALE, MEASURED NOT GUESSED ──────────────────────────────────────────
-- RE-MEASURED 2026-08-25 -- the numbers below were 6 files / 7 tables /
-- 158 total / 151 candidates when this header was written at 3d48403.
-- They drifted the same night: SAIRNroofing Phase 3b (148bd80) and 3c
-- (c27f5a2) added more schema files carrying the sound pattern. Re-derived
-- with the same commands rather than trusted, which is the whole point of
-- this file's method.
--
-- grep -n "^grant\|^revoke" across every sql/*.sql file (the same
-- structural technique that found the original 9 append-only tables,
-- extended to the whole platform rather than files tagged "append-only")
-- shows the SOUND `revoke all ... from service_role` pattern in exactly
-- 7 real schema files: sairncode_audit_log, stonedesk_audit_log, and FIVE
-- SAIRNroofing schema files (certifications, claims, employee_auth, jobs,
-- photos -- already fixed, confirmed via
-- `grep -l "revoke all.*from service_role" sql/*.sql`, excluding this file
-- and append_only_grant_audit.sql which are audit/fix files, not schema).
-- Those 7 files cover 9 tables: rf_cert_rules, rf_certifications,
-- rf_claim_photos, rf_claims, rf_jobs, rf_photos,
-- sairnroofing_employee_auth, sairncode_audit_log, stonedesk_audit_log.
-- Every other schema file on the platform -- 154 of 163 total granted
-- tables, counted directly (`grep -rhoiE "^grant [a-z, ]+ on
-- (public\.)?[a-z_]+" sql/*.sql | grep -oE "[a-z_]+$" | sort -u | wc -l`
-- = 163; the 7 sound files account for 9 of them) --
-- across StoneDesk, SAIRNcode, SAIRNcare, SAIRNdesign, SAIRNgrounds/MSB,
-- SAIRNscape, SAIRNlaw, SAIRNsenior, SAIRNbuild, SAIRNlegacy, SAIRNdental,
-- SAIRNcash -- only ever GRANTs, never revokes-all-first, and is
-- therefore structurally a candidate for the same excess baseline. This
-- is a code-level candidate count, not a confirmed live one -- Section 1
-- below is what actually confirms it against the real database.
--
-- ── STONEDESK SLABS / SAIRNGROUNDS-MSB, CHECKED RATHER THAN ASSUMED ──────
-- Per instruction: confirmed live in api/sd-data.js what these tables'
-- real write paths actually do, rather than trusting each schema file's
-- grant line at face value (sairnlaw_audit_log's own grant line was
-- already found to be incomplete once tonight).
--   UPDATE: sd_slabs, sd_blocks, sd_bundles, sd_slab_history all write via
--   `?on_conflict=...` upserts (sd_slabs at api/sd-data.js:517; the other
--   three follow "the sd_slabs read/write shape exactly" per that file's
--   own comment). grd_schedule, grd_invasive_sightings, msb_products,
--   msb_sales (sampled) all confirmed the same on_conflict upsert shape.
--   All genuinely need UPDATE -- narrowing it would break real writes.
--   DELETE: a platform-wide grep for `method: 'DELETE'` in api/sd-data.js
--   returns exactly ONE occurrence, and it is the SC_RESOURCES
--   (SAIRNcode) branch's Compliance-Admin-gated delete -- confirmed by
--   reading that call site directly, not assumed from the open-work-index
--   row that already claimed this (a claim re-verified here, not trusted).
--   StoneDesk slabs and every SAIRNgrounds/MSB table are granted DELETE at
--   the DB level but NO live code path ever issues one. That is a real,
--   separate finding -- unused DELETE grant is a different, narrower kind
--   of excess than the unused TRUNCATE/REFERENCES/TRIGGER/MAINTAIN this
--   sweep is about, and narrowing it would be a functional capability
--   change, not just removing dead default baggage. DELIBERATELY NOT
--   BUNDLED into the fix below -- flagged as its own decision, not
--   silently folded in.
--
-- ── 19 BARE-NAMED TABLES ARE UNREACHABLE FROM ANY CODE PATH (2026-08-25) ──
-- Twenty un-prefixed table names carry the excess baseline and were
-- suspected dead. Checked from code, not from the grant export, because
-- the export is a claim like any other (see the caveat block below).
--
-- Reached independently and by a different route from the SAIRN-cc block
-- (1) above, which is why both are kept: two methods, same 19 names, is
-- worth more than one method asserted twice. Where they DISAGREE, the
-- disagreements are resolved below and neither claim was quietly dropped.
--
-- METHOD -- the reachable-table set was enumerated exhaustively, not
-- sampled. FOUR channels can put a table name in front of PostgREST in
-- this codebase, all four walked:
--   1. `rest('literal')` string constants        -- extracted, 107 names
--   2. `const TABLE = '...'` / `*_TABLE` consts  -- 21 sites, all prefixed
--   3. `rest(resource + ...)` dynamic sites      -- 12 sites, every one of
--      them keyed on an explicit map of PREFIXED names (SD_LINEAGE,
--      SDN_RESOURCES, the 28-name SC_RESOURCES, etc.), so `resource` can
--      never be a bare name at those call sites
--   4. THE BROWSER, going straight to Supabase with the ANON key and
--      never touching api/ at all -- `sb.from('table')` in the app HTML
--
-- CHANNEL 4 IS A REAL GAP THIS CHECK ORIGINALLY HAD, and it is recorded
-- rather than silently patched: the first pass enumerated api/ only, and
-- an api/-only sweep cannot see a table the browser reads directly. It
-- was caught by cross-checking against the SAIRN-cc block, which listed
-- `intake_submissions` -- a name absent from api/ entirely. Re-running
-- with channel 4 included (`grep -rhoE "\.from\(['\"]?[a-z_]+" *.html`)
-- returns exactly TWO real client-side tables platform-wide: `employees`
-- and `intake_submissions` (via `INTAKE_TABLE`, stonedesk.html:31943).
-- Neither is among the 19, so the conclusion below survives the wider
-- method -- but it survives because it was re-checked, not because the
-- first method was sound.
--
-- RESULT: 19 of the 20 are reachable by nothing.
--   conversations, demo_calls, gl_entries, licenses, messages, parts,
--   payments, profiles, projects, shop_users, shops, subscriptions,
--   usage_logs, user_storage, webhook_events  -- absent from api/ entirely
--   and with no `create table` anywhere in sql/.
--   customers, invoices, jobs, slabs -- these four ARE registered resource
--   keys, which is the trap. Every branch that handles them maps to a
--   PREFIXED table: 'customers' -> scp_customers (sd-data.js:1356),
--   'invoices' -> scp_invoices (:1440), 'jobs' -> grd_jobs (:690),
--   'slabs' -> sd_slabs (:508). The bare tables of the same name are
--   never addressed. sd-data.js's own comment at :1355 records that the
--   prefixed resource names were chosen "specifically to avoid the
--   collision", so this is by design, not coincidence.
--
-- ── TWO CORRECTIONS TO BLOCK (1)/(2) ABOVE, BOTH EVIDENCED ───────────────
--
-- CORRECTION A -- network_insights is NOT currently broken. Block (2)
-- above states that service_role "has held only the TRUNCATE/REFERENCES/
-- TRIGGER/MAINTAIN default baseline since the table was created, meaning
-- api/network.js has never been able to actually select or insert on it,"
-- and calls it a live bug of the fe730e2 class. SELECT, at least, works.
-- Disproved live, three consecutive calls, no credential used:
--     curl -s -w " [HTTP %{http_code}]" \
--       "https://sairn.vercel.app/api/network?app=stonedesk"
--     -> {"ok":true,"insights":[]} [HTTP 200]   (x3)
-- A missing grant is Postgres 42501, which api/network.js:121 turns into
-- a NAMED 503 PERMISSION_DENIED, and a missing table is 42P01/PGRST205 ->
-- 503 NOT_PROVISIONED (:115). Neither fired. A 200 with ok:true is a
-- completed SELECT against network_insights, so service_role holds SELECT.
-- HOW, given sql/network_schema.sql really does contain no grant: block
-- (4) above supplies the mechanism -- a table created through Supabase's
-- Table Editor auto-grants, unlike a raw SQL migration. That is the
-- likeliest explanation and it is a hypothesis, not a finding.
-- WHAT IS STILL OPEN: INSERT is UNVERIFIED. Proving it needs a real POST
-- that writes a row, which is not something to fire at production to win
-- an argument, so it was not done. The honest statement is: SELECT
-- confirmed present, INSERT unknown. Do not upgrade that to "the table is
-- fine" without checking the write path.
-- WHY IT MATTERS BEYOND ONE TABLE: network_insights was on the ~20
-- zero-CRUD list, and it demonstrably has CRUD. The zero-CRUD list is
-- therefore not reliable per-row, which is the same defect as the
-- truncated export it came from.
--
-- CORRECTION B -- intake_submissions is NOT unreferenced. Block (1) lists
-- it as "CONFIRMED unreferenced by any live SAIRN code path." StoneDesk
-- reads it on every Intake panel load: `INTAKE_TABLE` is declared at
-- stonedesk.html:31943 and `sb.from(INTAKE_TABLE).select('*')` runs in
-- intakeRefresh() at :31982. It is invisible to an api/-only sweep
-- because it never goes through api/ -- it is channel 4, the browser's
-- own Supabase client on the ANON key. Both sweeps had the same blind
-- spot in opposite directions, which is precisely why this is written
-- down rather than corrected in place.
-- NUANCE THAT CUTS THE OTHER WAY, stated so nobody over-reads this: an
-- anon-key path does not use service_role at all, so intake_submissions'
-- service_role grants may genuinely be dead weight even though the TABLE
-- is very much alive. "Unused by service_role" and "unreferenced by any
-- code" are different claims and block (1) merged them.
-- SEPARATE, NOT CHASED HERE: intakeRefresh()'s catch falls back to
-- localStorage silently, so if that anon read is failing today the panel
-- shows stale cached rows and reports nothing. That is a silent-failure
-- candidate for sairn-silent-failure-sweep, not a grant question.
--
-- WHAT NONE OF THIS CHANGES: Section 2 reads each table's OWN live grants
-- and never consults any list in this file. That is exactly why two
-- wrong list entries could not have caused harm -- had Section 2 been
-- driven by the derived list it would have stripped network_insights'
-- real SELECT and silently killed StoneDesk's Intelligence Network panel.
-- Recorded because the near-miss is the argument for the list-free
-- design, not a footnote to it.
--
-- ── THE EXPORT HAS NOW BEEN TRUNCATED TWICE -- CHECK THE ONE IN FRONT OF YOU ──
-- SCOPE, because this is easy to misread: what follows is about the
-- 227-table list as PASTED INTO THE SAIRN-fourth SESSION on 2026-08-25.
-- It is NOT a claim about the export SAIRN-cc analysed in the block at
-- the top of this file. That block already established the first
-- truncation and its cause -- Michael's SQL client had a row limit and
-- the first export stopped at 100 rows -- and gives 227 as the real
-- table count. This is a SECOND, independent shortfall in a later
-- rendering of the same data, which is the point: the failure mode
-- recurred after being diagnosed once.
--
-- Two problems in that paste, both found by checking rather than trusting:
--   COUNT: it is labelled 227 tables. Enumerating it, including the
--   families given in shorthand at their stated sizes (leg_* 34, msb_* 9,
--   sc_* 29, scp_* 14, sdn_* 17), totals 215 -- 12 short of its own label.
--   CONTENT: 11 tables that are code-reachable, have a real schema file,
--   and use the UNSOUND grant pattern -- so they MUST carry the excess
--   baseline and MUST appear in a TRUNCATE-filtered list -- are absent
--   from it: alf_claim_routes, alf_signals, alf_staff_credentials,
--   dnt_cred_rules, dnt_credentials, sen_caregivers, sen_claims,
--   sen_clients, sen_portal_links, sen_visits, sairnsenior_employee_auth.
--   Their schema files do carry a `revoke all`, but it reads
--   `revoke all on public.X from anon, authenticated` -- NOT from
--   service_role (sairnsenior_visits_schema.sql:51-52 is the pattern), so
--   the default-ACL baseline survives untouched and absence is unexplained.
--   Note what that set is: every SAIRNsenior table plus the SAIRNcare and
--   SAIRNdental stragglers -- a contiguous alphabetical-ish tail, which is
--   what a row cap looks like, not what a random omission looks like.
-- Two readings, not resolved here: either those migrations were never run
-- (the exact class 6776f99 found for sairnscape_org_intel and
-- sairncash_waitlist), or this rendering is short too. 11 unexplained
-- absences against a 12-table count shortfall is suggestive of the
-- latter, and is not proof of either. The two counts can also both be
-- right about different things -- 227 real tables, 215 pasted.
-- CONSEQUENCE: run Section 1 live and read its real output before
-- Section 2. Section 2 itself is unaffected -- it queries
-- information_schema directly and never reads the export -- but anyone
-- predicting what Section 2 will touch from that paste will be wrong.
--
-- ── WHY THE FIX BELOW IS DYNAMIC, NOT 150 HAND-WRITTEN LINES ─────────────
-- Hand-enumerating ~150 REVOKE/GRANT pairs is exactly the kind of manual
-- transcription that introduces the next bug (a copy-paste privilege
-- dropped or added by mistake). Section 2 instead reads each table's OWN
-- CURRENT select/insert/update/delete grants from the database itself and
-- re-asserts exactly that same set -- it cannot add or remove any
-- functional capability, by construction, because it never invents a
-- privilege that was not already there. It only ever strips
-- TRUNCATE/REFERENCES/TRIGGER/MAINTAIN, which no schema file on this
-- platform ever explicitly grants (confirmed: zero explicit `references`
-- or `trigger` or `maintain` grants anywhere in sql/*.sql) -- so stripping
-- them is safe everywhere, unconditionally, without per-table judgment.

-- ── SECTION 1: DISCOVERY -- run this first, read the output before Section 2 ──
-- Every public table where service_role holds TRUNCATE, with its full
-- current privilege set alongside. List-free: does not depend on the
-- ~150-table candidate list above, so it will also catch anything that
-- list missed.
select
  t.table_name,
  string_agg(distinct g.privilege_type, ', ' order by g.privilege_type) as current_privs,
  bool_or(g.privilege_type = 'TRUNCATE')   as has_truncate,
  bool_or(g.privilege_type = 'REFERENCES') as has_references,
  bool_or(g.privilege_type = 'TRIGGER')    as has_trigger,
  bool_or(g.privilege_type = 'UPDATE')     as has_update,
  bool_or(g.privilege_type = 'DELETE')     as has_delete
from information_schema.tables t
join information_schema.role_table_grants g
  on g.table_name = t.table_name and g.table_schema = t.table_schema
where t.table_schema = 'public' and g.grantee = 'service_role'
group by t.table_name
having bool_or(g.privilege_type = 'TRUNCATE')
order by t.table_name;

-- ── SECTION 2 REVIEW, 2026-08-25 -- 6 FINDINGS, NOTHING CHANGED YET ──────
-- Section 2 was reviewed line by line rather than approved on the strength
-- of its own comment. The central claim -- "cannot add or remove
-- functional capability, by construction" -- holds for the code path as
-- written: keep_privs is filtered to a fixed IN-list, so the re-GRANT can
-- only ever restore a subset of what the table already had. The findings
-- below are about coverage, verification and blast radius, not about that
-- claim being false. Ordered by how much they matter. NONE of them are
-- applied -- the DO block is untouched, because whoever actually runs this
-- against the live database should decide, and one of the six is a
-- decision, not a defect.
--
-- (R1) THE "CANNOT CHANGE CAPABILITY" CLAIM IS UNPROVEN FOR THE ACTUAL
-- RUN, and this is the biggest gap. It is proven for the LOGIC; it is not
-- proven for the EVENT. There is no before-capture step anywhere in this
-- file, so after Section 2 runs there is no artifact to diff against and
-- the only verification (Section 3) checks that TRUNCATE is GONE, never
-- that SELECT/INSERT/UPDATE/DELETE SURVIVED. A bug in the loop that
-- dropped a privilege would pass Section 3 silently. The index row for the
-- verb-gate change already demands baseline-replay proof for exactly this
-- class of change; this file should meet the same bar. Recommended, as a
-- new Section 0 run BEFORE Section 2 in the same editor session:
--     create temp table grant_baseline as
--     select table_name, privilege_type
--     from information_schema.role_table_grants
--     where table_schema='public' and grantee='service_role'
--       and privilege_type in ('SELECT','INSERT','UPDATE','DELETE');
-- and then, as the real Section 3, a full-outer-join of that snapshot
-- against the post-run state expecting ZERO rows on either side. Note the
-- temp table dies with the session, so Sections 0, 2 and 3 must be one
-- editor session -- which is a feature: it makes the proof and the change
-- inseparable.
--
-- (R2) BOTH SECTIONS FILTER ON TRUNCATE ALONE, SO A REFERENCES-ONLY OR
-- TRIGGER-ONLY TABLE IS INVISIBLE TO THE SWEEP AND TO ITS VERIFICATION.
-- `having bool_or(privilege_type = 'TRUNCATE')` is the filter in Section
-- 1, Section 2 and (by reference) Section 3. This file is titled for four
-- privileges and only searches for one of them. The defence is that the
-- default ACL grants all four together so they co-occur -- but that
-- coupling is precisely what append_only_grant_audit.sql and the
-- ALTER DEFAULT PRIVILEGES fix have already been breaking on purpose, and
-- any hand-run REVOKE breaks it too. Section 3 would then report "zero
-- rows, clean" over tables still holding REFERENCES. Recommended filter,
-- all three places:
--     having bool_or(privilege_type in
--       ('TRUNCATE','REFERENCES','TRIGGER','MAINTAIN'))
--
-- (R3) THE EXCLUSION OF network_insights RESTS ON A CLAIM DISPROVED
-- ABOVE. The comment excludes it because it "already has zero real CRUD
-- for service_role today." Correction A shows SELECT works live, three
-- consecutive 200s. So the exclusion does not protect anything -- it just
-- leaves one table's excess baseline in place, and Section 3 will then
-- correctly report a leftover row that looks like a failure. Do not
-- silently delete the exclusion either: read network_insights' actual row
-- in Section 1's live output first, and drop the exclusion only if that
-- row shows real CRUD to preserve. The license_keys exclusion is
-- UNAFFECTED by this and remains well-reasoned -- no tracked schema,
-- platform-wide blast radius, exclude it and hand-check after.
--
-- (R4) COLUMN-LEVEL GRANTS AND GRANT OPTION WOULD BE DESTROYED SILENTLY.
-- `REVOKE ALL ON <table>` strips column-level privileges too, and the
-- re-GRANT only restores TABLE-level ones; likewise `WITH GRANT OPTION`
-- is not carried across. Neither is visible in role_table_grants -- the
-- first lives in role_column_grants, the second in that view's
-- is_grantable column, and Section 1 selects neither. The repo is clean
-- on both (`grep` finds zero column grants and zero `with grant option`
-- in sql/*.sql), but the repo is not the database -- this file already
-- documents five real tables with no tracked CREATE TABLE, and a table
-- on the same Supabase project from outside this repo cannot be ruled
-- out. Cheap pre-flight, expect zero rows:
--     select * from information_schema.role_column_grants
--     where table_schema='public' and grantee='service_role';
--     select table_name, privilege_type from information_schema.role_table_grants
--     where table_schema='public' and grantee='service_role' and is_grantable='YES';
--
-- (R5) THE WHOLE LOOP IS ONE TRANSACTION HOLDING A LOCK PER TABLE. A DO
-- block is a single statement, so all ~150 REVOKE/GRANT pairs commit
-- together -- good, because a partial application is the one outcome
-- nobody could reason about afterwards, and it means no window exists
-- where a table has been revoked but not re-granted. The cost is that
-- every relation it touches is locked until the block commits, against
-- live API traffic. It is catalog-only work and should be fast, but
-- "should be" is not a measurement. Run it in a quiet window, the same
-- way the .gitattributes row demands one. Not a defect -- a scheduling
-- constraint that is currently written down nowhere.
--
-- (R6) PRECONDITION NEVER STATED: THIS MUST RUN AS THE TABLE OWNER.
-- information_schema.role_table_grants only shows grants where the
-- current user is grantor, grantee, or a member of one of them, and
-- REVOKE only removes grants the executing role has authority over. Run
-- as postgres in the Supabase SQL editor both hold. Run as anything less
-- and the loop silently iterates a SHORT list, changes less than it
-- claims, and Section 3 reports clean because it is filtered by the same
-- blind spot. Add `select current_user;` as the first line of the run and
-- confirm it says postgres before executing anything.
--
-- ALSO CHECKED AND CLEAN, so nobody re-derives them: no partitioned
-- tables anywhere in sql/*.sql (REVOKE on a parent would not cascade to
-- partitions), and zero explicit REFERENCES/TRIGGER/MAINTAIN grants
-- anywhere in the repo, which is what makes stripping them unconditionally
-- safe rather than a per-table judgment.
--
-- ── SECTION 2: DRAFT FIX -- NOT RUN. Review Section 1's real output first. ──
-- For every table service_role holds TRUNCATE on, strips
-- TRUNCATE/REFERENCES/TRIGGER/MAINTAIN and re-grants exactly whichever of
-- SELECT/INSERT/UPDATE/DELETE it already had -- never more, never fewer.
-- Idempotent and safe to re-run; touches no row data; changes no
-- functional capability of any table.
--
-- DO $$
-- DECLARE
--   r RECORD;
--   keep_privs TEXT;
-- BEGIN
--   FOR r IN
--     SELECT t.table_name,
--            string_agg(DISTINCT g.privilege_type, ', ') AS all_privs
--     FROM information_schema.tables t
--     JOIN information_schema.role_table_grants g
--       ON g.table_name = t.table_name AND g.table_schema = t.table_schema
--     WHERE t.table_schema = 'public' AND g.grantee = 'service_role'
--       -- Excluded per the findings above, not silently swept in:
--       -- license_keys has no tracked schema to verify Section 2's output
--       -- against and carries outsized blast radius (every license check
--       -- on the platform); network_insights already has zero real CRUD
--       -- for service_role today (a separate, unfixed grant bug, not
--       -- something this sweep should touch or appear to "fix").
--       AND t.table_name NOT IN ('license_keys', 'network_insights')
--     GROUP BY t.table_name
--     HAVING bool_or(g.privilege_type = 'TRUNCATE')
--   LOOP
--     SELECT string_agg(priv, ', ') INTO keep_privs
--     FROM unnest(string_to_array(r.all_privs, ', ')) AS priv
--     WHERE priv IN ('SELECT', 'INSERT', 'UPDATE', 'DELETE');
--
--     EXECUTE format('REVOKE ALL ON public.%I FROM service_role', r.table_name);
--     IF keep_privs IS NOT NULL THEN
--       EXECUTE format('GRANT %s ON public.%I TO service_role', keep_privs, r.table_name);
--     END IF;
--
--     RAISE NOTICE 'Fixed %: kept %', r.table_name, coalesce(keep_privs, '(nothing -- had only TRUNCATE/REFERENCES/TRIGGER)');
--   END LOOP;
-- END $$;

-- ── SECTION 3: VERIFY, after Section 2 is actually run ───────────────────
-- Re-run Section 1. Expect zero rows.
--
-- INSUFFICIENT AS WRITTEN -- see R1 and R2 in the review block above.
-- Re-running Section 1 proves only that TRUNCATE is gone. It does not
-- prove that SELECT/INSERT/UPDATE/DELETE survived, which is the property
-- this whole file rests on, and with the TRUNCATE-only filter it does not
-- prove REFERENCES or TRIGGER are gone either. The real verification is
-- the Section 0 baseline diff described in R1, expecting zero rows on
-- both sides of a full outer join. Left as-is rather than rewritten,
-- because Section 2 is not mine to change and a verification step should
-- be agreed before it is relied on, not slipped in.

-- ── WHAT THIS DOES NOT COVER ──────────────────────────────────────────────
-- Same ownership caveat as every other grant file tonight: postgres owns
-- these tables and holds every privilege implicitly regardless of any
-- REVOKE here. This closes the service_role/API surface only.
--
-- The unused-DELETE finding above (StoneDesk slabs, SAIRNgrounds/MSB, and
-- likely most non-SC_RESOURCES full-CRUD tables) is NOT addressed here --
-- narrowing it is a real, separate, functional-capability decision, not
-- a mechanical strip-the-unused-default fix, and deserves its own review
-- rather than riding along on this one.
