-- sql/rf_cert_rules_load_gate_generated.sql
-- GENERATED by tools/sairn_build_load_gates.py -- DO NOT HAND-EDIT.
-- Re-run that script after any seed change; this file is derived, not authored.
-- READ-ONLY: no insert, update, delete, grant, revoke, alter, drop, truncate.
--
-- Compares every live rf_cert_rules row against the seed it should have come
-- from. A row in the output is a licence serving something the seeds do not say.
--
-- BOTH SIDES ARE SUBTRACTIVE. This table keeps compute content in PROMOTED
-- COLUMNS, not only in `data`, so comparing the blob alone would miss a wrong
-- value in one of them. to_jsonb(row) names no columns, so a column added
-- later is compared by default instead of being skipped by a stale list.
-- Bookkeeping columns subtracted: id, license_hash, app_id, created_at, updated_at, verified_by, rule_id.
--
-- The expected side mirrors the server's write-path normalisation, read from
-- api/sd-data.js rather than assumed: `state` uppercased, `status` defaulted to
-- 'active'. Without that the gate reports false STALE on every row whose seed
-- omits status, and a gate that cries wolf on its first run gets switched off.

with expected(rule_id, seed_file, compute) as (values
  ('OH-ROOFING-NO-STATE-LICENSE', 'sairnroofing_certifications_seed_ohio.json', '{"data": {"authority": {"citation": "ORC 4740.01 (Construction Industry Licensing Board — definitions)", "quote": "heating, ventilating, and air conditioning contractor; refrigeration contractor; electrical contractor; plumbing contractor; hydronics contractor — the enumerated specialty contractor types; the word \"roofing\" does not appear in this section", "read_on": "2026-08-24", "url": "https://codes.ohio.gov/ohio-revised-code/section-4740.01"}, "label": "Ohio — no state-level roofing contractor licence exists; only five trades are licensed", "licensed_trades": ["HVAC", "refrigeration", "electrical", "plumbing", "hydronics"], "notes": ["The correct Ohio answer is a NEGATIVE one. This rule exists so the app can say ''Ohio does not license this trade'' as a sourced statement, rather than showing an empty licensing panel that a user would read as ''not set up yet''.", "This does NOT mean a roofer in Ohio is unregulated. Local registration, insurance and bonding requirements are set by individual municipalities and counties, and vary between them. Those are entered per-jurisdiction as ''local_license'' records, because there is no statewide list to seed.", "effective_from is the chapter''s own era rather than a precise enactment date; the licensing-board chapter has been in force well before any date this app cares about, and no rule in this app turns on that boundary."], "state_license_required": false}, "effective_from": "2003-01-01", "effective_to": null, "requirement_type": "state_licensing", "role": null, "state": "OH", "status": "active"}'::jsonb),
  ('US-OSHA-FALL-PROTECTION-6FT', 'sairnroofing_certifications_seed_ohio.json', '{"data": {"authority": {"citation": "29 CFR 1926.501(b)(10)-(11)", "quote": "Each employee engaged in roofing activities on low-slope roofs, with unprotected sides and edges 6 feet (1.8 m) or more above lower levels shall be protected from falling by guardrail systems, safety net systems, personal fall arrest systems, or a combination …", "read_on": "2026-08-24", "url": "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.501"}, "label": "OSHA — fall protection required at 6 feet on low-slope and steep roofs", "notes": ["This is a WORKSITE standard, not a per-employee credential, and the app must not present it as one. It is seeded so the training records that support it (fall-protection training, competent-person designation) have a citable reason to exist.", "Roofing-specific: 1926.501(b)(10) covers low-slope roofs and (b)(11) steep roofs, each at the same 6-foot trigger. The permitted protections differ between them.", "The app does NOT compute whether a given job complies. It records whether the crew assigned to it holds current fall-protection training."], "trigger_height_feet": 6}, "effective_from": "1995-02-06", "effective_to": null, "requirement_type": "safety_standard", "role": null, "state": "US", "status": "active"}'::jsonb),
  ('US-OSHA-OUTREACH-CARD-NO-EXPIRY', 'sairnroofing_certifications_seed_ohio.json', '{"data": {"authority": {"citation": "OSHA Outreach Training Program — card validity", "quote": "OSHA does not place an expiration date on the 10-hour or 30-hour Outreach Training Program cards; requirements to hold or renew a card originate with states, owners, general contractors and unions rather than with federal OSHA", "read_on": "2026-08-24", "url": "https://www.osha.gov/training/outreach"}, "federal_expiry": false, "known_state_refresh_windows_years": {"CT": 5, "MO": 5, "NV": 5, "NY": 5}, "label": "OSHA 10/30-hour Outreach card — no federal expiration; refresh windows are state or contract imposed", "notes": ["The federal half is verified from OSHA''s own Outreach program: the card carries no expiration date and OSHA does not require any worker to hold one — card requirements come from states, owners, general contractors and unions.", "The per-state refresh windows above are recorded as LOCATED BUT NOT PRIMARY-VERIFIED. They came from a secondary compilation; the underlying statutes (e.g. NY Labor Law 220-h) were not read in this pass. They are stored as data a user can correct, and the app must not present them as confirmed law. See unverified_notes.", "Ohio is deliberately absent from that map: no Ohio refresh requirement was found, and absence of evidence is recorded as absence of a claim, not as a confirmed ''none''."]}, "effective_from": "2015-01-01", "effective_to": null, "requirement_type": "training_card", "role": null, "state": "US", "status": "active"}'::jsonb)
),
licences as (
  select k.key, encode(digest(k.key,'sha256'),'hex') as h
  from public.license_keys k where k.app_id = 'sairnroofing'
),
live as (
  select l.key as licence, r.rule_id as rule_id,
         (to_jsonb(r) - 'id' - 'license_hash' - 'app_id' - 'created_at' - 'updated_at' - 'verified_by' - 'rule_id') as compute
  from licences l
  join public.rf_cert_rules r on r.license_hash = l.h
),
-- every (licence, seed rule) PAIR. Joining expected straight to live on
-- rule_id alone cannot see "missing from licence A while present on licence B".
wanted as (
  select l.key as licence, x.rule_id, x.seed_file, x.compute
  from licences l cross join expected x
)
select
  coalesce(w.licence, v.licence)   as licence,
  coalesce(w.rule_id, v.rule_id)   as rule_id,
  w.seed_file,
  case
    when v.rule_id is null then 'MISSING -- seed rule never loaded onto this licence'
    when w.rule_id is null then 'ORPHAN -- live row with no seed; origin unknown'
    else 'STALE -- live content differs from the seed'
  end                              as verdict,
  jsonb_pretty(w.compute)          as seed_compute,
  jsonb_pretty(v.compute)          as live_compute
from wanted w
full outer join live v on v.licence = w.licence and v.rule_id = w.rule_id
where v.rule_id is null or w.rule_id is null
   or v.compute is distinct from w.compute
order by 4, 1, 2;
