-- sql/rf_contingency_rules_load_gate_generated.sql
-- GENERATED by tools/sairn_build_load_gates.py -- DO NOT HAND-EDIT.
-- Re-run that script after any seed change; this file is derived, not authored.
-- READ-ONLY: no insert, update, delete, grant, revoke, alter, drop, truncate.
--
-- Compares every live rf_contingency_rules row against the seed it should have come
-- from. A row in the output is a licence serving something the seeds do not say.
--
-- BOTH SIDES ARE SUBTRACTIVE. This table keeps compute content in PROMOTED
-- COLUMNS, not only in `data`, so comparing the blob alone would miss a wrong
-- value in one of them. to_jsonb(row) names no columns, so a column added
-- later is compared by default instead of being skipped by a stale list.
-- Bookkeeping columns subtracted: id, license_hash, app_id, created_at, updated_at, verified_by, rule_id.
--
-- The expected side mirrors the server's write-path normalisation, read from
-- api/sd-data.js rather than assumed: `state` uppercased, `status` defaulted to
-- 'active'. Without that the gate reports false STALE on every row whose seed
-- omits status, and a gate that cries wolf on its first run gets switched off.

with expected(rule_id, seed_file, compute) as (values
  ('RFCON-OH-HSSA-CANCEL', 'sairnroofing_contingency_seed_ohio.json', '{"business_day_basis": "oh_hssa", "count": 3, "data": {"applies_only_when_solicited": true, "authority": "Ohio Rev. Code 1345.22 (Home Solicitation Sales Act -- right of buyer to cancel)", "form_required": true, "indefinite_if_noncompliant": true, "notes": ["This is the GENERAL home-solicitation statute, not a roofing statute. Ohio has no roofing-specific contingency law.", "R.C. 1345.21 defines ''business day'' as any calendar day EXCEPT SUNDAY and eleven named holidays: New Year''s day, Martin Luther King day, Presidents'' day, Memorial day, Juneteenth day, Independence day, Labor day, Columbus day, Veterans day, Thanksgiving day, Christmas day. Saturday counts.", "The statute names those days and does not provide for observed-day shifting when one falls on a Sunday, so the engine applies none.", "Refunds: the seller must return all payments within ten business days of receiving the cancellation notice (R.C. 1345.23). Not modelled as a deadline in v1 -- flagged, not faked."], "notice_required": true, "read_on": "2026-08-25", "url": "https://codes.ohio.gov/ohio-revised-code/section-1345.22", "verbatim": "You, the buyer, may cancel this transaction at any time prior to midnight of the third business day after the date of this transaction.", "verbatim_source": "R.C. 1345.23 -- the notice language the seller must place, clearly and conspicuously, in bold-face type of a minimum size of ten points, on the copy of the contract left with the buyer."}, "effective_from": "1972-11-15", "state": "OH", "status": "active", "trigger_event": "execution", "unit": "business_days"}'::jsonb),
  ('RFCON-OH-HSSA-SCOPE', 'sairnroofing_contingency_seed_ohio.json', '{"business_day_basis": "oh_hssa", "count": 3, "data": {"authority": "Ohio Rev. Code 1345.21(A) (definition of ''home solicitation sale'')", "notes": ["Loaded as ''superseded'' ON PURPOSE: this row is the SCOPE evidence for RFCON-OH-HSSA-CANCEL, not a second live rule. Only one active rule may govern a state, and two active rows would be exactly the ambiguity the engine flags.", "The exclusion matters as much as the definition: the Act does not reach a sale where the buyer initiated contact and the seller has a fixed business establishment in Ohio where those goods or services are regularly offered. That is why signing_venue is captured at signature time and cannot be inferred later."], "read_on": "2026-08-25", "url": "https://codes.ohio.gov/ohio-revised-code/section-1345.21", "verbatim": "A sale of consumer goods or services in which the seller or a person acting for the seller engages in a personal solicitation of the sale at a residence of the buyer ... or in which the buyer''s agreement or offer to purchase is made at a place other than the seller''s place of business."}, "effective_from": "1972-11-15", "state": "OH", "status": "superseded", "trigger_event": "execution", "unit": "business_days"}'::jsonb)
),
licences as (
  select k.key, encode(digest(k.key,'sha256'),'hex') as h
  from public.license_keys k where k.app_id = 'sairnroofing'
),
live as (
  select l.key as licence, r.rule_id as rule_id,
         (to_jsonb(r) - 'id' - 'license_hash' - 'app_id' - 'created_at' - 'updated_at' - 'verified_by' - 'rule_id') as compute
  from licences l
  join public.rf_contingency_rules r on r.license_hash = l.h
),
-- every (licence, seed rule) PAIR. Joining expected straight to live on
-- rule_id alone cannot see "missing from licence A while present on licence B".
wanted as (
  select l.key as licence, x.rule_id, x.seed_file, x.compute
  from licences l cross join expected x
)
select
  coalesce(w.licence, v.licence)   as licence,
  coalesce(w.rule_id, v.rule_id)   as rule_id,
  w.seed_file,
  case
    when v.rule_id is null then 'MISSING -- seed rule never loaded onto this licence'
    when w.rule_id is null then 'ORPHAN -- live row with no seed; origin unknown'
    else 'STALE -- live content differs from the seed'
  end                              as verdict,
  jsonb_pretty(w.compute)          as seed_compute,
  jsonb_pretty(v.compute)          as live_compute
from wanted w
full outer join live v on v.licence = w.licence and v.rule_id = w.rule_id
where v.rule_id is null or w.rule_id is null
   or v.compute is distinct from w.compute
order by 4, 1, 2;
