-- sql/sairnlaw_deposit_void_balance_guard.sql
-- SAIRNlaw trust disbursement server-sync, step 3a: closes the deposit-void
-- balance gap disclosed in SAIRN-BACKLOG.md ("SAIRNlaw void-of-deposit can
-- retroactively negative a client's balance"). Extracts law_client_balance()
-- as a shared helper (used by both this and step 2's disbursement function)
-- and adds law_check_and_void_deposit(), the atomic guard for voiding a
-- Deposit. See docs/superpowers/specs/2026-08-17-sairnlaw-deposit-void-balance-guard-design.md.
-- Safe to re-run -- create-or-replace throughout.

-- ═══════════════════════════════════════════════════════════════════════
-- FUNCTION DEFINITIONS REMOVED 2026-09-03 -- they now live in ONE file:
--
--     sql/sairnlaw_trusttx_functions.sql
--
-- They were removed rather than left here with a warning. Three files had
-- come to define law_check_and_insert_disbursement() with plain
-- `create or replace`, so re-running an older one for its OTHER contents
-- SILENTLY REVERTED the function to that file's version -- no error, no
-- warning, no diff. Two of the three already carried a prose warning about
-- the file before them; a comment does not stop a `\i` in a SQL editor.
--
-- The most recent revert would have restored a disbursement function that
-- returns ONE CLIENT'S TRUST ROW to ANOTHER CLIENT'S REQUEST. The trap is
-- gone now because the duplicate text is gone.
-- ═══════════════════════════════════════════════════════════════════════
