-- sql/sairnlaw_trusttx_cross_client_collision_2026-09-03.sql
-- SAIRNlaw trust disbursement, step 3b: closes a CROSS-CLIENT TRUST-ACCOUNT
-- LEAK in law_check_and_insert_disbursement().
--
-- Supersedes the function body in sql/sairnlaw_deposit_void_balance_guard.sql
-- (step 3a), which itself superseded the one in
-- sql/sairnlaw_trust_disbursement_atomic_check.sql (step 2). If either of
-- those files is ever re-run, RE-RUN THIS ONE IMMEDIATELY AFTER -- both would
-- otherwise silently restore the vulnerable version with no error anywhere,
-- exactly as step 3a's own header warns about step 2.
--
-- Safe to re-run -- create-or-replace throughout, no DDL, no data change.
--
-- ════════════════════════════════════════════════════════════════════════
-- WHAT WAS WRONG. THE LOCK AND THE UNIQUENESS KEY DISAGREED.
-- ════════════════════════════════════════════════════════════════════════
-- The advisory lock is taken on (license_hash, client_id) -- the CALLER'S
-- asserted client. The retry-idempotency lookup then matched on
-- (license_hash, trusttx_id) with NO client predicate, and the table's unique
-- constraint is likewise (license_hash, trusttx_id) -- licence-wide.
--
-- One key is per-client and the other is per-licence. Everything below follows
-- from that single mismatch.
--
-- ── FAILURE 1: A CLIENT'S TRUST ROW RETURNED TO ANOTHER CLIENT'S REQUEST ─
-- A disbursement posted for client B, whose trusttx_id already exists under
-- client A, took the retry-idempotency branch and returned A'S ROW. The caller
-- got HTTP 200 {ok:true} carrying A's amount, matter_id, description and
-- reference number -- in a lawyer's trust ledger, that is one client's
-- financial record handed to another client's transaction. No money moved for
-- B and nothing said so.
--
-- ── FAILURE 2: A PHANTOM DISBURSEMENT THAT REPORTS SUCCESS ──────────────
-- `on conflict (license_hash, trusttx_id) do nothing returning *` returns NO
-- ROW on conflict, so v_row stayed NULL and the function returned a null
-- composite. api/sd-data.js then did:
--
--     res.status(200).json({ ok: true, data: row ? row.data : payload });
--
-- -- echoing THE CALLER'S OWN PAYLOAD back as though it were the stored row.
-- The lawyer's screen showed the disbursement posted; the database had no such
-- row; the trust balance on screen and the trust balance in the ledger
-- disagreed, in the client's favour on screen. That is the silent-success
-- class this platform refuses everywhere else, on a trust account.
--
-- ── WHY THE LOCK DID NOT PREVENT IT ────────────────────────────────────
-- Two calls colliding on trusttx_id but naming DIFFERENT clients take
-- DIFFERENT advisory locks, so they do not serialize against each other at
-- all. The lock only ever protected the balance arithmetic for one client; it
-- was never able to protect a licence-wide unique key.
--
-- ── AND IT IS REACHABLE, NOT THEORETICAL ───────────────────────────────
-- sairnlaw.html's id generator is
--
--     newId(prefix) => prefix + '-' + Date.now() + '-' + floor(random()*1000)
--
-- One thousand suffixes per millisecond, not a UUID, and the same generator
-- serves every client in the firm. Two people posting in the same millisecond
-- collide with probability 1/1000, and over a firm's transaction history the
-- birthday bound makes it a question of when. This was found by reading the
-- id generator, not by assuming a UUID.
--
-- ════════════════════════════════════════════════════════════════════════
-- THE FIX, AND WHY IT REFUSES RATHER THAN REPAIRS
-- ════════════════════════════════════════════════════════════════════════
-- 1. The idempotency lookup now carries `and client_id = p_client_id`. A
--    genuine retry -- same id, same client -- still returns the existing row,
--    which is the whole point of that branch and is preserved exactly.
--
-- 2. A same-id/different-client collision now RAISES. It does not silently
--    return the other client's row, and it does not quietly mint a new id on
--    the caller's behalf either. Re-keying someone's trust transaction inside
--    the database, without the firm knowing, would put a disbursement in the
--    ledger under an id their own records do not have -- a reconciliation
--    problem discovered at an audit rather than at the keyboard. The caller is
--    told, and re-submits with a fresh id.
--
-- 3. The `do nothing` null path is closed. If the insert still conflicts after
--    both checks -- a same-id/same-client insert committed by a concurrent
--    transaction between the lookup and the insert -- the row is RE-SELECTED
--    and returned, because that is a true retry and returning it is correct.
--    If even that finds nothing, the function raises rather than returning
--    null. NO PATH RETURNS NULL ANY MORE, which is what let a phantom
--    disbursement report success.
--
-- The advisory lock is left keyed on (license_hash, client_id). Widening it to
-- the licence would serialize every client in the firm behind one another for
-- a collision that is rare -- the correct fix is to make the rare case LOUD,
-- not to make the common case slow.

-- ═══════════════════════════════════════════════════════════════════════
-- FUNCTION DEFINITIONS REMOVED 2026-09-03 -- they now live in ONE file:
--
--     sql/sairnlaw_trusttx_functions.sql
--
-- They were removed rather than left here with a warning. Three files had
-- come to define law_check_and_insert_disbursement() with plain
-- `create or replace`, so re-running an older one for its OTHER contents
-- SILENTLY REVERTED the function to that file's version -- no error, no
-- warning, no diff. Two of the three already carried a prose warning about
-- the file before them; a comment does not stop a `\i` in a SQL editor.
--
-- The most recent revert would have restored a disbursement function that
-- returns ONE CLIENT'S TRUST ROW to ANOTHER CLIENT'S REQUEST. The trap is
-- gone now because the duplicate text is gone.
-- ═══════════════════════════════════════════════════════════════════════

-- The analysis above is kept as the INCIDENT RECORD -- it is why the
-- guarantees in sairnlaw_trusttx_functions.sql are worded the way they are,
-- and deleting it would leave that file's refusals looking like taste.
-- This file no longer executes anything.
