-- sql/schema_snapshot_query.sql
--
-- Produces the LIVE schema snapshot that tools/sairn_sql_preflight.py needs in
-- order to be a real check rather than a repo-consistency check.
--
-- WHY IT IS A QUERY YOU RUN AND NOT SOMETHING THE TOOL FETCHES. No clone on
-- this platform has generic information_schema access -- the app APIs expose
-- named actions (read/write/roster/whoami), not introspection, and adding an
-- endpoint that returns the whole schema shape to anyone holding a licence key
-- is a worse trade than pasting a query. This follows the pattern already used
-- by sql/introspect_undeclared_tables_2026-08-26.sql and the grant audits.
--
-- HOW TO USE
--   1. Run this whole file in the Supabase SQL editor.
--   2. Copy the single JSON value out of the result cell.
--   3. Save it as db/schema_snapshot.json in the clone (create db/ if needed).
--   4. python tools/sairn_sql_preflight.py --live db/schema_snapshot.json sql/your_file.sql
--
-- READ-ONLY. It selects from information_schema and writes nothing.
--
-- THE SNAPSHOT GOES STALE THE MOMENT SOMEONE RUNS A MIGRATION, and the tool
-- cannot tell. The generated JSON therefore carries `_generated_at`; re-run this
-- query whenever a schema file has been applied since, and treat a snapshot
-- older than the last migration as DECLARED-grade evidence, not LIVE.

-- CHECK CONSTRAINTS ADDED 2026-09-02, and the reason is a live incident.
-- SAIRNdental's dnt_appointments carried `octet_length(data::text) <= 65536`
-- while sql/sairndental_data_schema.sql had been raised to 1291059 and a
-- migration written. A migration is inert until someone runs it, and NOTHING
-- could see the difference: this snapshot captured tables and columns only, so
-- the preflight compared the two things that agreed and never looked at the one
-- that did not. A schema file saying one bound while the database enforces
-- another is invisible to every gate that was running.
--
-- Emitted under `_constraints` rather than as another top-level key so the
-- existing {table: [columns]} shape is untouched and an older reader keeps
-- working. Only CHECK constraints are captured: those are the ones written by
-- hand in sql/*.sql and therefore the ones that can silently disagree.
-- Primary keys, uniques and foreign keys are generated by the same DDL that
-- creates the table and do not drift the same way.
select jsonb_pretty(
  jsonb_build_object('_generated_at', now()::text)
  || jsonb_build_object('_constraints', coalesce(
       (select jsonb_object_agg(x.rel, x.defs)
          from (
            select c.conrelid::regclass::text as rel,
                   jsonb_object_agg(c.conname, pg_get_constraintdef(c.oid)) as defs
              from pg_constraint c
              join pg_class     cl on cl.oid = c.conrelid
              join pg_namespace n  on n.oid = cl.relnamespace
             where n.nspname = 'public'
               and cl.relkind = 'r'
               and c.contype  = 'c'          -- CHECK only
             group by c.conrelid
          ) x),
       '{}'::jsonb))
  || coalesce(
       jsonb_object_agg(t.table_name, t.cols),
       '{}'::jsonb
     )
)
from (
  select c.table_name,
         jsonb_agg(c.column_name order by c.ordinal_position) as cols
    from information_schema.columns c
    join information_schema.tables tb
      on tb.table_schema = c.table_schema
     and tb.table_name   = c.table_name
   where c.table_schema = 'public'
     -- BASE TABLE only. A view's columns are real to a SELECT and not to an
     -- INSERT, and including them would let a preflight pass a write against
     -- something that cannot be written.
     and tb.table_type = 'BASE TABLE'
   group by c.table_name
) t;
