-- sql/schema_snapshot_constraints_query.sql
--
-- Produces ONLY the `_constraints` half of the schema snapshot, so it can be
-- merged into an existing db/schema_snapshot.json without re-pasting 439
-- tables.
--
-- ── WHY THIS FILE EXISTS, AND WHAT IT IS NOT ─────────────────────────────
-- `sql/schema_snapshot_query.sql` ALREADY emits `_constraints`. It has since
-- 2026-09-02. The snapshot run on 2026-10-05 15:10:30 UTC came back WITHOUT
-- that key, which means an OLDER copy of the query was pasted into the editor
-- -- the tables-and-columns version from before that date.
--
-- So nothing here is a new capability. This is the CHEAP PATH: re-running the
-- full query means copying a 440-key JSON blob again, and the only part
-- missing is small.
--
-- EITHER IS CORRECT. If you would rather do it in one step, run
-- sql/schema_snapshot_query.sql (the CURRENT copy in this repo) and overwrite
-- db/schema_snapshot.json wholesale. This file exists only to save that.
--
-- ── WHY THE MISSING HALF MATTERS ─────────────────────────────────────────
-- Without `_constraints`, tools/sairn_sql_preflight.py reports
--
--     COULD NOT CHECK   snapshot carries no _constraints key
--
-- which is honest and is NOT a pass. The check exists because of a real
-- incident: SAIRNdental's `dnt_appointments` enforced
-- `octet_length(data::text) <= 65536` while sql/sairndental_data_schema.sql
-- had been raised to 1291059 and a migration written. A migration is inert
-- until someone runs it, and the snapshot captured tables and columns only --
-- so the preflight compared the two things that agreed and never looked at
-- the one that did not. A schema file naming one bound while the database
-- enforces another is invisible to every gate without this.
--
-- Only CHECK constraints are captured, deliberately: those are the ones
-- written by hand in sql/*.sql and therefore the ones that can silently
-- disagree. Primary keys, uniques and foreign keys are generated by the same
-- DDL that creates the table and do not drift the same way.
--
-- READ-ONLY. It selects from pg_catalog and writes nothing.
--
-- ── HOW TO USE ───────────────────────────────────────────────────────────
--   1. Run this whole file in the Supabase SQL editor.
--   2. Copy the single JSON value out of the result cell. It will look like
--        { "_constraints": { "public.dnt_appointments": { "...": "..." } } }
--      and will be SMALL -- a few dozen lines, not a few hundred.
--   3. Save it anywhere, e.g. /tmp/constraints.json, and merge:
--
--        python -c "import io,json; s=json.load(io.open('db/schema_snapshot.json',encoding='utf-8')); c=json.load(io.open('/tmp/constraints.json',encoding='utf-8')); s['_constraints']=c['_constraints']; io.open('db/schema_snapshot.json','w',encoding='utf-8',newline='\n').write(json.dumps(s,indent=4)+'\n')"
--
--   4. Confirm the preflight stops saying COULD NOT CHECK:
--
--        python tools/sairn_sql_preflight.py --live db/schema_snapshot.json sql/<any file>.sql
--
--      The CHECK CONSTRAINTS section must report a comparison, not a
--      could-not-check. If it still says could-not-check, the merge did not
--      land and nothing about constraints has been verified.
--
-- ── AN EMPTY RESULT IS A REAL ANSWER AND MUST NOT BE DISCARDED ───────────
-- If the database genuinely has no CHECK constraints in `public`, this
-- returns `{"_constraints": {}}`. MERGE THAT ANYWAY. An empty object means
-- "asked, and there are none"; a missing key means "never asked", and the
-- preflight distinguishes the two. Dropping the empty result leaves the tool
-- unable to tell them apart, which is the whole failure this half addresses.

select jsonb_pretty(
  jsonb_build_object('_constraints', coalesce(
       (select jsonb_object_agg(x.rel, x.defs)
          from (
            select c.conrelid::regclass::text as rel,
                   jsonb_object_agg(c.conname, pg_get_constraintdef(c.oid)) as defs
              from pg_constraint c
              join pg_class     cl on cl.oid = c.conrelid
              join pg_namespace n  on n.oid = cl.relnamespace
             where n.nspname = 'public'
               and cl.relkind = 'r'         -- ordinary tables only
               and c.contype  = 'c'         -- CHECK only
             group by c.conrelid
          ) x),
       '{}'::jsonb))
);
