-- sql/undeclared_table_acl_check_2026-08-26.sql
-- READ-ONLY. Four SELECTs, independent, no shared state. Nothing here writes,
-- creates, drops, grants, revokes or alters.
--
-- ── THE QUESTION ──────────────────────────────────────────────────────────
-- `business_profiles`, `ai_memories` and `employees` were found on 2026-08-25
-- to be live with no schema file, and all three carried anon/authenticated
-- TRUNCATE/REFERENCES/TRIGGER -- the Supabase default-ACL baseline that
-- sql/append_only_grant_audit.sql and the 2026-08-24 TRUNCATE sweep removed
-- everywhere else. They were never in scope for either run for one reason: a
-- privilege sweep driven off sql/ inherits sql/'s omissions. It cannot revoke
-- on a table it has never heard of.
--
-- That is a mechanism, not a coincidence, so it should apply to EVERY
-- live-but-not-declared table -- 25 of them when the gap check ran on
-- 2026-08-25, 22 now that those three are declared. This file confirms that
-- rather than assuming it. The prediction is written down before the answer
-- comes back, on purpose: if the other 22 come back CLEAN, the reasoning above
-- is wrong and that is worth knowing more than being right was.
--
-- Section 2 is the answer. Sections 1 and 3 are controls, section 4 is scope.
--
-- The 227 names below are generated from every `create table` in sql/*.sql
-- with comments stripped by a quote-aware state machine, minus two transient
-- sweep baselines. 224 before the three new schema files, 227 after. Do NOT
-- hand-edit this list -- regenerate it. The naive version of the same
-- extraction counts `create table` inside COMMENTS and invents phantom tables
-- named `alone`, `anywhere`, `for`, `if` and `to` out of prose in file
-- headers, which is how a 231 got reported once already.

-- ── 1. CONTROL: the three tables just declared and revoked ─────────────────
-- Run this FIRST. Expect service_role -> INSERT, SELECT, UPDATE on each, and
-- NO anon or authenticated rows at all. If anon/authenticated still appear,
-- the revoke line in those migrations did not run and section 2 is measuring a
-- world that did not change. If service_role is missing or short a verb, the
-- `revoke all` ran and the re-grant did not -- stop and fix that first, it
-- breaks the live app.
select table_name,
       grantee,
       string_agg(privilege_type, ', ' order by privilege_type) as privileges
  from information_schema.role_table_grants
 where table_schema = 'public'
   and table_name in ('business_profiles', 'ai_memories', 'employees')
   and grantee in ('service_role', 'anon', 'authenticated')
 group by table_name, grantee
 order by table_name, grantee;

-- ── 2. THE ANSWER: anon/authenticated grants on every table that is LIVE ───
-- ──    but declared in no schema file ─────────────────────────────────────
-- The list is computed here rather than pasted, so it cannot go stale between
-- the gap check and this one. Expect ~22 tables. Any row returned is a table
-- where anon or authenticated hold a privilege they were never meant to have
-- on any table.
with declared(table_name) as (values
    ('ai_memories'),
    ('alf_activities'),
    ('alf_billing'),
    ('alf_claim_routes'),
    ('alf_clients'),
    ('alf_compliance_rules'),
    ('alf_facility'),
    ('alf_incidents'),
    ('alf_mar'),
    ('alf_op_audits'),
    ('alf_payer_rules'),
    ('alf_signals'),
    ('alf_staff'),
    ('alf_staff_credentials'),
    ('bld_bids'),
    ('bld_tna_assessments'),
    ('business_profiles'),
    ('cl_case_cache'),
    ('cl_citing_treatments'),
    ('cl_court_cache'),
    ('cl_coverage'),
    ('cl_feedback_log'),
    ('cl_rate_limit_log'),
    ('dnt_appointments'),
    ('dnt_ar'),
    ('dnt_booking_rate_limits'),
    ('dnt_charges'),
    ('dnt_complaints'),
    ('dnt_coverage_rules'),
    ('dnt_cred_rules'),
    ('dnt_credentials'),
    ('dnt_denial'),
    ('dnt_operatories'),
    ('dnt_patients'),
    ('dnt_payments'),
    ('dnt_procedure_types'),
    ('dnt_provider_hours'),
    ('dnt_providers'),
    ('dnt_referrals'),
    ('dnt_revenue'),
    ('dnt_settings'),
    ('employees'),
    ('fcl_rate_limit_log'),
    ('grd_boq_rates'),
    ('grd_designs'),
    ('grd_dreamclose'),
    ('grd_ecosystem_reports'),
    ('grd_employee_auth'),
    ('grd_golf_zones'),
    ('grd_invasive_sightings'),
    ('grd_invoices'),
    ('grd_irr_controllers'),
    ('grd_irr_schedules'),
    ('grd_irr_zones'),
    ('grd_jobs'),
    ('grd_progress_photos'),
    ('grd_properties'),
    ('grd_quotes'),
    ('grd_schedule'),
    ('grd_training_completions'),
    ('grd_training_courses'),
    ('grd_vendors'),
    ('grd_water_features'),
    ('law_clients'),
    ('law_deadline_rules'),
    ('law_deadlines'),
    ('law_holidays'),
    ('law_matters'),
    ('law_trusttx'),
    ('leg_aftercare'),
    ('leg_bookings'),
    ('leg_cases'),
    ('leg_catererorders'),
    ('leg_caterers'),
    ('leg_certs'),
    ('leg_clergy'),
    ('leg_clergybookings'),
    ('leg_cremations'),
    ('leg_custodylog'),
    ('leg_deathrecords'),
    ('leg_dispatches'),
    ('leg_documents'),
    ('leg_facilities'),
    ('leg_floristorders'),
    ('leg_florists'),
    ('leg_gplservices'),
    ('leg_guestbook'),
    ('leg_insurance'),
    ('leg_invoices'),
    ('leg_keepsakeorders'),
    ('leg_keepsakes'),
    ('leg_liverybookings'),
    ('leg_liveryvendors'),
    ('leg_maintenance'),
    ('leg_memorials'),
    ('leg_merch_catalog'),
    ('leg_merch_units'),
    ('leg_monuments'),
    ('leg_obituaries'),
    ('leg_petcases'),
    ('leg_plots'),
    ('leg_preneed'),
    ('leg_processions'),
    ('leg_tributes'),
    ('leg_vehicles'),
    ('msb_bottle_scans'),
    ('msb_food_cost_log'),
    ('msb_food_scans'),
    ('msb_food_waste'),
    ('msb_inventory_log'),
    ('msb_licenses'),
    ('msb_products'),
    ('msb_sale_hours'),
    ('msb_sales'),
    ('network_insights'),
    ('rf_cert_rules'),
    ('rf_certifications'),
    ('rf_claim_agreements'),
    ('rf_claim_photos'),
    ('rf_claims'),
    ('rf_company_programs'),
    ('rf_contingency_rules'),
    ('rf_invoice_counters'),
    ('rf_invoices'),
    ('rf_jobs'),
    ('rf_locations'),
    ('rf_photos'),
    ('rf_proposals'),
    ('rf_schedule'),
    ('sairn_agent_commands'),
    ('sairn_agents'),
    ('sairn_ai_rate_limit_log'),
    ('sairnbuild_employee_auth'),
    ('sairncare_employee_auth'),
    ('sairncash_trial'),
    ('sairncash_waitlist'),
    ('sairncode_audit_log'),
    ('sairncode_employee_auth'),
    ('sairndesign_employee_auth'),
    ('sairnlaw_audit_log'),
    ('sairnlaw_employee_auth'),
    ('sairnlegacy_employee_auth'),
    ('sairnroofing_employee_auth'),
    ('sairnscape_org_intel'),
    ('sairnsenior_employee_auth'),
    ('sb_employee_auth'),
    ('sc_anesthesia'),
    ('sc_anesthesia_base_units'),
    ('sc_ar'),
    ('sc_auth'),
    ('sc_auth_requests'),
    ('sc_claims'),
    ('sc_coded_items'),
    ('sc_compliance'),
    ('sc_credential_scope'),
    ('sc_credentials'),
    ('sc_denial'),
    ('sc_denial_events'),
    ('sc_dme'),
    ('sc_drg'),
    ('sc_eligibility'),
    ('sc_encoder'),
    ('sc_fraud'),
    ('sc_hcc'),
    ('sc_pctc'),
    ('sc_prebill'),
    ('sc_providers'),
    ('sc_query'),
    ('sc_rac'),
    ('sc_revenue'),
    ('sc_scrubrules'),
    ('sc_settings'),
    ('sc_specialty_checklists'),
    ('sc_specialty_checks'),
    ('sc_telehealth'),
    ('scp_customers'),
    ('scp_designs'),
    ('scp_employee_auth'),
    ('scp_invoices'),
    ('scp_irr_controllers'),
    ('scp_irr_schedules'),
    ('scp_irr_zones'),
    ('scp_jobs'),
    ('scp_progress_photos'),
    ('scp_quotes'),
    ('scp_schedule'),
    ('scp_vendors'),
    ('scp_water_features'),
    ('sd_blocks'),
    ('sd_bundles'),
    ('sd_crm'),
    ('sd_employee_auth'),
    ('sd_employee_profiles'),
    ('sd_progress_photos'),
    ('sd_render_usage'),
    ('sd_shared_knowledge'),
    ('sd_slab_history'),
    ('sd_slabs'),
    ('sd_sub_auth'),
    ('sd_sub_jobs'),
    ('sd_subs'),
    ('sd_webauthn_credentials'),
    ('sdn_clients'),
    ('sdn_colorcodes'),
    ('sdn_contracts'),
    ('sdn_discounts'),
    ('sdn_invoices'),
    ('sdn_moodboards'),
    ('sdn_pos'),
    ('sdn_projects'),
    ('sdn_proposals'),
    ('sdn_referrals'),
    ('sdn_roomdims'),
    ('sdn_samplerequests'),
    ('sdn_samples'),
    ('sdn_schedule'),
    ('sdn_specitems'),
    ('sdn_team'),
    ('sdn_timeentries'),
    ('sdn_vendors'),
    ('sen_caregivers'),
    ('sen_claims'),
    ('sen_clients'),
    ('sen_portal_links'),
    ('sen_visits'),
    ('stonedesk_audit_log'),
    ('wex_rate_limit_log')
)
select t.table_name,
       g.grantee,
       string_agg(g.privilege_type, ', ' order by g.privilege_type) as privileges
  from information_schema.tables t
  left join declared d on d.table_name = t.table_name
  join information_schema.role_table_grants g
    on g.table_schema = t.table_schema
   and g.table_name   = t.table_name
 where t.table_schema = 'public'
   and t.table_type   = 'BASE TABLE'
   and d.table_name is null              -- live, declared nowhere
   and g.grantee in ('anon', 'authenticated')
 group by t.table_name, g.grantee
 order by t.table_name, g.grantee;

-- ── 3. CONTROL: the same check across DECLARED tables ─────────────────────
-- This is what makes section 2 mean anything. If declared tables come back
-- clean and undeclared ones do not, the sql/-blind-spot explanation holds. If
-- BOTH sets carry the baseline, the earlier sweeps did not finish and this is
-- a much larger and more urgent finding than three tables. Expect zero rows.
with declared(table_name) as (values
    ('ai_memories'),
    ('alf_activities'),
    ('alf_billing'),
    ('alf_claim_routes'),
    ('alf_clients'),
    ('alf_compliance_rules'),
    ('alf_facility'),
    ('alf_incidents'),
    ('alf_mar'),
    ('alf_op_audits'),
    ('alf_payer_rules'),
    ('alf_signals'),
    ('alf_staff'),
    ('alf_staff_credentials'),
    ('bld_bids'),
    ('bld_tna_assessments'),
    ('business_profiles'),
    ('cl_case_cache'),
    ('cl_citing_treatments'),
    ('cl_court_cache'),
    ('cl_coverage'),
    ('cl_feedback_log'),
    ('cl_rate_limit_log'),
    ('dnt_appointments'),
    ('dnt_ar'),
    ('dnt_booking_rate_limits'),
    ('dnt_charges'),
    ('dnt_complaints'),
    ('dnt_coverage_rules'),
    ('dnt_cred_rules'),
    ('dnt_credentials'),
    ('dnt_denial'),
    ('dnt_operatories'),
    ('dnt_patients'),
    ('dnt_payments'),
    ('dnt_procedure_types'),
    ('dnt_provider_hours'),
    ('dnt_providers'),
    ('dnt_referrals'),
    ('dnt_revenue'),
    ('dnt_settings'),
    ('employees'),
    ('fcl_rate_limit_log'),
    ('grd_boq_rates'),
    ('grd_designs'),
    ('grd_dreamclose'),
    ('grd_ecosystem_reports'),
    ('grd_employee_auth'),
    ('grd_golf_zones'),
    ('grd_invasive_sightings'),
    ('grd_invoices'),
    ('grd_irr_controllers'),
    ('grd_irr_schedules'),
    ('grd_irr_zones'),
    ('grd_jobs'),
    ('grd_progress_photos'),
    ('grd_properties'),
    ('grd_quotes'),
    ('grd_schedule'),
    ('grd_training_completions'),
    ('grd_training_courses'),
    ('grd_vendors'),
    ('grd_water_features'),
    ('law_clients'),
    ('law_deadline_rules'),
    ('law_deadlines'),
    ('law_holidays'),
    ('law_matters'),
    ('law_trusttx'),
    ('leg_aftercare'),
    ('leg_bookings'),
    ('leg_cases'),
    ('leg_catererorders'),
    ('leg_caterers'),
    ('leg_certs'),
    ('leg_clergy'),
    ('leg_clergybookings'),
    ('leg_cremations'),
    ('leg_custodylog'),
    ('leg_deathrecords'),
    ('leg_dispatches'),
    ('leg_documents'),
    ('leg_facilities'),
    ('leg_floristorders'),
    ('leg_florists'),
    ('leg_gplservices'),
    ('leg_guestbook'),
    ('leg_insurance'),
    ('leg_invoices'),
    ('leg_keepsakeorders'),
    ('leg_keepsakes'),
    ('leg_liverybookings'),
    ('leg_liveryvendors'),
    ('leg_maintenance'),
    ('leg_memorials'),
    ('leg_merch_catalog'),
    ('leg_merch_units'),
    ('leg_monuments'),
    ('leg_obituaries'),
    ('leg_petcases'),
    ('leg_plots'),
    ('leg_preneed'),
    ('leg_processions'),
    ('leg_tributes'),
    ('leg_vehicles'),
    ('msb_bottle_scans'),
    ('msb_food_cost_log'),
    ('msb_food_scans'),
    ('msb_food_waste'),
    ('msb_inventory_log'),
    ('msb_licenses'),
    ('msb_products'),
    ('msb_sale_hours'),
    ('msb_sales'),
    ('network_insights'),
    ('rf_cert_rules'),
    ('rf_certifications'),
    ('rf_claim_agreements'),
    ('rf_claim_photos'),
    ('rf_claims'),
    ('rf_company_programs'),
    ('rf_contingency_rules'),
    ('rf_invoice_counters'),
    ('rf_invoices'),
    ('rf_jobs'),
    ('rf_locations'),
    ('rf_photos'),
    ('rf_proposals'),
    ('rf_schedule'),
    ('sairn_agent_commands'),
    ('sairn_agents'),
    ('sairn_ai_rate_limit_log'),
    ('sairnbuild_employee_auth'),
    ('sairncare_employee_auth'),
    ('sairncash_trial'),
    ('sairncash_waitlist'),
    ('sairncode_audit_log'),
    ('sairncode_employee_auth'),
    ('sairndesign_employee_auth'),
    ('sairnlaw_audit_log'),
    ('sairnlaw_employee_auth'),
    ('sairnlegacy_employee_auth'),
    ('sairnroofing_employee_auth'),
    ('sairnscape_org_intel'),
    ('sairnsenior_employee_auth'),
    ('sb_employee_auth'),
    ('sc_anesthesia'),
    ('sc_anesthesia_base_units'),
    ('sc_ar'),
    ('sc_auth'),
    ('sc_auth_requests'),
    ('sc_claims'),
    ('sc_coded_items'),
    ('sc_compliance'),
    ('sc_credential_scope'),
    ('sc_credentials'),
    ('sc_denial'),
    ('sc_denial_events'),
    ('sc_dme'),
    ('sc_drg'),
    ('sc_eligibility'),
    ('sc_encoder'),
    ('sc_fraud'),
    ('sc_hcc'),
    ('sc_pctc'),
    ('sc_prebill'),
    ('sc_providers'),
    ('sc_query'),
    ('sc_rac'),
    ('sc_revenue'),
    ('sc_scrubrules'),
    ('sc_settings'),
    ('sc_specialty_checklists'),
    ('sc_specialty_checks'),
    ('sc_telehealth'),
    ('scp_customers'),
    ('scp_designs'),
    ('scp_employee_auth'),
    ('scp_invoices'),
    ('scp_irr_controllers'),
    ('scp_irr_schedules'),
    ('scp_irr_zones'),
    ('scp_jobs'),
    ('scp_progress_photos'),
    ('scp_quotes'),
    ('scp_schedule'),
    ('scp_vendors'),
    ('scp_water_features'),
    ('sd_blocks'),
    ('sd_bundles'),
    ('sd_crm'),
    ('sd_employee_auth'),
    ('sd_employee_profiles'),
    ('sd_progress_photos'),
    ('sd_render_usage'),
    ('sd_shared_knowledge'),
    ('sd_slab_history'),
    ('sd_slabs'),
    ('sd_sub_auth'),
    ('sd_sub_jobs'),
    ('sd_subs'),
    ('sd_webauthn_credentials'),
    ('sdn_clients'),
    ('sdn_colorcodes'),
    ('sdn_contracts'),
    ('sdn_discounts'),
    ('sdn_invoices'),
    ('sdn_moodboards'),
    ('sdn_pos'),
    ('sdn_projects'),
    ('sdn_proposals'),
    ('sdn_referrals'),
    ('sdn_roomdims'),
    ('sdn_samplerequests'),
    ('sdn_samples'),
    ('sdn_schedule'),
    ('sdn_specitems'),
    ('sdn_team'),
    ('sdn_timeentries'),
    ('sdn_vendors'),
    ('sen_caregivers'),
    ('sen_claims'),
    ('sen_clients'),
    ('sen_portal_links'),
    ('sen_visits'),
    ('stonedesk_audit_log'),
    ('wex_rate_limit_log')
)
select t.table_name,
       g.grantee,
       string_agg(g.privilege_type, ', ' order by g.privilege_type) as privileges
  from information_schema.tables t
  join declared d on d.table_name = t.table_name
  join information_schema.role_table_grants g
    on g.table_schema = t.table_schema
   and g.table_name   = t.table_name
 where t.table_schema = 'public'
   and t.table_type   = 'BASE TABLE'
   and g.grantee in ('anon', 'authenticated')
 group by t.table_name, g.grantee
 order by t.table_name, g.grantee;

-- ── 4. SCOPE: totals, so a truncated paste is detectable ──────────────────
-- If declared_total is not 227, the VALUES lists above were truncated in
-- transit and sections 2-3 are unreliable -- do not read them.
with declared(table_name) as (values
    ('ai_memories'),
    ('alf_activities'),
    ('alf_billing'),
    ('alf_claim_routes'),
    ('alf_clients'),
    ('alf_compliance_rules'),
    ('alf_facility'),
    ('alf_incidents'),
    ('alf_mar'),
    ('alf_op_audits'),
    ('alf_payer_rules'),
    ('alf_signals'),
    ('alf_staff'),
    ('alf_staff_credentials'),
    ('bld_bids'),
    ('bld_tna_assessments'),
    ('business_profiles'),
    ('cl_case_cache'),
    ('cl_citing_treatments'),
    ('cl_court_cache'),
    ('cl_coverage'),
    ('cl_feedback_log'),
    ('cl_rate_limit_log'),
    ('dnt_appointments'),
    ('dnt_ar'),
    ('dnt_booking_rate_limits'),
    ('dnt_charges'),
    ('dnt_complaints'),
    ('dnt_coverage_rules'),
    ('dnt_cred_rules'),
    ('dnt_credentials'),
    ('dnt_denial'),
    ('dnt_operatories'),
    ('dnt_patients'),
    ('dnt_payments'),
    ('dnt_procedure_types'),
    ('dnt_provider_hours'),
    ('dnt_providers'),
    ('dnt_referrals'),
    ('dnt_revenue'),
    ('dnt_settings'),
    ('employees'),
    ('fcl_rate_limit_log'),
    ('grd_boq_rates'),
    ('grd_designs'),
    ('grd_dreamclose'),
    ('grd_ecosystem_reports'),
    ('grd_employee_auth'),
    ('grd_golf_zones'),
    ('grd_invasive_sightings'),
    ('grd_invoices'),
    ('grd_irr_controllers'),
    ('grd_irr_schedules'),
    ('grd_irr_zones'),
    ('grd_jobs'),
    ('grd_progress_photos'),
    ('grd_properties'),
    ('grd_quotes'),
    ('grd_schedule'),
    ('grd_training_completions'),
    ('grd_training_courses'),
    ('grd_vendors'),
    ('grd_water_features'),
    ('law_clients'),
    ('law_deadline_rules'),
    ('law_deadlines'),
    ('law_holidays'),
    ('law_matters'),
    ('law_trusttx'),
    ('leg_aftercare'),
    ('leg_bookings'),
    ('leg_cases'),
    ('leg_catererorders'),
    ('leg_caterers'),
    ('leg_certs'),
    ('leg_clergy'),
    ('leg_clergybookings'),
    ('leg_cremations'),
    ('leg_custodylog'),
    ('leg_deathrecords'),
    ('leg_dispatches'),
    ('leg_documents'),
    ('leg_facilities'),
    ('leg_floristorders'),
    ('leg_florists'),
    ('leg_gplservices'),
    ('leg_guestbook'),
    ('leg_insurance'),
    ('leg_invoices'),
    ('leg_keepsakeorders'),
    ('leg_keepsakes'),
    ('leg_liverybookings'),
    ('leg_liveryvendors'),
    ('leg_maintenance'),
    ('leg_memorials'),
    ('leg_merch_catalog'),
    ('leg_merch_units'),
    ('leg_monuments'),
    ('leg_obituaries'),
    ('leg_petcases'),
    ('leg_plots'),
    ('leg_preneed'),
    ('leg_processions'),
    ('leg_tributes'),
    ('leg_vehicles'),
    ('msb_bottle_scans'),
    ('msb_food_cost_log'),
    ('msb_food_scans'),
    ('msb_food_waste'),
    ('msb_inventory_log'),
    ('msb_licenses'),
    ('msb_products'),
    ('msb_sale_hours'),
    ('msb_sales'),
    ('network_insights'),
    ('rf_cert_rules'),
    ('rf_certifications'),
    ('rf_claim_agreements'),
    ('rf_claim_photos'),
    ('rf_claims'),
    ('rf_company_programs'),
    ('rf_contingency_rules'),
    ('rf_invoice_counters'),
    ('rf_invoices'),
    ('rf_jobs'),
    ('rf_locations'),
    ('rf_photos'),
    ('rf_proposals'),
    ('rf_schedule'),
    ('sairn_agent_commands'),
    ('sairn_agents'),
    ('sairn_ai_rate_limit_log'),
    ('sairnbuild_employee_auth'),
    ('sairncare_employee_auth'),
    ('sairncash_trial'),
    ('sairncash_waitlist'),
    ('sairncode_audit_log'),
    ('sairncode_employee_auth'),
    ('sairndesign_employee_auth'),
    ('sairnlaw_audit_log'),
    ('sairnlaw_employee_auth'),
    ('sairnlegacy_employee_auth'),
    ('sairnroofing_employee_auth'),
    ('sairnscape_org_intel'),
    ('sairnsenior_employee_auth'),
    ('sb_employee_auth'),
    ('sc_anesthesia'),
    ('sc_anesthesia_base_units'),
    ('sc_ar'),
    ('sc_auth'),
    ('sc_auth_requests'),
    ('sc_claims'),
    ('sc_coded_items'),
    ('sc_compliance'),
    ('sc_credential_scope'),
    ('sc_credentials'),
    ('sc_denial'),
    ('sc_denial_events'),
    ('sc_dme'),
    ('sc_drg'),
    ('sc_eligibility'),
    ('sc_encoder'),
    ('sc_fraud'),
    ('sc_hcc'),
    ('sc_pctc'),
    ('sc_prebill'),
    ('sc_providers'),
    ('sc_query'),
    ('sc_rac'),
    ('sc_revenue'),
    ('sc_scrubrules'),
    ('sc_settings'),
    ('sc_specialty_checklists'),
    ('sc_specialty_checks'),
    ('sc_telehealth'),
    ('scp_customers'),
    ('scp_designs'),
    ('scp_employee_auth'),
    ('scp_invoices'),
    ('scp_irr_controllers'),
    ('scp_irr_schedules'),
    ('scp_irr_zones'),
    ('scp_jobs'),
    ('scp_progress_photos'),
    ('scp_quotes'),
    ('scp_schedule'),
    ('scp_vendors'),
    ('scp_water_features'),
    ('sd_blocks'),
    ('sd_bundles'),
    ('sd_crm'),
    ('sd_employee_auth'),
    ('sd_employee_profiles'),
    ('sd_progress_photos'),
    ('sd_render_usage'),
    ('sd_shared_knowledge'),
    ('sd_slab_history'),
    ('sd_slabs'),
    ('sd_sub_auth'),
    ('sd_sub_jobs'),
    ('sd_subs'),
    ('sd_webauthn_credentials'),
    ('sdn_clients'),
    ('sdn_colorcodes'),
    ('sdn_contracts'),
    ('sdn_discounts'),
    ('sdn_invoices'),
    ('sdn_moodboards'),
    ('sdn_pos'),
    ('sdn_projects'),
    ('sdn_proposals'),
    ('sdn_referrals'),
    ('sdn_roomdims'),
    ('sdn_samplerequests'),
    ('sdn_samples'),
    ('sdn_schedule'),
    ('sdn_specitems'),
    ('sdn_team'),
    ('sdn_timeentries'),
    ('sdn_vendors'),
    ('sen_caregivers'),
    ('sen_claims'),
    ('sen_clients'),
    ('sen_portal_links'),
    ('sen_visits'),
    ('stonedesk_audit_log'),
    ('wex_rate_limit_log')
)
select (select count(*) from declared)                          as declared_total,
       (select count(*) from information_schema.tables
         where table_schema = 'public'
           and table_type   = 'BASE TABLE')                     as live_total,
       (select count(*) from information_schema.tables t
          left join declared d on d.table_name = t.table_name
         where t.table_schema = 'public'
           and t.table_type   = 'BASE TABLE'
           and d.table_name is null)                            as live_but_not_declared;
