-- sql/unused_delete_grant_revoke_2026-08-24.sql
-- Revokes service_role's DELETE on every public table EXCEPT the SAIRNcode
-- sc_* family, which is the only app with a real, reachable delete path.
--
-- Same three-section shape as sql/full_crud_truncate_sweep_2026-08-24.sql:
-- discover live, review, then fix. The table list is NEVER hand-written --
-- it is pulled from information_schema at run time, so a table added after
-- this file was written is still covered.
--
-- ── COUNT CORRECTION 2026-08-25: THE "~107 / ~78" FIGURE WAS WRONG ────────
-- A live count on 2026-08-25 returned 135 non-sc_* tables holding DELETE,
-- not the ~78 this file's first revision implied. Reconciled before any
-- revoke runs, because a 57-table gap is not a rounding difference.
--
-- CAUSE: the original figure came from a TRUNCATED EXPORT, and was then
-- written into docs/SAIRN-OPEN-WORK-INDEX.md as though it described the
-- database. sql/full_crud_truncate_sweep_2026-08-24.sql records the same
-- root cause in its own header, found independently by the SAIRN-cc
-- session: "Michael's SQL client had a row limit; the first export
-- (100 rows) was confirmed truncated by cross-checking against tables
-- already known to exist (SAIRNlegacy alone continues well past where
-- that export stopped)." The real export is 227 tables. Any count near
-- 100 taken during that window is capped, not measured.
--
-- NOT THE CAUSE -- checked, not assumed: new tables created since. origin
-- has no schema commit after the original count; the only unpushed work in
-- any sibling clone (SAIRN-cc dd5327b) adds documentation and zero tables.
-- New tables account for approximately none of the 57.
--
-- WHERE THE 135 COMES FROM -- predicted from repo grant lines, then
-- CHECKED against Section 1's real output on 2026-08-25:
--   131  non-sc_* tables this repo grants anything on to service_role
--    83    of those carry an explicit `grant ... delete` line  <- the
--          original count, i.e. it counted GRANT LINES IN THIS REPO and
--          reported them as live rows. scp_employee_auth is one of these.
--    48    of those are granted only SELECT/INSERT/UPDATE here -- 10 of
--          which explicitly REVOKE delete, leaving 38 candidates.
--          *** ALL 38 CAME BACK CLEAN. Zero hold DELETE. ***
--   ~52  the real remainder: tables with NO grant-delete line in this repo
--          at all, consistent with 227 live tables vs 131 granted here.
--          This is where the 57-table gap actually lived -- untracked
--          schema, not a default privilege.
--
-- MY FIRST EXPLANATION WAS WRONG AND IS RECORDED AS WRONG: I predicted the
-- 48 (later 38) would be "granted only SELECT/INSERT/UPDATE here yet hold
-- DELETE live anyway", and proposed that as evidence the grant arrives by
-- default privilege. The live result is the exact opposite. The arithmetic
-- 83 + 48 + 4 = 135 fitted well enough to look like confirmation and was
-- coincidence. Flagged as unverified at the time, which is the only reason
-- it did not become a fact in this file.
--
-- ── AUDIT-LOG CHECK CAME BACK CLEAN, AND MY TEST WAS A BAD TEST ──────────
-- Confirmed live 2026-08-25: sairncode_audit_log, stonedesk_audit_log and
-- sairnlaw_audit_log all show INSERT/SELECT only, no DELETE. The
-- `revoke all ... from service_role` pattern does what it is supposed to.
-- It is not broken -- it is just not universal (9 tables use it; see
-- `grep -l "revoke all.*from service_role" sql/*.sql`).
--
-- But I proposed those three as the DISCRIMINATING test, and they are not.
-- All three are EXPLICITLY protected in their own schema files --
-- sairncode_audit_log and stonedesk_audit_log by `revoke all` first,
-- sairnlaw_audit_log by an explicit `revoke update, delete ... from
-- service_role` at sql/sairnlaw_audit_log*.sql:87. A table that explicitly
-- revokes DELETE showing no DELETE is consistent with BOTH hypotheses and
-- therefore separates neither. Recording this because the wrong test
-- passing is easy to mistake for the question being answered.
--
-- CANDIDATE SET NARROWED 48 -> 38. The first pass counted only `grant`
-- lines and ignored `revoke` lines, so it wrongly listed all 10 explicitly
-- protected tables as candidates. Re-parsed for both verbs: 38 non-sc_*
-- tables are granted SELECT/INSERT/UPDATE with NO delete granted AND no
-- revoke protecting them. Those 38 -- alf_* (13), sen_* (5), sd_sub*/sd_subs
-- (3), the eight *_employee_auth tables, bld_bids, bld_tna_assessments,
-- dnt_cred_rules, dnt_credentials, sairncash_trial, sairncash_waitlist,
-- sairnscape_org_intel, sd_render_usage, sd_shared_knowledge -- are the
-- real discriminator. RESOLVED BELOW: they came back clean, so the second
-- branch is what happened -- the 135 is 83 explicit grants plus ~52 tables
-- with no tracked schema, and the default-ACL question is moot.
--
-- ── SECTION 1 RAN 2026-08-25. 135 ROWS. RESULT: 0 OF THE 38 HOLD DELETE ──
-- The candidate hypothesis is DEAD, and cleanly so. All 38 tables that are
-- granted SELECT/INSERT/UPDATE with no delete granted and no revoke
-- protecting them came back CLEAN. Nothing is arriving by default.
--
-- ONE CORRECTION TO HOW THIS WAS REPORTED BACK: the single table found
-- holding DELETE, scp_employee_auth, was NOT one of the 38. It was in the
-- 83 -- the set with an EXPLICIT `grant ... delete` line in this repo. So
-- the score is 0 of 38, not 1 of 38, which makes the result stronger, not
-- weaker: no unprotected table anywhere acquired DELETE without being
-- explicitly granted it.
--
-- ── WHY scp_employee_auth DIFFERS FROM THE OTHER SEVEN: IT JUST SAYS SO ──
-- Not a missing revoke, not grant order, not a stray `grant all`, and not
-- a fix applied to the others but never to it. sql/scp_employee_auth_schema.sql:47
-- literally reads:
--     grant select, insert, update, delete on scp_employee_auth to service_role;
-- It is the ONLY *_employee_auth file on the platform whose grant line
-- contains `delete` -- confirmed by
-- `grep -niE "^\s*grant[^;]*delete[^;]*employee_auth" sql/*.sql`, one hit.
-- Every sibling (sb_, sairncode_, sairnlaw_, sairnbuild_, sairncare_,
-- sairndesign_, sairnlegacy_, sairnsenior_) grants `select, insert, update`
-- and stops.
--
-- The file's own header says why, and the reason is an OVERCORRECTION, not
-- an oversight: "GRANT statements included explicitly this session
-- (2026-08-06) -- a known recurring gap flagged after the SAIRNgrounds
-- license-row issue. service_role bypasses RLS by default in Supabase, but
-- being explicit here removes any ambiguity rather than relying on that
-- default silently." The author was fixing a pattern of MISSING grants and,
-- being explicit, wrote the full CRUD verb list instead of the verbs the
-- app actually uses. SAIRNscape has no delete path -- the platform's only
-- DELETE is the SAIRNcode branch -- so it has never been used.
--
-- That makes it exactly what this sweep is for, and it should still be
-- revoked. Root cause understood, not revoked blind.
--
-- ── WHAT THE REMAINING ~52 ROWS ARE ──────────────────────────────────────
-- 135 live, minus the 83 with an explicit repo grant-delete line, leaves
-- ~52 unaccounted for by any grant line in sql/*.sql. That is the
-- untracked-schema bucket, and it is consistent in size with the gap
-- already known: 227 live tables against 131 this repo grants anything on.
-- Some of the 83 may also never have been run (commit 6776f99 found two
-- audited tables that do not exist), so ~52 is a floor, not a fixed number.
-- EXACT BUCKETING NEEDS THE 135-ROW LIST ITSELF, which this session has not
-- seen -- only the 38-candidate verdict was reported back. Section 2 acts
-- correctly on all of them regardless, since it is list-free and preserves
-- whatever SELECT/INSERT/UPDATE each table already holds.
--
-- ── DOES THE DEFAULT-ACL FIX NEED WIDENING TO INCLUDE DELETE? NO ─────────
-- ANSWERED 2026-08-25 by the result above, ahead of the pg_default_acl
-- query: 37 of 38 -- now 38 of 38 -- tables with NO revoke protecting them
-- hold no DELETE. If any default privilege granted DELETE, those tables
-- would have it. They do not. Widening Section 4 of
-- sql/append_only_grant_audit.sql to include `delete` would be a no-op that
-- reads like a fix. DO NOT WIDEN IT.
--
-- The pg_default_acl query (every row, not just postgres's) is still worth
-- running, but it is now CONFIRMATORY rather than decisive. If it somehow
-- shows a second defaclrole granting DELETE, that would CONTRADICT the live
-- table evidence and the contradiction itself would be the finding -- do
-- not quietly reconcile it in favour of either side.
--
-- ── SUPERSEDED REASONING, KEPT SO IT IS NOT RE-DERIVED ───────────────────
-- sql/append_only_grant_audit.sql Section 4 revokes only
-- `truncate, references, trigger, maintain` from the default privileges,
-- not delete. Whether that needs widening depends entirely on the answer
-- above -- and there is already evidence in hand that it does NOT:
--
--   * Section 1a of that file confirmed live what postgres's default ACL
--     actually grants service_role: TRUNCATE, REFERENCES, TRIGGER,
--     MAINTAIN. DELETE is NOT in that list. If DELETE is not in the
--     default ACL, revoking it from the default ACL changes nothing.
--   * Section 1b of that file records dnt_credentials -- which IS one of
--     the 38 -- reading `del=f` before the fix. That is a table with no
--     delete grant, no revoke, and no DELETE. Exactly what the "default
--     privilege is not the source" answer predicts.
--
-- Both bullets above turned out to be right, and Section 1's real output
-- settled it directly rather than by inference. dnt_credentials was one of
-- the 38 and came back clean, matching its recorded `del=f`.
--
-- STATUS OF THIS BLOCK: superseded, not wrong. Kept because the reasoning
-- is what made the 38 the right thing to ask about, and because a later
-- session finding the pg_default_acl output should know this question was
-- already answered from the table side first.
--
-- ── WHY ───────────────────────────────────────────────────────────────────
-- Exactly ONE piece of code in the entire repo issues a DELETE:
-- api/sd-data.js, inside the SC_RESOURCES branch (line 5029 as of
-- 2026-08-25 -- the line number drifts as that file grows, the branch
-- does not; it was 4980 when this file was first written), gated by a
-- server-side re-check that the caller holds a valid SAIRNcode *admin*
-- session (a forged client claim of admin-ness is rejected there). Verified
-- by grepping every .js/.cjs/.mjs/.ts/.html in the repo, not just api/ --
-- one hit, no others.
--
-- Every other table's DELETE grant is a default copied forward through
-- schema files. Nothing built or planned needs it:
--   * erroneous-entry correction -> upsert on (license_hash, <entry>_id),
--     which is how every sd_*/grd_*/msb_* resource already works
--   * job/appointment cancellation -> a status ('Cancelled', 'INACTIVE'),
--     because a cancelled job you cannot see is indistinguishable from one
--     that never existed
--   * GDPR erasure -> the platform's own design (SAIRNcare) KEEPS the
--     identifier plus a suppression flag and reason code and deletes the
--     surrounding personal data. That is field-level redaction inside a
--     retained row -- an UPDATE, not a DELETE. These tables hold stone
--     inventory, landscaping jobs and beverage sales, not the personal-data
--     surface an erasure request targets anyway.
--
-- The grant is also the ONLY layer here. Every one of these tables has RLS
-- `for all using (false) with check (false)`, and service_role bypasses RLS
-- entirely -- so the grant is the sole thing between a leaked service key,
-- or a future coding mistake, and irreversible row loss.
--
-- One table makes the contradiction explicit: sd_slab_history is documented
-- in sql/sd_slab_lineage_schema.sql as "one row per event, append-only in
-- practice" and is granted DELETE. That is the provenance trail someone
-- reads when auditing a high-value slab.
--
-- ── NOTHING INTERNAL RELIES ON THIS, CHECKED NOT ASSUMED ──────────────────
-- The cleanup scripts that DO issue real deletes against in-scope tables
-- (sql/rbac_test_artifact_cleanup.sql -> msb_sales, grd_progress_photos;
-- sairndesign_*_cleanup.sql; sairncash_verification_trial_cleanup.sql;
-- sairndental_credentials_verify_cleanup.sql) run in the Supabase SQL
-- editor as the owner role, NOT as service_role. rbac_test_artifact_cleanup
-- says so in its own header: "This needs direct Supabase access -- same
-- hand-off as every other provisioning/schema step." Revoking service_role's
-- DELETE does not affect them. Neither Vercel cron
-- (/api/sairndental/send-reminder, /api/alf-alerts) deletes anything.
--
-- ── REVERSAL ──────────────────────────────────────────────────────────────
-- One line per table: GRANT DELETE ON public.<t> TO service_role.
-- This does NOT foreclose the deferred test/demo-data cleanup capability in
-- SAIRN-BACKLOG.md -- that item is explicitly undecided between soft- and
-- hard-delete. Revoking forces the decision to be made deliberately rather
-- than inherited from a copied grant.

-- ── SECTION 1: DISCOVER -- run this first, review the real output ─────────
-- Every table service_role can DELETE from that is NOT SAIRNcode's.
-- These are the rows Section 2 will change.

select
  t.table_name,
  string_agg(distinct g.privilege_type, ', ' order by g.privilege_type) as current_privs
from information_schema.tables t
join information_schema.role_table_grants g
  on g.table_name = t.table_name and g.table_schema = t.table_schema
where t.table_schema = 'public'
  and g.grantee = 'service_role'
  and t.table_name not like 'sc\_%'
group by t.table_name
having bool_or(g.privilege_type = 'DELETE')
order by t.table_name;

-- Sanity counterpart -- the sc_* tables that must be LEFT ALONE.
-- Expect the SAIRNcode family here, and expect Section 2 not to touch them.
--
-- select t.table_name
-- from information_schema.tables t
-- join information_schema.role_table_grants g
--   on g.table_name = t.table_name and g.table_schema = t.table_schema
-- where t.table_schema = 'public' and g.grantee = 'service_role'
--   and t.table_name like 'sc\_%'
-- group by t.table_name
-- having bool_or(g.privilege_type = 'DELETE')
-- order by t.table_name;

-- ── SECTION 2: DRAFT FIX -- NOT RUN. Review Section 1's real output first. ──
-- Revoke-then-grant, so nothing regresses: strips ALL of service_role's
-- privileges on the table, then re-grants exactly whichever of
-- SELECT/INSERT/UPDATE it already held -- never more, never fewer, and
-- never DELETE. A table that somehow held only DELETE ends with no grant,
-- which is reported rather than silently done.
--
-- Excludes sc_* by the same pattern Section 1 uses, so the 29 SAIRNcode
-- grants are untouched. Idempotent and safe to re-run. Touches no row data.
--
-- DO $$
-- DECLARE
--   r RECORD;
--   keep_privs TEXT;
-- BEGIN
--   FOR r IN
--     SELECT t.table_name,
--            string_agg(DISTINCT g.privilege_type, ', ') AS all_privs
--     FROM information_schema.tables t
--     JOIN information_schema.role_table_grants g
--       ON g.table_name = t.table_name AND g.table_schema = t.table_schema
--     WHERE t.table_schema = 'public'
--       AND g.grantee = 'service_role'
--       AND t.table_name NOT LIKE 'sc\_%'
--       -- EXCLUDED ON MICHAEL'S DECISION 2026-08-25. Not a judgement call
--       -- left open any more: license_keys has no tracked CREATE TABLE
--       -- anywhere in this repo, so Section 2's output cannot be checked
--       -- against an expected schema, and every license check on the
--       -- platform depends on it. Real risk, not worth carrying in the same
--       -- pass as the rest. The truncate sweep excluded it for the same
--       -- reason. It gets its own dedicated review -- see the license_keys
--       -- row in docs/SAIRN-OPEN-WORK-INDEX.md. Do NOT quietly fold it back
--       -- into a later sweep.
--       AND t.table_name <> 'license_keys'
--     GROUP BY t.table_name
--     HAVING bool_or(g.privilege_type = 'DELETE')
--   LOOP
--     SELECT string_agg(priv, ', ') INTO keep_privs
--     FROM unnest(string_to_array(r.all_privs, ', ')) AS priv
--     WHERE priv IN ('SELECT', 'INSERT', 'UPDATE');
--
--     EXECUTE format('REVOKE ALL ON public.%I FROM service_role', r.table_name);
--     IF keep_privs IS NOT NULL THEN
--       EXECUTE format('GRANT %s ON public.%I TO service_role', keep_privs, r.table_name);
--     END IF;
--
--     RAISE NOTICE 'Revoked DELETE on %: kept %', r.table_name,
--       coalesce(keep_privs, '(nothing -- this table held ONLY DELETE, check it)');
--   END LOOP;
-- END $$;

-- ── SECTION 3: VERIFY, after Section 2 is actually run ───────────────────
-- Re-run SECTION 1. Expect EXACTLY ONE row: license_keys, still holding
-- DELETE, because Section 2 deliberately excludes it (see the exclusion
-- comment there and the license_keys row in the open-work index). Anything
-- ELSE still listed is a real miss and needs investigating.
--
-- NOT "expect zero rows" -- that was this file's wording before license_keys
-- was excluded on 2026-08-25, and leaving it would have made the deliberate
-- exclusion look like a failed revoke.
--
-- And confirm SAIRNcode was untouched -- expect its full family back,
-- every row still showing DELETE:
--
-- select t.table_name,
--        string_agg(distinct g.privilege_type, ', ' order by g.privilege_type) as privs
-- from information_schema.tables t
-- join information_schema.role_table_grants g
--   on g.table_name = t.table_name and g.table_schema = t.table_schema
-- where t.table_schema = 'public' and g.grantee = 'service_role'
--   and t.table_name like 'sc\_%'
-- group by t.table_name
-- having bool_or(g.privilege_type = 'DELETE')
-- order by t.table_name;
--
-- Then confirm the app still works where it must: SAIRNcode's delete path
-- (api/sd-data.js SC_RESOURCES branch, admin session) must still succeed,
-- and a normal read/write round-trip on any sd_*/grd_*/dnt_* resource must
-- still succeed. A 403 from PostgREST on a WRITE would mean the re-grant
-- dropped a privilege -- that is what Section 2's keep_privs exists to
-- prevent, and what this check exists to catch if it failed anyway.

-- ── WHAT THIS DOES NOT COVER ──────────────────────────────────────────────
-- * The `anon` and `authenticated` roles. This file only touches
--   service_role. Those roles are locked out by RLS on these tables, but
--   their grants were not audited here.
-- * Schemas other than public.
-- * THE SOURCE LINE IN scp_employee_auth's OWN SCHEMA FILE. Section 2
--   revokes the live grant, but sql/scp_employee_auth_schema.sql:47 still
--   reads `grant select, insert, update, delete ...`. That file is
--   `create table if not exists` and safe to re-run, so re-running it after
--   this sweep would put DELETE straight back. Fix the line to
--   `grant select, insert, update` to match its eight siblings. Not done
--   here because this file is a grant sweep, not a schema edit, and the two
--   should not land in one commit.
-- * The DEFAULT PRIVILEGES that made this recur -- a new table created by a
--   schema file that copies the usual `grant select, insert, update, delete`
--   line will reintroduce a DELETE grant. The durable fix is to stop writing
--   `delete` into new schema files; this sweep only cleans what exists now.
